### ISSUE TITLE
上传File图片文件的时候java.security.cert.CertificateException:异常

### ISSUE THREAD

**Issue by magic0908** [jeasonlzy/okhttp-OkGo#100]
我把File图片转成FileInputStream上传，调用setCertificates()方法的时候报java.security.cert.CertificateException:异常，希望作者有时间看看，异常信息：
java.security.cert.CertificateException: com.android.org.conscrypt.OpenSSLX509CertificateFactory$ParsingException: com.android.org.conscrypt.OpenSSLX509CertificateFactory$ParsingException: java.lang.RuntimeException: error:0D0680A8:asn1 encoding routines:ASN1_CHECK_TLEN:wrong tag
11-13 22:29:16.695 18926-18926/com.iwxingbtu.hxt W/System.err:     at com.android.org.conscrypt.OpenSSLX509CertificateFactory.engineGenerateCertificate(OpenSSLX509CertificateFactory.java:272)
11-13 22:29:16.695 18926-18926/com.iwxingbtu.hxt W/System.err:     at java.security.cert.CertificateFactory.generateCertificate(CertificateFactory.java:195)
11-13 22:29:16.695 18926-18926/com.iwxingbtu.hxt W/System.err:     at com.lzy.okgo.https.HttpsUtils.prepareTrustManager(HttpsUtils.java:66)
11-13 22:29:16.695 18926-18926/com.iwxingbtu.hxt W/System.err:     at com.lzy.okgo.https.HttpsUtils.getSslSocketFactory(HttpsUtils.java:36)
11-13 22:29:16.695 18926-18926/com.iwxingbtu.hxt W/System.err:     at com.lzy.okgo.request.BaseRequest.setCertificates(BaseRequest.java:139)

**Comment by jeasonlzy** [comment]
这个方法是做https设置证书的，并不是上传图片的。。你把图片传给证书的方法，当然是异常。

**Comment by jeasonlzy** [comment]
上传图片 直接使用 params("key",new File(你的图片路径))  就可以上传了

**Comment by magic0908** [comment]
主要是我们后台这边是要用io流来接收文件的，不然上传不成功，然后我就看了只有setCertificates()方法里面的参数是传inputStream的，所以就用这个设置了。这样的话安卓端这边是要怎么用io流上传呢？还是说需要后台重新写一个新接口，支持File文件直接上传？

**Comment by jeasonlzy** [comment]
okgo 直接传 file，框架内部就是按流上传的。。不需要任何额外操作，后台直接按流解析即可。

**Comment by magic0908** [comment]
你好，我在安卓端这边设置了.isMultipart(true)，但是log打印信息的时候还是Content-Type: application/json;charset=utf-8 ，不能强制设置为Content-Type:multipart/form-data。所以上传图片还是有问题，我把代码贴一下，麻烦作者有时间看下：
Android端： OkGo.post(HttpUrl.UpLoadFile)
                        .tag(this)
                        .isMultipart(true)
                        .params("action", "customerHeadPic")
                        .params("ssoid", ssoId)
                        .params("userId", userId)
                        .params("dataId", userId)
                        .params("file",file，file.getName())
                        .execute(new StringCallback() {
                            @Override
                            public void onSuccess(String s, Call call, Response response) {
                                Log.i(Config.TAG, "ss-->>" + s);
                            }
                        });
 另外问一下，我这边后台接收文件的时候，不需要在params里面传key的，只需要传一个流就行了。也就是 .params(file文件) 这样接收的，然后okgo的框架内部是自己转成流的，一定要一个key和一个file文件，于是我就自己添加一个key和一个file文件，这样会不会有影响？

**Comment by jeasonlzy** [comment]
你看清楚是请求的content-type还是响应的 content-type，估计你是看错了。其余的问题也不好回答你，建议你先看看 http 上传文件的协议。协议搞明白了，这些问题你就明白了。

这里有张我画的图，先看协议在看图。

![k m3 w xkmvyyu51 f v](https://cloud.githubusercontent.com/assets/13421975/20741373/b92826cc-b704-11e6-8fbf-ae6b22417503.png)

**Comment by nwq-miao** [comment]
哥们问题解决没，分享下呗
