### ISSUE TITLE
post同时使用params和upString传值会导致params参数丢失？

### ISSUE THREAD

**Issue by tank62** [jeasonlzy/okhttp-OkGo#101]
`BaseRequest` baseRequest = OkGo.post(url).tag(context)
                .params("data", paramStr)
                .upJson(files.toString())
                .connTimeOut(ConfigUtil.TIMEOUT_MILLISECONDS_LONG)
                .writeTimeOut(ConfigUtil.TIMEOUT_MILLISECONDS_LONG)
                `.readTimeOut(ConfigUtil.TIMEOUT_MILLISECONDS_LONG);`

后台取不到data
单独使用 .params("data", paramStr)就可以取到。

com.lzy.okgo.request.BaseBodyRequest  在这个类中看到如下代码

 @Override
    public RequestBody generateRequestBody() {
        if (requestBody != null) return requestBody;                                           //自定义的请求体
        if (string != null && mediaType != null) return RequestBody.create(mediaType, string); //post上传字符串数据
        if (json != null && mediaType != null) return RequestBody.create(mediaType, json);     //post上传json数据
        if (bs != null && mediaType != null) return RequestBody.create(mediaType, bs);         //post上传字节数组
        return HttpUtils.generateMultipartRequestBody(params);
    }

只能支持一种参数？

**Comment by jeasonlzy** [comment]
是的。。这个在文档中写的很清楚。。使用 upString 这种方式的时候会清空之前所有的 请求体，也就是参数了。。

**Comment by tank62** [comment]
这个问题好解决吗？

**Comment by tank62** [comment]
有没有别的方式能实现？

**Comment by jeasonlzy** [comment]
这个是协议层的东西。。无法解决。。你应该确定的是你们的传参方式。。并没有这样传递参数的。
