### ISSUE TITLE
加入缓存模式后老是出现异常cacheMode(CacheMode.FIRST_CACHE_THEN_REQUEST)

### ISSUE THREAD

**Issue by ExcellentLife-FeiFan** [jeasonlzy/okhttp-OkGo#102]
getRequest.cacheMode(CacheMode.FIRST_CACHE_THEN_REQUEST);

加入缓存模式后老是出现以下报的异常

java.lang.ExceptionInInitializerError
                                                                 at com.lzy.okgo.adapter.CacheCall.execute(CacheCall.java:66)
                                                                 at com.lzy.okgo.request.BaseRequest.execute(BaseRequest.java:432)

这是怎么回事呀，整了好久都搞不明白？？？

**Comment by jeasonlzy** [comment]
你没有在 Application 调用 OkGo.init(this)； 初始化

**Comment by ExcellentLife-FeiFan** [comment]
private void initOkGo() {
        OkGo.init(this);
        try {
          
            OkGo.getInstance()
               
                    .debug("OkGo")
                
                    .setConnectTimeout(OkGo.DEFAULT_MILLISECONDS)  //全局的连接超时时间
                    .setReadTimeOut(OkGo.DEFAULT_MILLISECONDS)     //全局的读取超时时间
                    .setWriteTimeOut(OkGo.DEFAULT_MILLISECONDS)    //全局的写入超时时间
              
                    .setCacheMode(CacheMode.NO_CACHE)
            
                    .setCacheTime(CacheEntity.CACHE_NEVER_EXPIRE)
    
                    .setCookieStore(new MemoryCookieStore())               
                    .setCookieStore(new PersistentCookieStore());       
        } catch (Exception e) {
            e.printStackTrace();
        }
    }


我初始化了呀

**Comment by luvictor** [comment]
@ExcellentLife-FeiFan 你在Application中初始化的是.setCacheMode(CacheMode.NO_CACHE)，无缓存模式。 然后具体的请求是CacheMode.FIRST_CACHE_THEN_REQUEST。 两种模式冲突导致
