### ISSUE TITLE
后台数据返回 是xml

### ISSUE THREAD

**Issue by kuaige** [jeasonlzy/okhttp-OkGo#104]
<string xmlns="http://tempuri.org/">
这里是json
</string>
这种格式,我要在哪去先去处理数据.

**Comment by kuaige** [comment]
<string xmlns="http://tempuri.org/">
这里是json
</string>

**Comment by kuaige** [comment]
<strin河蟹g xmlns="http://tempuri.org/">
这里是json
</strin河蟹g>

**Comment by kuaige** [comment]
<s河蟹trin河蟹g xm河蟹ln河蟹s="htt河蟹p://tempuri.o河蟹rg/">
这里是json
河蟹</strin河蟹g河蟹>河蟹

**Comment by jeasonlzy** [comment]
和son一样，在convertSuccess 中。。只是一个是解析 json 一个是解析 xml
