### ISSUE TITLE
没有办法传任意对象吗？

### ISSUE THREAD

**Issue by happinesspeople** [jeasonlzy/okhttp-OkGo#106]
params.put....
这个只能传list--String/list--file而已吗？
其他的比如说list--integer之类的 不能传吗
只能转化为json再传吗？这样很不方便啊

**Comment by jeasonlzy** [comment]
实际上就算你传的  integer，我也是内部转成了string上传的，如果我接受 任意对象的话，使用者就不一定只传这些东西了，可能直接给我传个javabean过来，这样我是无法解析的，所以限制接受数据类型，自行转成string后传入，不过使用 params 传的话，是允许接受int，long 等类型的。。

**Comment by happinesspeople** [comment]
好的 了解了 谢谢
