### ISSUE TITLE
使用stetho调试工具，能拦截到网络请求，但是接受不到返回值？

### ISSUE THREAD

**Issue by kevin1202** [jeasonlzy/okhttp-OkGo#109]
使用stetho调试工具，能拦截到网络请求，但是接受不到返回值？
```
  OkGo.getInstance().getOkHttpClientBuilder().addNetworkInterceptor(new StethoInterceptor()).build();
```
请问该怎么处理？

**Comment by jeasonlzy** [comment]
这个具体可能和okgo关系不大，可能是拦截器的具体代码导致的。。实际上okgo也只是把你传进来拦截器丢给了 okhttp，并没有做任何操作。。

**Comment by kevin1202** [comment]
我现在已经解决了，当时没有使用你的代码`OkGo.getInstance().debug("OkGo")`, 加了以上代码就好了。
