### ISSUE TITLE
关于缓存的问题

### ISSUE THREAD

**Issue by KarlLargerFeld** [jeasonlzy/okhttp-OkGo#112]
你好，我在使用缓存的时候用了FIRST_CACHE_THEN_REQUEST模式， 并在OnSuccess，OnCacheSuccess回调中处理了返回数据，当本地有缓存并请求成功时，就会出现重复数据。
1.无缓存时,网络请求成功 onBefore -> onCacheError -> convertSuccess -> onSuccess -> onAfter
2.无缓存时,网络请求失败 onBefore -> onCacheError -> parseError -> onError -> onAfter
3.有缓存时,网络请求成功 onBefore -> onCacheSuccess -> convertSuccess -> onSuccess -> onAfter
4.有缓存时,网络请求失败 onBefore -> onCacheSuccess -> parseError -> onError -> onAfter
针对第三种情况，如何避免出现重复数据呢？

**Comment by jeasonlzy** [comment]
看 demo中代码。。强大的缓存处理。。有详细的处理方法。
