### ISSUE TITLE
User-Agent 的添加

### ISSUE THREAD

**Issue by moonljt521** [jeasonlzy/okhttp-OkGo#113]
关于 User-Agent，不自己设置的时候okgo会默认会添加一些user-agent参数，而当我动添加代码
HttpHeaders headers = new HttpHeaders();
        headers.put(HttpHeaders.HEAD_KEY_USER_AGENT, "aaaaa");
后只User-agent参数会留下 aaaaa ，而默认的都没有了，如何做到默认和我自己添加的参数都保留

**Comment by jeasonlzy** [comment]
不能都保留，header的键是唯一的。。需要的话自己值里面都写上。
