### ISSUE TITLE
provide method to get cache size

### ISSUE THREAD

**Issue by asker517** [jeasonlzy/okhttp-OkGo#114]
So powerful library 👍 

Could you provide a method to get cache size for user to count app cache size ? Thanks

**Comment by jeasonlzy** [comment]
缓存是使用数据库保存的，一般只会保存应用的文本数据，这个量是很小的，数据库不修改路径默认是在 data/data/包名/database 中，其实不属于app的缓存区，更像data区，所以结论就是，数据的大小要获取的话，可以直接根据db文件的路径获取 db 文件的length，但是这个大小不一定是缓存的大小，而且文件很小，也不需要清理。。

**Comment by jeasonlzy** [comment]
详细的可以看看源码中  Cache 包下的实现。主要是 CacheHelper 和 CacheManager

**Comment by asker517** [comment]
@jeasonlzy 嗯嗯 了解了 感谢 :-)
