### ISSUE TITLE
response.body.string()

### ISSUE THREAD

**Issue by deng7777777** [jeasonlzy/okhttp-OkGo#115]
Logger.e(response.body.string())或者Logger.json(response.body.string())最新版的okgo没办法打印response.body.string()
exe: ---java.io.IOException: Content-Length and stream length disagree

**Comment by jeasonlzy** [comment]
这个异常的原因是 你服务端返回的 content-length 和 真实的数据大小 不一致导致的。。具体问题还是出在服务端，建议检查服务端代码。

**Comment by chlonn** [comment]
浏览器有content-length,OKdownload不能处理Transfer-Encoding: chunked
