### ISSUE TITLE
开启debug与自定义的日志拦截器冲突

### ISSUE THREAD

**Issue by luvictor** [jeasonlzy/okhttp-OkGo#116]
自定义了一个日志拦截器
public class LoggingInterceptor implements Interceptor {
    @Override
    public Response intercept(Interceptor.Chain chain) throws IOException {
        Request request = chain.request();

        long t1 = System.nanoTime();
        Logger.e(String.format(Locale.getDefault(), "Request: %s%nRequestBody: %s", request.url(), request.body()));

        Response response = chain.proceed(request);

        long t2 = System.nanoTime();

        Logger.e(String.format(Locale.getDefault(), "Received response for %s in %.1fms%n%s",
                response.request().url(), (t2 - t1) / 1e6d, response.headers()));
        Logger.json(response.body().string());

        return response;
    }
}

会掉的时候打印response.body().string()提示java.lang.IllegalStateException: closed
![image](https://cloud.githubusercontent.com/assets/14093993/20759997/95a6bb96-b759-11e6-8411-9aa37b64db77.png)

**Comment by jeasonlzy** [comment]
你的拦截器代码有问题。。切记 response.body().string() 是个读流操作，在任何时候任何地方，只要读取一次，流就空了。详细的写法看 提供的 LoggingInterceptor 参考写法。。

**Comment by luvictor** [comment]
好的，谢谢大神。 学习了。
