### ISSUE TITLE
MemoryCookieStore空指针异常

### ISSUE THREAD

**Issue by pengbs** [jeasonlzy/okhttp-OkGo#117]
java.lang.NullPointerException
Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
异常日志如下：
`}
1 com.lzy.okgo.cookie.store.MemoryCookieStore.saveCookie(MemoryCookieStore.java:29)
2 com.lzy.okgo.cookie.CookieJarImpl.saveFromResponse(CookieJarImpl.java:33)
3 okhttp3.internal.http.HttpHeaders.receiveHeaders(HttpHeaders.java:187)
4 okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:95)
5 okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
6 okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
7 okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
8 okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
9 okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
10 okhttp3.RealCall.access$100(RealCall.java:33)
11 okhttp3.RealCall$AsyncCall.execute(RealCall.java:120)
12 okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
13 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
14 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
15 java.lang.Thread.run(Thread.java:818)`

**Comment by jeasonlzy** [comment]
这个问题看起来不容易发生，也不应该发生。。需要更多关于你请求的代码。

**Comment by jeasonlzy** [comment]
qq群已解决。使用版本太低，换1.7.2版本即可。

**Comment by pengbs** [comment]
什么版本换成1.7.2？

**Comment by jeasonlzy** [comment]
okgo  之前他用的1.6.7的版本。发生了这个异常。。换成1.7.2就解决了。

**Comment by pengbs** [comment]
我使用的是最新版，还是会偶现这个问题，不是必现

**Comment by jeasonlzy** [comment]
你加文档里面的群，详细的到群里说。。
