### ISSUE TITLE
为什么经常缓存不成功

### ISSUE THREAD

**Issue by fan91** [jeasonlzy/okhttp-OkGo#123]
bean已经序列化，缓存模式也设置了，但是有时候缓存不成功是怎么回事

**Comment by jeasonlzy** [comment]
看控制台有什么异常没。。

**Comment by qianyue0317** [comment]
我也是,,,控制台输出 "没有获取到缓存,或者缓存已经过期!"

**Comment by qiaoyhh** [comment]
我也遇到了，，post接口没有缓存成功

**Comment by jeasonlzy** [comment]
除了这个还有异常的，这个提示只是我catch住异常后，给的统一提示，而且就算有这个提示，也不代表不正常，比如使用以下两个模式的情况
<img width="620" alt="qq20170329-144212 2x" src="https://cloud.githubusercontent.com/assets/13421975/24441817/f559b412-148d-11e7-8cc4-9f6fd2a0f4fe.png">
图中圈的地方就是正常的逻辑，只要走了onCacheError，就会抛这个异常，然后继续后续的逻辑。

至于为什么缓存失败，
一部分和使用方法有关，比如没有序列化等，
一部分是设置了缓存过期时间，缓存过期了，
一部分是逻辑问题，比如第一次请求，使用先使用缓存的模式，这个时候连一次都没有请求成功过，何来缓存，所以必然先抛异常，然后走后续的逻辑，第二次才能有缓存。
