### ISSUE TITLE
传递参数自动改变

### ISSUE THREAD

**Issue by shun99** [jeasonlzy/okhttp-OkGo#124]
我用post在params传递一个参数，值是0hxJogq8Ko4VcMTTt4e3tSV4xoc/GSKl3T1z/vBmQdltLClvSPpoFq6fQxTRBBzWPPtpAFL16BKAb1fRfourfEc96KTR+L57Is57JJ/1Q89kZDS3hu/mKYfhgtm5IbqnttalPFay7CldRvAyR0ORj/V5F7CoXfskcNHwnt9Gww+MmBQIK6fEUg==
为什么上传过程会变成0hxJogq8Ko4VcMTTt4e3tSV4xoc%2FGSKl3T1z%2FvBmQdltLClvSPpoFq6fQxTRBBzWPPtpAFL16BKAb1fRfourfEc96KTR%2BL57Is57JJ%2F1Q89kZDS3hu%2FmKYfhgtm5IbqnttalPFay7CldRvAyR0ORj%2FV5F7CoXfskcNHwnt9Gww%2BMmBQIK6fEUg%3D%3D
这导致我没办法获取数据，很致命啊，不知道为什么

**Comment by ravenwang2012** [comment]
看上去被做了UrlEncode

**Comment by jeasonlzy** [comment]
对。就是会对参数进行url编码。后台需要按url解码一次就可以。
