### ISSUE TITLE
DownloadManager下载，在小米Max上被重定向，无法使用

### ISSUE THREAD

**Issue by ravenwang2012** [jeasonlzy/okhttp-OkGo#125]
型号：小米Max
系统版本：6.0.1    
Gradle配置：
       compile 'com.lzy.net:okgo:2.1.4'//可以单独使用，不需要依赖下方的扩展包
       compile 'com.lzy.net:okrx:0.1.2'//RxJava扩展支持，根据需要添加
       compile 'com.lzy.net:okserver:1.1.3'//下载管理和上传管理扩展，根据需要添加
现象：
      使用DownloadManager.addTask()进行下载，请求被重定向，使用OKGo的Demo测试也得到了同样的结果，但是使用FileCall方式去下载是没有问题的。

**Comment by jeasonlzy** [comment]
需要详细的接口地址我试试。
