### ISSUE TITLE
上传图片失败！message：此资源不支持请求实体的媒体类型“multipart/form-data”

### ISSUE THREAD

**Issue by ghost** [jeasonlzy/okhttp-OkGo#132]
1/后台写的post上传图片接口，parame写在URI Parameters没有写在Body Parameters这符合规范嘛？
2/okgo默认为表单上传？
ps：parame写在uri parameters中，使用okgo或者okhttp均报404-----改为bod parameters，上传提示'此资源不支持请求实体的媒体类型“multipart/form-data”'
求解，谢谢！

**Comment by ping999** [comment]
使用xutils3及可成功
源码：
`RequestParams requestParams = new RequestParams(LiveNetStatic.URL+ LiveNetStatic.UPLOAD_USER_HEAD_PIC);
        requestParams.addQueryStringParameter("UserID", SPUtils.getString(context(), LiveNetStatic.USER_ID, null));
        requestParams.addQueryStringParameter("TokenCode", SPUtils.getString(context(), LiveNetStatic.TOKEN, null));
        requestParams.addBodyParameter("file",file);
        requestParams.setMultipart(true);
        x.http().post(requestParams, new org.xutils.common.Callback.CommonCallback<String>() {}`

**Comment by jeasonlzy** [comment]
使用post的时候，所有 params 参数通过请求体添加，框架并不会把参数再往 url 后拼一份，如果想 请求体，和 url 后面都带上自己的参数，那么传入的 url 需要自己拼接好参数，同时，params里面只要有文件，就默认使用 multipart/form-data 上传，如果不支持这个类型，那说明你的上传方式与你服务器需要的不一致，建议先搞清楚服务器需要什么类型。

**Comment by ping999** [comment]
后台兼顾了ios，post请求使用uri parameters，okgo的post请求中使用headers("key","value")貌似失效？
**使用拼接方式，file传入params就可以使用okgo了**
感谢！

**Comment by jeasonlzy** [comment]
不知道你说的 uri params 是什么，看看接口文档的传参方式，任何形式都可以传，只是你的方法不对。

**Comment by MelvinCen** [comment]
OkGo.post(url)
                .tag(context)
                .isMultipart(true)
                .params("file1",file)
                .execute(callback);
这样子上传打印出来content-type  是application/json; charset=utf-8
isMultipart(true)也设置了，文件也放了
