### ISSUE TITLE
Download频繁结束，开始同一个任务

### ISSUE THREAD

**Issue by jy03773322** [jeasonlzy/okhttp-OkGo#133]
你好，
我遇到了在频繁结束和开始同一个file的下载时会造成下载文件错误的问题。
我看到DownloadTask中Stop()方法调用的mFuture.cancel(mayInterruptIfRunning);，参数传入的是flase，是不是代表，其实工作线程并没有停止下载，造成了频繁开关下载，多个线程同时操作了同一个问题文件。

**Comment by jeasonlzy** [comment]
当一个线程运行起来的时候，是没有方法让这个线程直接结束的，包括DownloadTask 也是一样，是无法让一个下载中的线程立即结束的，需要做的就是用标记位控制线程的流程，让他尽早结束而已。至于那个参数，true 还是 false ，对代码基本没有影响，一个运行的线程，传true也是停止不了的，你可以试试。详细关于线程如何停止，你多看看资料应该就有答案了。。

**Comment by jy03773322** [comment]
好的多谢，是我没有注意到download循环中的“!isCancelled()”判断。
还有一个问题是，现在是用DB保存File下载状态，如果手动把下载到一半或已经下载完成的File删掉。那么下次再次下载同文件，是在哪里做File完整性校验的

**Comment by jeasonlzy** [comment]
我看了下代码。。这种情况应该是没有做文件校验，下次更新我加上。。

**Comment by jeasonlzy** [comment]
关于你的第一个问题，频繁结束和开始同一个file的下载时会造成下载文件错误的问题。我又仔细的看了下代码，确实是因为多线程同时操作同一个文件导致的，可能还没有真正停止，然后又开始下载了，导致写入出错，这个我在okgo3.0版本做了校验，虽然偶尔还是会报下载出错，但是不影响下载文件的完整性，应该影响不大。。

**Comment by jeasonlzy** [comment]
目前这个问题我应该不会修复，没有特别好的解决办法，不过一点不影响使用，所有功能都是正常的，原因有以下几点
1. 很少有用户把一个任务来回的点击暂停和继续，只有测试这么干
2. 就算点击出错了，只需要继续点击继续，文件依然正常下载
3. 要修改这个问题，会增加更多的线程控制代码，闲的比较多余

所以，鉴于以上几点，在不影响正常的功能前提下，暂时不做修复，后期再计划吧。
