### ISSUE TITLE
设置了信任所有的证书，还是经常报SSL的问题

### ISSUE THREAD

**Issue by dazhao2016** [jeasonlzy/okhttp-OkGo#135]

**Comment by jeasonlzy** [comment]
异常和代码贴一下，偶发还是必现。

**Comment by dazhao2016** [comment]
经常，有时候一两次，有时候一下载就报。我在网上找了一段设置信任任何证书的okhttp代码来封装，就基本没有这个问题，但还是会报timeout。如果使用的是okgo就很少发现timeout的问题，最常见的是ssl
12-28 22:07:24.253 21662-21662/com.zibo.projectbay W/System.err: javax.net.ssl.SSLException: Connection closed by peer
12-28 22:07:24.268 21662-21662/com.zibo.projectbay W/System.err:     at org.apache.harmony.xnet.provider.jsse.NativeCrypto.SSL_do_handshake(Native Method)
12-28 22:07:24.268 21662-21662/com.zibo.projectbay W/System.err:     at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:378)
12-28 22:07:24.268 21662-21662/com.zibo.projectbay W/System.err:     at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:241)
12-28 22:07:24.268 21662-21662/com.zibo.projectbay W/System.err:     at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:198)
12-28 22:07:24.268 21662-21662/com.zibo.projectbay W/System.err:     at okhttp3.internal.connection.RealConnection.buildConnection(RealConnection.java:174)
12-28 22:07:24.268 21662-21662/com.zibo.projectbay W/System.err:     at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:114)
12-28 22:07:24.276 21662-21662/com.zibo.projectbay W/System.err:     at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:193)
12-28 22:07:24.276 21662-21662/com.zibo.projectbay W/System.err:     at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:129)
12-28 22:07:24.276 21662-21662/com.zibo.projectbay W/System.err:     at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:98)
12-28 22:07:24.276 21662-21662/com.zibo.projectbay W/System.err:     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
12-28 22:07:24.276 21662-21662/com.zibo.projectbay W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
12-28 22:07:24.276 21662-21662/com.zibo.projectbay W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
12-28 22:07:24.276 21662-21662/com.zibo.projectbay W/System.err:     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109)
12-28 22:07:24.276 21662-21662/com.zibo.projectbay W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
12-28 22:07:24.276 21662-21662/com.zibo.projectbay W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
12-28 22:07:24.276 21662-21662/com.zibo.projectbay W/System.err:     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
12-28 22:07:24.276 21662-21662/com.zibo.projectbay W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
12-28 22:07:24.284 21662-21662/com.zibo.projectbay W/System.err:     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
12-28 22:07:24.284 21662-21662/com.zibo.projectbay W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
12-28 22:07:24.284 21662-21662/com.zibo.projectbay W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
12-28 22:07:24.284 21662-21662/com.zibo.projectbay W/System.err:     at com.lzy.okhttputils.interceptor.LoggerInterceptor.intercept(LoggerInterceptor.java:40)
12-28 22:07:24.284 21662-21662/com.zibo.projectbay W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
12-28 22:07:24.284 21662-21662/com.zibo.projectbay W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
12-28 22:07:24.284 21662-21662/com.zibo.projectbay W/System.err:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
12-28 22:07:24.284 21662-21662/com.zibo.projectbay W/System.err:     at okhttp3.RealCall.access$100(RealCall.java:33)
12-28 22:07:24.284 21662-21662/com.zibo.projectbay W/System.err:     at okhttp3.RealCall$AsyncCall.execute(RealCall.java:120)
12-28 22:07:24.284 21662-21662/com.zibo.projectbay W/System.err:     at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
12-28 22:07:24.284 21662-21662/com.zibo.projectbay W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
12-28 22:07:24.284 21662-21662/com.zibo.projectbay W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
12-28 22:07:24.284 21662-21662/com.zibo.projectbay W/System.err:     at java.lang.Thread.run(Thread.java:856)

**Comment by dazhao2016** [comment]
这个是我现在使用的代码：
 private void initOkhttpUtils() {
        HttpHeaders headers = new HttpHeaders();
        HttpParams params = new HttpParams();

        //必须调用初始化
        OkHttpUtils.init(this);

        //以下设置的所有参数是全局参数,同样的参数可以在请求的时候再设置一遍,那么对于该请求来讲,请求中的参数会覆盖全局参数
        //好处是全局参数统一,特定请求可以特别定制参数
        try {
            //以下都不是必须的，根据需要自行选择,一般来说只需要 debug,缓存相关,cookie相关的 就可以了
            OkHttpUtils.getInstance()
                    //打开该调试开关,控制台会使用 红色error 级别打印log,并不是错误,是为了显眼,不需要就不要加入该行
                    .debug("OkHttpUtils")

                    //如果使用默认的 5分钟,以下三行也不需要传
                    .setConnectTimeout(300000)  //全局的连接超时时间
                    .setReadTimeOut(300000)     //全局的读取超时时间
                    .setWriteTimeOut(300000)    //全局的写入超时时间
                    .setCacheMode(CacheMode.DEFAULT)
                    .setCacheTime(CacheEntity.CACHE_NEVER_EXPIRE)
                    .setCookieStore(new PersistentCookieStore())          //cookie持久化存储，如果cookie不过期，则一直有效
                    .setCertificates();                                 //方法一：信任所有证书
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

**Comment by jeasonlzy** [comment]
建议升级到 okgo，新版本对 https 的封装有比较大改动。
