### ISSUE TITLE
多任务同时下载过程经常发生文件读写异常...

### ISSUE THREAD

**Issue by yuruiyin** [jeasonlzy/okhttp-OkGo#139]
特别是多个任务同时下载的时候，就经常发生个别下载任务发生文件读写异常或网络异常。。

**Comment by stubhbw** [comment]
Hello,jeasonlzy

    下载文件会报错,同一个url,成功或失败的情况都有,报下面的错误,上stackoverflow查看,大多说content-length超出实际文件大小,但是用浏览器登录下载连接,查看请求,与文件大小一致

01-20 21:03:50.145 3193-3193/? W/System.err: java.net.ProtocolException: unexpected end of stream
01-20 21:03:50.145 3193-3193/? W/System.err:     at okhttp3.internal.http.Http1xStream$FixedLengthSource.read(Http1xStream.java:380)
01-20 21:03:50.145 3193-3193/? W/System.err:     at okio.RealBufferedSource$1.read(RealBufferedSource.java:409)
01-20 21:03:50.145 3193-3193/? W/System.err:     at java.io.InputStream.read(InputStream.java:162)
01-20 21:03:50.145 3193-3193/? W/System.err:     at com.lzy.okgo.convert.FileConvert.convertSuccess(FileConvert.java:74)
01-20 21:03:50.145 3193-3193/? W/System.err:     at com.lzy.okgo.callback.FileCallback.convertSuccess(FileCallback.java:37)
01-20 21:03:50.145 3193-3193/? W/System.err:     at com.lzy.okgo.callback.FileCallback.convertSuccess(FileCallback.java:18)
01-20 21:03:50.145 3193-3193/? W/System.err:     at com.lzy.okgo.adapter.CacheCall.parseResponse(CacheCall.java:269)
01-20 21:03:50.145 3193-3193/? W/System.err:     at com.lzy.okgo.adapter.CacheCall.access$600(CacheCall.java:34)
01-20 21:03:50.145 3193-3193/? W/System.err:     at com.lzy.okgo.adapter.CacheCall$1.onResponse(CacheCall.java:160)
01-20 21:03:50.145 3193-3193/? W/System.err:     at okhttp3.RealCall$AsyncCall.execute(RealCall.java:126)
01-20 21:03:50.145 3193-3193/? W/System.err:     at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
01-20 21:03:50.145 3193-3193/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
01-20 21:03:50.145 3193-3193/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
01-20 21:03:50.145 3193-3193/? W/System.err:     at java.lang.Thread.run(Thread.java:841)


    下面是下载代码:
OkGo.post(adFile_Url)
                .tag(mContext)
                .execute(new FileCallback(Environment.getExternalStorageDirectory().getAbsolutePath() + "/MyDownLoad/", adFile.getName()) {
                    @Override
                    public void onSuccess(File file, Call call, Response response) {

                    }

                    @Override
                    public void onError(Call call, Response response, Exception e) {
                        super.onError(call, response, e);

                    }
                });

请教......

**Comment by stubhbw** [comment]
Hello,jeasonlzy

    下载文件会报错,同一个url,成功或失败的情况都有,报下面的错误,上stackoverflow查看,大多说content-length超出实际文件大小,但是用浏览器登录下载连接,查看请求,与文件大小一致

01-20 21:03:50.145 3193-3193/? W/System.err: java.net.ProtocolException: unexpected end of stream
01-20 21:03:50.145 3193-3193/? W/System.err:     at okhttp3.internal.http.Http1xStream$FixedLengthSource.read(Http1xStream.java:380)
01-20 21:03:50.145 3193-3193/? W/System.err:     at okio.RealBufferedSource$1.read(RealBufferedSource.java:409)
01-20 21:03:50.145 3193-3193/? W/System.err:     at java.io.InputStream.read(InputStream.java:162)
01-20 21:03:50.145 3193-3193/? W/System.err:     at com.lzy.okgo.convert.FileConvert.convertSuccess(FileConvert.java:74)
01-20 21:03:50.145 3193-3193/? W/System.err:     at com.lzy.okgo.callback.FileCallback.convertSuccess(FileCallback.java:37)
01-20 21:03:50.145 3193-3193/? W/System.err:     at com.lzy.okgo.callback.FileCallback.convertSuccess(FileCallback.java:18)
01-20 21:03:50.145 3193-3193/? W/System.err:     at com.lzy.okgo.adapter.CacheCall.parseResponse(CacheCall.java:269)
01-20 21:03:50.145 3193-3193/? W/System.err:     at com.lzy.okgo.adapter.CacheCall.access$600(CacheCall.java:34)
01-20 21:03:50.145 3193-3193/? W/System.err:     at com.lzy.okgo.adapter.CacheCall$1.onResponse(CacheCall.java:160)
01-20 21:03:50.145 3193-3193/? W/System.err:     at okhttp3.RealCall$AsyncCall.execute(RealCall.java:126)
01-20 21:03:50.145 3193-3193/? W/System.err:     at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
01-20 21:03:50.145 3193-3193/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
01-20 21:03:50.145 3193-3193/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
01-20 21:03:50.145 3193-3193/? W/System.err:     at java.lang.Thread.run(Thread.java:841)


    下面是下载代码:
OkGo.post(adFile_Url)
                .tag(mContext)
                .execute(new FileCallback(Environment.getExternalStorageDirectory().getAbsolutePath() + "/MyDownLoad/", adFile.getName()) {
                    @Override
                    public void onSuccess(File file, Call call, Response response) {

                    }

                    @Override
                    public void onError(Call call, Response response, Exception e) {
                        super.onError(call, response, e);

                    }
                });

请教......

**Comment by stubhbw** [comment]
Hello,jeasonlzy

    下载文件会报错,同一个url,成功或失败的情况都有,报下面的错误,上stackoverflow查看,大多说content-length超出实际文件大小,但是用浏览器登录下载连接,查看请求,与文件大小一致

01-20 21:03:50.145 3193-3193/? W/System.err: java.net.ProtocolException: unexpected end of stream
01-20 21:03:50.145 3193-3193/? W/System.err:     at okhttp3.internal.http.Http1xStream$FixedLengthSource.read(Http1xStream.java:380)
01-20 21:03:50.145 3193-3193/? W/System.err:     at okio.RealBufferedSource$1.read(RealBufferedSource.java:409)
01-20 21:03:50.145 3193-3193/? W/System.err:     at java.io.InputStream.read(InputStream.java:162)
01-20 21:03:50.145 3193-3193/? W/System.err:     at com.lzy.okgo.convert.FileConvert.convertSuccess(FileConvert.java:74)
01-20 21:03:50.145 3193-3193/? W/System.err:     at com.lzy.okgo.callback.FileCallback.convertSuccess(FileCallback.java:37)
01-20 21:03:50.145 3193-3193/? W/System.err:     at com.lzy.okgo.callback.FileCallback.convertSuccess(FileCallback.java:18)
01-20 21:03:50.145 3193-3193/? W/System.err:     at com.lzy.okgo.adapter.CacheCall.parseResponse(CacheCall.java:269)
01-20 21:03:50.145 3193-3193/? W/System.err:     at com.lzy.okgo.adapter.CacheCall.access$600(CacheCall.java:34)
01-20 21:03:50.145 3193-3193/? W/System.err:     at com.lzy.okgo.adapter.CacheCall$1.onResponse(CacheCall.java:160)
01-20 21:03:50.145 3193-3193/? W/System.err:     at okhttp3.RealCall$AsyncCall.execute(RealCall.java:126)
01-20 21:03:50.145 3193-3193/? W/System.err:     at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
01-20 21:03:50.145 3193-3193/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
01-20 21:03:50.145 3193-3193/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
01-20 21:03:50.145 3193-3193/? W/System.err:     at java.lang.Thread.run(Thread.java:841)


    下面是下载代码:
      OkGo.post(adFile_Url)
                    .tag(mContext)
                    .execute(new FileCallback(Environment.getExternalStorageDirectory().getAbsolutePath() +              "/MyDownLoad/", adFile.getName()) {
                    @Override
                    public void onSuccess(File file, Call call, Response response) {

                    }

                    @Override
                    public void onError(Call call, Response response, Exception e) {
                        super.onError(call, response, e);

                    }
                });

请教......

**Comment by stubhbw** [comment]
.get也会出现
ProtocolException: unexpected end of stream这个异常
DownLoadManager如果下载的文件较多也会出现该异常,出现几率较单任务下载要低(文件包括图片视频)

**Comment by jeasonlzy** [comment]
下载文件的 url 地址有吗  我测试下。。

**Comment by jeasonlzy** [comment]
okgo升级3.0，okserver进行了重构，欢迎下载体验。。

**Comment by zhp075366** [comment]
07-31 16:00:05.863 6845-6845/com.example.test E/gotech: [ (DownloadingTaskAdapter.java:177)#onError ] 蘑菇街->Progress{fraction=0.9825276, totalSize=30951077, currentSize=30471724, speed=0, status=4, priority=0, folder=/storage/emulated/0/com.example.test/Download, filePath=/storage/emulated/0/com.example.test/Download/com.mogujie_save.apk, fileName=com.mogujie_save.apk, tag=http://121.29.10.1/f5.market.xiaomi.com/download/AppStore/07a6ee4955e364c3f013b14055c37b8e4f6668161/com.mogujie.apk, url=http://121.29.10.1/f5.market.xiaomi.com/download/AppStore/07a6ee4955e364c3f013b14055c37b8e4f6668161/com.mogujie.apk}
07-31 16:00:05.863 6845-6845/com.example.test W/System.err: java.net.ProtocolException: unexpected end of stream
07-31 16:00:05.864 6845-6845/com.example.test W/System.err:     at okhttp3.internal.http1.Http1Codec$FixedLengthSource.read(Http1Codec.java:387)
07-31 16:00:05.864 6845-6845/com.example.test W/System.err:     at okio.RealBufferedSource$1.read(RealBufferedSource.java:430)
07-31 16:00:05.864 6845-6845/com.example.test W/System.err:     at java.io.BufferedInputStream.read(BufferedInputStream.java:290)
07-31 16:00:05.864 6845-6845/com.example.test W/System.err:     at com.lzy.okserver.download.DownloadTask.download(DownloadTask.java:338)
07-31 16:00:05.864 6845-6845/com.example.test W/System.err:     at com.lzy.okserver.download.DownloadTask.run(DownloadTask.java:309)
07-31 16:00:05.864 6845-6845/com.example.test W/System.err:     at com.lzy.okserver.task.PriorityRunnable.run(PriorityRunnable.java:35)
07-31 16:00:05.864 6845-6845/com.example.test W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
07-31 16:00:05.864 6845-6845/com.example.test W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
07-31 16:00:05.864 6845-6845/com.example.test W/System.err:     at java.lang.Thread.run(Thread.java:818)
07-31 16:00:05.864 6845-6845/com.example.test E/gotech: [ (DownloadingTaskAdapter.java:180)#onError ] Exception message: unexpected end of stream

**Comment by zhp075366** [comment]
最新的版本还是有java.net.ProtocolException: unexpected end of stream
DownLoadManager如果下载的文件较多出现的概率比较大

**Comment by MickeyDaddy** [comment]
@jeasonlzy 我在 单任务下载时，也会偶现这个问题，用的是 compile 'com.lzy.net:okgo:3.0.4' 最新版本的，请问这个 有办法解决吗
