### ISSUE TITLE
初次接触okhttp-OkGo报错，求指教

### ISSUE THREAD

**Issue by wzej** [jeasonlzy/okhttp-OkGo#144]
请教一个问题
运行okhttp-OkGo项目案例，报错
Error:(74, 13) Failed to resolve: com.github.CymChad:BaseRecyclerViewAdapterHelper:v2.0.7
<a href="openFile:D:/Android app/Hdgaxxfb/okhttp-OkGo-sample/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

提示错误行
    compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:v2.0.7'
求教如何解决，谢谢！

**Comment by jeasonlzy** [comment]
根目录 build.gradle 修改如下
allprojects {
    repositories {
        jcenter()
        maven { url "https://jitpack.io" }
    }
}
