### ISSUE TITLE
感谢作者

### ISSUE THREAD

**Issue by JustinChiang123** [jeasonlzy/okhttp-OkGo#145]
偶然发现作者的东西，两个地方非常舒服。
  1、日常callback返回值直接进UI线程这个点。
  2、返回值共同解析那个点，非常实用。
项目上的东西，虽然也是改吧改吧有这个效果，但是都没有心思像作者一样抽成bankproject。
非常感谢作者，加油！
非常佩服作者的高规范注释。

**Comment by jeasonlzy** [comment]
感谢。共勉。。
