### ISSUE TITLE
用HashMap或者params请求体传参的时候如何设置请求数据的编码

### ISSUE THREAD

**Issue by allnan** [jeasonlzy/okhttp-OkGo#147]
项目里最近用的短信接口有变动，需要用`GBK`编码来传参。OkGO中的post自带一层urlEncode UTF-8的编码，这导致用GBK编码以后又会套一层urlEncode，第三方后台解析不了。

在示例中我只找到upString的方法里可以改变传参的格式，但是只能传长文本，项目里大多用的是HashMap和添加params请求体，请问这种请求参数的编码需要怎么设置呢。

**Comment by jeasonlzy** [comment]
okgo底层使用 okhttp 的api构建请求体，okhttp默认使用utf-8编码，没有暴露修改编码的api，所以使用params构建请求体的时候，okgo也无法修改请求编码。

**Comment by allnan** [comment]
好的，谢谢。
暂用volley吧，有个改变编码的方法，比较方便，不会出现两个请求头。
```
@Override
            protected String getParamsEncoding() {
                return "gb2312";
            }
```
