### ISSUE TITLE
如何上传不需要键值对的文件？

### ISSUE THREAD

**Issue by zZiv** [jeasonlzy/okhttp-OkGo#148]
如题，就上传个图片，后台需要传请求头和一个文件，文件不用传它的KEY。这样怎么搞？
就如鸿洋的： 
OkHttpUtils
    .postFile()
    .url(url)
    .file(file)
    .build()
    .execute(new MyStringCallback());

**Comment by jeasonlzy** [comment]
可以传递 requestbody，你这个需求后续我加个方法，可能更方便点。

**Comment by zZiv** [comment]
获取okhttp实例？然后传递requestbody吗？能否举例？先谢谢作者

**Comment by jeasonlzy** [comment]
okgo升级3.0 原生支持upFile() 方法直接传文件。。
