### ISSUE TITLE
错误信息的处理

### ISSUE THREAD

**Issue by Liuyaowu** [jeasonlzy/okhttp-OkGo#149]
网络请求无非是成功或是失败，请求成功不废话，失败的话情况会有很多种，一：如服务器接收到了请求返回的数据中出现了诸如“密码错误”等等的失败信息，这种您是在解析Json数据的时候通过抛出异常处理。二：对于其他情况如：连接超时、服务器异常诸如这类的情况我希望给用户一个友好的提示我应该怎么处理呢？？最好的情况是直接在onError中就根据e.getMessage将信息提示，但是对于连接超时get到的消息是
"error：connect timeout exception"这样的，是不是还需要针对第二种情况进行判断呢？

**Comment by jeasonlzy** [comment]
第二种也是在onError中，但是不是判断 getMessage ，而是使用 e instantof SocketTimeOutException 等等这样的形式判断异常的类型，一般来书 url 错误，无网络，连接超时等等，这些异常类型都是不一样的。
