### ISSUE TITLE
下载doc、excel文件能功能，但下载后文件损坏。

### ISSUE THREAD

**Issue by AnlieMelody** [jeasonlzy/okhttp-OkGo#150]
<-- 206 Partial Content http://ojk4en1lx.bkt.clouddn.com/84b58aa434e64f0f8ea679c8a68565d4.docx?e=1799477270&token=zqieMj9uwET4pKmQ0XXnHT-6NB4PwAM9F8qfAPyH:CMtkNaWx1wyMjfx05jY2DmSE-ks= (221ms）
01-11 14:48:38.314 26701-27791/com.banmen.joifox I/OkGo: 	Date: Wed, 11 Jan 2017 06:48:37 GMT
01-11 14:48:38.314 26701-27791/com.banmen.joifox I/OkGo: 	Content-Type: application/vnd.openxmlformats-officedocument.wordprocessingml.document
01-11 14:48:38.314 26701-27791/com.banmen.joifox I/OkGo: 	Content-Length: 15108
01-11 14:48:38.314 26701-27791/com.banmen.joifox I/OkGo: 	Connection: keep-alive
01-11 14:48:38.314 26701-27791/com.banmen.joifox I/OkGo: 	Server: openresty
01-11 14:48:38.314 26701-27791/com.banmen.joifox I/OkGo: 	Accept-Ranges: bytes
01-11 14:48:38.314 26701-27791/com.banmen.joifox I/OkGo: 	Access-Control-Allow-Origin: *
01-11 14:48:38.314 26701-27791/com.banmen.joifox I/OkGo: 	Access-Control-Expose-Headers: X-Log, X-Reqid
01-11 14:48:38.314 26701-27791/com.banmen.joifox I/OkGo: 	Access-Control-Max-Age: 2592000
01-11 14:48:38.314 26701-27791/com.banmen.joifox I/OkGo: 	Cache-Control: public, max-age=31536000
01-11 14:48:38.314 26701-27791/com.banmen.joifox I/OkGo: 	Content-Disposition: inline; filename="84b58aa434e64f0f8ea679c8a68565d4.docx"
01-11 14:48:38.314 26701-27791/com.banmen.joifox I/OkGo: 	Content-Transfer-Encoding: binary
01-11 14:48:38.314 26701-27791/com.banmen.joifox I/OkGo: 	ETag: "FvoaVgrLknTQ23XS366yiEwIfK8n"
01-11 14:48:38.314 26701-27791/com.banmen.joifox I/OkGo: 	Last-Modified: Tue, 10 Jan 2017 12:43:02 GMT
01-11 14:48:38.314 26701-27791/com.banmen.joifox I/OkGo: 	X-Log: mc.g/404;mc.g;RS;mc.s;IO:2
01-11 14:48:38.314 26701-27791/com.banmen.joifox I/OkGo: 	X-M-Log: QNM:xs478;SRCPROXY:xs482;SRCPROXY:35;QNM2:148
01-11 14:48:38.314 26701-27791/com.banmen.joifox I/OkGo: 	X-M-Reqid: f1cAAC26xGvWpJgU
01-11 14:48:38.314 26701-27791/com.banmen.joifox I/OkGo: 	X-Private: 1
01-11 14:48:38.314 26701-27791/com.banmen.joifox I/OkGo: 	X-Qiniu-Zone: 1
01-11 14:48:38.314 26701-27791/com.banmen.joifox I/OkGo: 	X-Qnm-Cache: Miss,Proxy,Cache
01-11 14:48:38.314 26701-27791/com.banmen.joifox I/OkGo: 	X-Reqid: f1cAAC26xGvWpJgU
01-11 14:48:38.314 26701-27791/com.banmen.joifox I/OkGo: 	Content-Range: bytes 0-15107/15108
01-11 14:48:38.314 26701-27791/com.banmen.joifox I/OkGo: 	X-Ser: BC5_yd-jiangsu-wuxi-2-cache-1, BC136_yd-jiangsu-nanjing-1-cache-3
01-11 14:48:38.314 26701-27791/com.banmen.joifox I/OkGo: 	X-Cache: MISS from BC136_yd-jiangsu-nanjing-1-cache-3(baishan)
01-11 14:48:38.314 26701-27791/com.banmen.joifox I/OkGo:  
01-11 14:48:38.324 26701-27791/com.banmen.joifox I/OkGo: 	body:PK����������!��ok�~����(������[Content_Types].xml �(����������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������j�0��ѵ�Jz(��Ρ?�6��i��ڒ�6oߵ�R�&�b0f����N�U��mM��ɈE`�U�,2�5{�YP%Jk c;l��ޤ���Ѵ	["�'΃\B%Bb�RX_	�W��N�o���~?=pi��k��2ൂh*<���t��z�k�X���E��Z:c¹RK�d����#ۢ�������缕�V�I����<O_����-y����Sm�Lh�q�څ���Zg'����\�NG��6�'}ܕC�=�<5PI�>��[8��B]>*��:�k����:=�	-�o��"�{��s|u�dAw�L�K�Z���ТϚ���s����t��_��ƪ����7�|���������PK����������!�����������N������_rels/.rels �(����������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������JA���a�}7�
                                                         "���H�w"����w̤ھ�� �P�^����O֛���;�<�aYՠ؛`G�kxm��PY�[��gGΰino�/<���<�1��ⳆA$>"f3��\�ȾT��I	S�������W����Yig�@��X6_�]7~
                                                         f��ˉ�ao�.b*lI�r�j)�,l0�%��b�
                                                         6�i���D�_���,	�	���|u�Z^t٢yǯ;!Y,}{�C��/h>��������PK����������!����Q~�����������word/_rels/document.xml.rels �(��������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������n�@��M�d�eAŊ^�&zi�V`+�����1b���&{�d�0��a���U�lAi.EL|�#�D�\�1Y.^F���D�J) &�d6����A�м�
01-11 14:48:38.324 26701-27791/com.banmen.joifox I/OkGo: <-- END HTTP

**Comment by AnlieMelody** [comment]
额，没人应答吗？很严重的问题。doc、excel等文件下载不行

**Comment by wankey** [comment]
遇到了类似的问题，下载下来的文件大小与实际不符，导致无法正确打开

**Comment by ouyangwenfeng** [comment]
我也遇到这个问题，下载下来的文件大小与实际不符，导致无法正确打开

**Comment by ouyangwenfeng** [comment]
感觉是okhttp3 对 Content-Type: application/vnd.openxmlformats-officedocument.wordprocessingml.document 的处理太好了，默认搞成了utf-8
编码。。

**Comment by jeasonlzy** [comment]
可以尝试把  debug 关掉试试。

**Comment by budingts** [comment]
word打开乱码

**Comment by jeasonlzy** [comment]
可以尝试把 debug 关掉试试。
