### ISSUE TITLE
网络链接断开时，抛出UnknownHostException异常如何捕获呢？

### ISSUE THREAD

**Issue by loganguo** [jeasonlzy/okhttp-OkGo#151]
需要捕获并且转换成自定义的异常类中的一个预定义常量值

**Comment by Liuyaowu** [comment]
e  instanceof  UnknownHostException判断一下不就可以了么？判断常见的几种如：网络异常、连接超时等等，其它的一般可以默认为服务器异常就行了吧，因为很多错误信息你可能不需要给用户展示，只需要给用户能懂得几个提示就行了，仅供操参考

**Comment by jeasonlzy** [comment]
@Liuyaowu 正解。标准答案。。

**Comment by loganguo** [comment]
> e instanceof UnknownHostException判断一下不就可以了么
可以的。

在JsonConvert中，我可以根据code来判断并抛出对应的预定义异常，这样上层统一处理我这个预定义错误类即可。但是对于UnknownHostException这样的错误，显然在JsonConvert中是处理不到的，那我的问题是有没有类似于JsonConvert这样的类呢？我想简化上层的处理逻辑，尽量不去处理` e instanceof UnknownHostException`这样的逻辑。有没有好办法呢？

**Comment by Liuyaowu** [comment]
@Override
    public void onError(Call call, Response response, Exception e) {
        if (null != response){
            int code = response.code();
            switch (code){
                case 404:
                    onErrorHandled("找不到服务器地址");
                    break;
                case 408:
                    onErrorHandled("请求链接超时");
                    break;
                default:
                    onErrorHandled("服务器异常");
                    break;
            }
        } else {//网络无法连接，无返回的Response
            if (isReturnNoNetSign) {
                onNetErrorListener();
            } else {
                onErrorHandled("网络连接不可用，请稍后重试");
            }
        }
    }

    /**
     * 错误消息处理，只有错误消息提示
     *
     * @param errorMsg
     */
    protected void onErrorHandled(String errorMsg) {

    }

    /**
     * 专门针对网络不可使用提供的方法
     */
    protected void onNetErrorListener() {

    }
