### ISSUE TITLE
请问tag传入context是否会泄漏呢？

### ISSUE THREAD

**Issue by pye52** [jeasonlzy/okhttp-OkGo#152]
用context作为tag统一管理某个fragment的请求
在onstop的时候cancel掉，请问会造成泄漏么？

**Comment by jeasonlzy** [comment]
传入什么无所谓，重点是在activity销毁的时候 请求有没有完成或者被取消，如果没有取消，无论你用什么网络框架，无论是否传入什么tag， 必然泄露
