### ISSUE TITLE
DownloadService没有意义？

### ISSUE THREAD

**Issue by baby2431** [jeasonlzy/okhttp-OkGo#154]
您好，非常开心能够使用到您这个项目。但是看了相关源码，我存在一个疑问，就是DownloadService的oncreate并没有复写，且仅仅是两个与Service生命周期不相关的两个方法。并不是Android定义的后台任务的，Thread等应该是跟Application的生命周期相同。才疏学浅，请问DownloadService是否有意义?

**Comment by jeasonlzy** [comment]
downloadservice的意义在于他作为一个服务，优先级较高，不容易被回收，他需要做的就是持有downloadmanager 就够了，只要service在，成员变量就在，下载局可以继续。就这样。

**Comment by tianma8023** [comment]
@jeasonlzy  OKay-Server中没有提供关闭DownloadService的方法，如果项目虽有下载模块，但下载功能并不是主要的模块，而一旦进行下载操作之后DownloadService就一直在后台开着，这样也不好吧。
