### ISSUE TITLE
文件下载时,回调totalSize=-1

### ISSUE THREAD

**Issue by zabio** [jeasonlzy/okhttp-OkGo#157]
--[Debug]--: currentSize:	3981549	totalSize:	-1	progress:	-3981549.0
--[Debug]--: currentSize:	4213381	totalSize:	-1	progress:	-4213381.0
--[Debug]--: currentSize:	5266437	totalSize:	-1	progress:	-5266437.0
--[Debug]--: currentSize:	5312669	totalSize:	-1	progress:	-5312669.0

**Comment by jeasonlzy** [comment]
服务端没有返回content-length头。

**Comment by LinkGitcode** [comment]
怎么关闭了。。。content-length=-1怎么解决

**Comment by chlonn** [comment]
浏览器有content-length,OKdownload不能处理Transfer-Encoding: chunked
