### ISSUE TITLE
OkGo怎么开启 gzip压缩，返回数据时候如何解析

### ISSUE THREAD

**Issue by moonljt521** [jeasonlzy/okhttp-OkGo#158]
OkGo怎么开启 gzip压缩，返回数据时候如何解析

**Comment by jeasonlzy** [comment]
默认已开启。不需要关系。。数据解析看文档和demo

**Comment by moonljt521** [comment]
ok （我意思只是问开启了gizp后返回的数据如何解压~~）

**Comment by ZhenMrLee** [comment]
这个默认开启得   不用处理嘛

**Comment by ZhenMrLee** [comment]
.headers("Accept-Encoding", "gzip,deflate") 后台让加上这个，出来得json就是乱码了
