### ISSUE TITLE
OkGo的双向验证第一次请求速度慢

### ISSUE THREAD

**Issue by chenzixue** [jeasonlzy/okhttp-OkGo#160]
第一次请求的时候速度慢，感觉OkHttpUtils还快一些

**Comment by jeasonlzy** [comment]
这个不分第一次还是第几次，走的代码都是一样的。

**Comment by chenzixue** [comment]
再经过测试后，app每次启动后，OkGo第一轮（8次）请求速度慢。
而OkHttpUtils请求速度一直都很快。
![1](https://cloud.githubusercontent.com/assets/13416741/22576741/500d64c8-e9f8-11e6-917f-032017c2df91.png)
这是启动应用后的第一轮（8次）请求中的一个请求
![2](https://cloud.githubusercontent.com/assets/13416741/22576788/a4ab3ee2-e9f8-11e6-8231-11445f36d244.png)
这是第二轮中的请求
