### ISSUE TITLE
设置okgo.setCertificates(in) 走单向SSL 挂出异常 异常见内容 急！！！！

### ISSUE THREAD

**Issue by awpss** [jeasonlzy/okhttp-OkGo#163]
javax.net.ssl.SSLHandshakeException: com.android.org.bouncycastle.jce.exception.ExtCertPathValidatorException: Could not validate certificate: null
01-22 14:35:44.289 6242-6242/com.infosec.auth W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:410)
01-22 14:35:44.289 6242-6242/com.infosec.auth W/System.err:     at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:241)
01-22 14:35:44.289 6242-6242/com.infosec.auth W/System.err:     at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:198)
01-22 14:35:44.289 6242-6242/com.infosec.auth W/System.err:     at okhttp3.internal.connection.RealConnection.buildConnection(RealConnection.java:174)
01-22 14:35:44.289 6242-6242/com.infosec.auth W/System.err:     at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:114)
01-22 14:35:44.289 6242-6242/com.infosec.auth W/System.err:     at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:193)
01-22 14:35:44.289 6242-6242/com.infosec.auth W/System.err:     at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:129)
01-22 14:35:44.289 6242-6242/com.infosec.auth W/System.err:     at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:98)
01-22 14:35:44.294 6242-6242/com.infosec.auth W/System.err:     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
01-22 14:35:44.294 6242-6242/com.infosec.auth W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
01-22 14:35:44.294 6242-6242/com.infosec.auth W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
01-22 14:35:44.294 6242-6242/com.infosec.auth W/System.err:     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109)
01-22 14:35:44.294 6242-6242/com.infosec.auth W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
01-22 14:35:44.294 6242-6242/com.infosec.auth W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
01-22 14:35:44.294 6242-6242/com.infosec.auth W/System.err:     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
01-22 14:35:44.294 6242-6242/com.infosec.auth W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
01-22 14:35:44.294 6242-6242/com.infosec.auth W/System.err:     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
01-22 14:35:44.294 6242-6242/com.infosec.auth W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
01-22 14:35:44.294 6242-6242/com.infosec.auth W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
01-22 14:35:44.294 6242-6242/com.infosec.auth W/System.err:     at com.lzy.okgo.interceptor.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:76)
01-22 14:35:44.294 6242-6242/com.infosec.auth W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
01-22 14:35:44.294 6242-6242/com.infosec.auth W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
01-22 14:35:44.294 6242-6242/com.infosec.auth W/System.err:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
01-22 14:35:44.294 6242-6242/com.infosec.auth W/System.err:     at okhttp3.RealCall.access$100(RealCall.java:33)
01-22 14:35:44.294 6242-6242/com.infosec.auth W/System.err:     at okhttp3.RealCall$AsyncCall.execute(RealCall.java:120)
01-22 14:35:44.294 6242-6242/com.infosec.auth W/System.err:     at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
01-22 14:35:44.294 6242-6242/com.infosec.auth W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
01-22 14:35:44.294 6242-6242/com.infosec.auth W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
01-22 14:35:44.294 6242-6242/com.infosec.auth W/System.err:     at java.lang.Thread.run(Thread.java:841)

代码:
   
  class app extends Application{
            OkGo.init(this);
            InputStream in = this.getClass().getClassLoader().getResourceAsStream("assets/xxx.cer");
        try {
            OkGo.getInstance().debug("OkGo", Level.INFO, true)
                    .setCertificates(in);
        } catch (Exception e) {

        }
}

class xxactivity extends BaseActivity{
 //......省略

 onClick(){
 
     OkGo.post(Constant.ROOT_URL + Constant.REGISTER_URL).params("xx", "xx")
                .tag(this)
                .params("xx", "xx")
                .params("xx", xx)
                .params("xx", "1")
                .cacheMode(CacheMode.NO_CACHE)
                .execute(new RegisterCallback<RegisterBean>() {
                    @Override
                    public void onSuccess(RegisterBean registerBean, Call call, Response response) {
                        skipIntent(RegisterActivity.this, SettingCodeActivity.class, "register", registerBean);

                    }

                    @Override
                    public void onError(Call call, Response response, Exception e) {
                        super.onError(call, response, e);
                        showToast(e.getMessage());
                    }
                });

    }
   
}
}

**Comment by awpss** [comment]
okGO 版本是2.1.4

**Comment by jielundewode** [comment]
ExtCertPathValidatorException路径不对？
