### ISSUE TITLE
关于集成Rxjav后的缓存的实现

### ISSUE THREAD

**Issue by ddssingsong** [jeasonlzy/okhttp-OkGo#164]
**出现场景**
   当我在使用okgo的时候，需要使用rxjava进行线程的切换，但是当我使用到缓存的时候发现无法使用缓存，定位到CacheCall这个类，debug之后发现使用rxjava根本走不到缓存的地方，请教一下如果我想使用rxjava实现缓存该怎么做呢？

**Comment by jeasonlzy** [comment]
rxjava目前不支持缓存。

**Comment by andansky** [comment]
有没有大神能实现rxjava方式的缓存啊

**Comment by jeasonlzy** [comment]
okgo升级3.0，已经支持缓存，支持rxjava2
