### ISSUE TITLE
使用OkRx如何获取Response对象

### ISSUE THREAD

**Issue by conghuahuadan** [jeasonlzy/okhttp-OkGo#171]
你好，使用OkRx如何获取Response对象？示例代码并没有提供相关的方法

```
    OkGo.post(Urls.URL_METHOD)//
        .headers("aaa", "111")//
        .params("bbb", "222")//
        .getCall(StringConvert.create(), RxAdapter.<String>create())//以上为产生请求事件,请求默认发生在IO线程
        .doOnSubscribe(() -> {
            showLoading();  //开始请求前显示对话框
        })
        .observeOn(AndroidSchedulers.mainThread())//切换到主线程
        .subscribe(s -> {
            dismissLoading();               //请求成功,关闭对话框
            handleResponse(s, null, null);
        }, throwable -> {
            throwable.printStackTrace();
            dismissLoading();       //请求失败
            showToast("请求失败");
            handleError(null, null);
        });

```

**Comment by jeasonlzy** [comment]
自定义一个 Convert 对象，返回Response 就行了。

**Comment by Christain** [comment]
.subscribe(new Action1<String>() {
        @Override
        public void call(String s) {
            dismissLoading();               //请求成功,关闭对话框
            handleResponse(s, null, null);
        }
    }, new Action1<Throwable>() {
        @Override
        public void call(Throwable throwable) {
            throwable.printStackTrace();
            dismissLoading();       //请求失败
            showToast("请求失败");
            handleError(null, null);
        }
我想问一下，怎么定义Convert，可以在Action1里面获得Response和Call对象
