### ISSUE TITLE
HTTP FAILED: java.io.IOException: Canceled

### ISSUE THREAD

**Issue by AlexLiuSheng** [jeasonlzy/okhttp-OkGo#172]
请求接口是以PostString方式请求的 ，有时候要报这个HTTP FAILED: java.io.IOException: Canceled或者Socket Cloesd.请问大大 是怎么回事啊.我用NoHttp不会有这个错误，郁闷中...

**Comment by AlexLiuSheng** [comment]
我设置了延迟请求1s左右就不会报这个错了，大大求指点

**Comment by DonnyHe** [comment]
你好，我现在也出现这个问题，不知道你解决没有？

**Comment by AlexLiuSheng** [comment]
应该是哪里cancel掉了请求，之前我是在baseActivity里面cancel掉了。所以每次新开界面的时候，如果有界面被销毁就会调用cancel。。。

**Comment by DonnyHe** [comment]
太感谢了，这个问题困扰了我很久了，头都大了，各种搜索，各种尝试，收到你的邮件我立刻试验了，我在BaseFragment和BaseActivity的onDestroy里面调用了OkGo.getInstance().cancelAll();结果偶尔出现这个异常，但是又不走onError回调。现在没问题了。

**Comment by AlexLiuSheng** [comment]
。。。可能我没表达清楚。我的意思是我之前出现这个问题是因为我在baseActivity的onDestroy里面CancelAll了所有的请求，所以当这个界面还没有完全销毁（还没调用onDestroy），同时下一个Activity就已经发起请求。这时上一个OnDestroy一调用，就会造成上述错误。所以最好的情况是不要在base里面处理http cancel事件

**Comment by DonnyHe** [comment]
哦，是这样，我明白了，真是多谢了

**Comment by wzxlucky** [comment]
@DonnyHe @AlexLiuSheng 我的情况是在fragment中请求，然后切换别的fragment，在回来，就HTTP FAILED: java.io.IOException: Canceled
