### ISSUE TITLE
小米四，安卓6.0 安装运行okGo_v2.1.3.apk，进入”强大缓存示例页面”报错

### ISSUE THREAD

**Issue by CodeDogandCat** [jeasonlzy/okhttp-OkGo#175]
第一次运行app，进入该页面，报错如下图：
![screenshot_2017-02-17-10-26-30-166_com lzy demo](https://cloud.githubusercontent.com/assets/14949494/23050331/9b41efe0-f4fc-11e6-8158-487c5f127518.png)

kill应用，再次运行，进入该页面，直接闪退
作者，想请教一下是怎么回事？

**Comment by loveOpenCV** [comment]
我也是，直接闪退了，提示{"errNum":300205,"errMsg":"Api does not exist"}

**Comment by jeasonlzy** [comment]
这个是服务器接口挂了，可能要换个服务器，这个不影响。。
