### ISSUE TITLE
网络请求创建后，在提交给服务器前怎么取消？

### ISSUE THREAD

**Issue by fly263** [jeasonlzy/okhttp-OkGo#176]
有两种场景：1、没有网络不需要提交网络请求 2、APP启动的时候已经检测到版本过低需要升级，如果用户不升级，进行其他操作，调用其他接口不用提交请求给服务器
针对上述问题，有两种解决思路：
1、在OkGo提交请求的方法外面再包一层，使用自定义的回调等，有网络时才提交请求，这样做实现比较复杂
2、在onBefore的回调方法中终止请求，在onError回调中处理异常，弹出提示信息等
但经过测试发现，在onBefore中调用OkGo.getInstance().cancelTag(context)无法取消请求

也许第二种方式不是好的方案，但是第一种有点复杂，在框架层是否需要考虑一下？

**Comment by jeasonlzy** [comment]
onBefore 中是无法取消的，因为这个时候这个请求还没有加入到队列中，所以无论是未发出的请求还是已经发出的请求，都找不到这个tag，当然也就无法取消了。

没有网络就算提交了网络请求也是直接回调onError，这个也没什么影响，因为这个时候并没有任何请求加入队列，而是直接回调onError
