### ISSUE TITLE
Post请求JSON方式时，缓存不起作用

### ISSUE THREAD

**Issue by lc5450** [jeasonlzy/okhttp-OkGo#177]
当参数不同是缓存不起作用

baseRequest.setCacheKey(HttpUtils.createUrlFromParams(baseRequest.getBaseUrl(), baseRequest.getParams().urlParamsMap));

json方式时
baseRequest.getParams().urlParamsMap是没有参数的

**Comment by jeasonlzy** [comment]
上传json的时候，params 的参数都无效。这个文档里面有写。
