### ISSUE TITLE
下载时候，存在数据库隐患

### ISSUE THREAD

**Issue by AndMy** [jeasonlzy/okhttp-OkGo#179]
SQLiteConnectionPool(19981): A SQLiteConnection object for database '/data/data/com.hualumedia.opera/databases/downloaddata.db' was leaked!  Please fix your application to end transactions in progress properly and to close the database when it is no longer needed.

**Comment by jeasonlzy** [comment]
okgo升级3.0，数据库模块进行了重构，欢迎使用。。
