### ISSUE TITLE
上传图片文件失败

### ISSUE THREAD

**Issue by MelvinCen** [jeasonlzy/okhttp-OkGo#180]
OkGo.post(url)
.tag(context)
.isMultipart(true)
.params("file1",file)
.execute(callback);
这样子上传打印出来content-type 是application/json; charset=utf-8
我把参数自己拼接在url上，params放文件
isMultipart(true)也设置了，文件也放了

**Comment by jeasonlzy** [comment]
你确定是上传的content-type，不是响应的content-type？
