### ISSUE TITLE
onError里的Response能获得类似onSuccess的返回吗？

### ISSUE THREAD

**Issue by Staray** [jeasonlzy/okhttp-OkGo#181]
具体情况是这样的：
服务器返回了错误码比如：400、401等等，这时不会库会直接调用onError(Call call, Response response, Exception e)的方法，response里面能获取到错误码等信息，可是服务器返回的错误消息就没法获取了，
我传一张postman的请求图：http://7xawq4.com1.z0.glb.clouddn.com/QQ%E6%88%AA%E5%9B%BE20170227165044.png

这种情况怎么处理，我想获取错误消息。

**Comment by jeasonlzy** [comment]
convertSuccess 中抛出异常，详细看demo，有代码示例。

**Comment by Staray** [comment]
谢谢，我按照demo的示例改好了，非常感谢！

**Comment by chao9267** [comment]
请问是怎么弄的？ 我们服务器返回的错误码全是500   走onError方法,body为空，拿不到服务器返回的错误信息 message字段 ，

**Comment by chao9267** [comment]
@Staray
