### ISSUE TITLE
文件下载出错：从Url获取文件名称考虑情况不够周全

### ISSUE THREAD

**Issue by JebySun** [jeasonlzy/okhttp-OkGo#182]
例如，下载一张图片的地址是http://mavin-manzhan.oss-cn-hangzhou.aliyuncs.com/1486631099150286149.jpg?x-oss-process=image/watermark,image_d2F0ZXJtYXJrXzIwMF81MC5wbmc
不指定下载文件名，然后报错，根据错误信息，看出是从这个url获取文件名出问题了。

**Comment by jeasonlzy** [comment]
这种情况比较复杂了，一般建议服务端返回的头信息里面携带文件名，这样比较规范。

**Comment by jeasonlzy** [comment]
okgo升级3.0 已经修复。欢迎使用。。
