### ISSUE TITLE
求助：是否有多地址管理功能？

### ISSUE THREAD

**Issue by 1371030** [jeasonlzy/okhttp-OkGo#183]
如下所示：
http://a1.domain.net
http://a2.domain.net
.....

访问的都是/file/a1.json文件，如何在a1.domain.net不能访问的情况下切换到另一域名或在域名列表中进行选择？

**Comment by 1371030** [comment]
有人能帮忙解答下吗？

**Comment by 1371030** [comment]
求助，求助

**Comment by jeasonlzy** [comment]
这个可以在业务层面做，发生异常后，修改你的基类url就行。。在库层面无法提供，，
