### ISSUE TITLE
com.lzy.okgo.model.HttpParams.FileWrapper   toString方法filename后面多了一个单引号

### ISSUE THREAD

**Issue by ideastudios** [jeasonlzy/okhttp-OkGo#185]
![20170301141254](https://cloud.githubusercontent.com/assets/16684417/23447975/59602cea-fe89-11e6-80b8-65816267a705.jpg)

**Comment by jeasonlzy** [comment]
好眼力，下次改掉。。

**Comment by jeasonlzy** [comment]
已修改
