### ISSUE TITLE
上传图片问题，求解答

### ISSUE THREAD

**Issue by CodeDogandCat** [jeasonlzy/okhttp-OkGo#189]
I/OkGo: <-- HTTP FAILED: java.net.ProtocolException: expected 599 bytes but received 8192
W/System.err: java.net.ProtocolException: expected 599 bytes but received 8192
W/System.err:     at okhttp3.internal.http.Http1xStream$FixedLengthSink.write(Http1xStream.java:279)
W/System.err:     at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:171)
W/System.err:     at okio.RealBufferedSink.write(RealBufferedSink.java:41)
W/System.err:     at okio.ForwardingSink.write(ForwardingSink.java:35)
W/System.err:     at com.lzy.okgo.request.ProgressRequestBody$CountingSink.write(ProgressRequestBody.java:78)
W/System.err:     at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:171)
W/System.err:     at okio.RealBufferedSink.writeAll(RealBufferedSink.java:99)
W/System.err:     at okhttp3.RequestBody$3.writeTo(RequestBody.java:118)
W/System.err:     at okhttp3.MultipartBody.writeOrCountBytes(MultipartBody.java:171)
W/System.err:     at okhttp3.MultipartBody.writeTo(MultipartBody.java:113)
W/System.err:     at com.lzy.okgo.request.ProgressRequestBody.writeTo(ProgressRequestBody.java:61)
W/System.err:     at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:47)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
W/System.err:     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
W/System.err:     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
W/System.err:     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
W/System.err:     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
W/System.err:     at com.lzy.okgo.interceptor.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:76)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
W/System.err:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
W/System.err:     at okhttp3.RealCall.access$100(RealCall.java:33)
W/System.err:     at okhttp3.RealCall$AsyncCall.execute(RealCall.java:120)
W/System.err:     at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
W/System.err:     at java.lang.Thread.run(Thread.java:818)

**Comment by zZiv** [comment]
问题大概是这个吧？ expected 599 bytes but received 8192

**Comment by jeasonlzy** [comment]
这个应该是服务端的问题，返回的实际大小和content-length不一致导致的。
