### ISSUE TITLE
post多条汉字数据，解析失败

### ISSUE THREAD

**Issue by liushuike521** [jeasonlzy/okhttp-OkGo#190]
用 new FormBody.Builder() 的方式传递多个参数（十几条汉字参数），拦截返回了结果（成功打印了了返回信息），但是打印请求的状态的时候说请求不到资源，并且请求网址是 以  .jsp  结尾，返回404
拦截结果如下：

`03-06 18:33:31.712 14173-14827/com.yuntu.tianzehanyu E/拦截的结果: {"success":false,"errMsg":"该手机号已注册！","otherMsg":null,"data":null,"total":0,"rows":null,"enterpriseName":null,"enterpriseId":0,"otherList":null,"otherList1":null}--------`

请求如下：

`OkGo.post(sb.toString())
				.tag(this)
				.requestBody(requestBody)
				.execute(new DialogCallback<CompleteCreateNewUserBean>(this) {
					@Override
					public void onSuccess(CompleteCreateNewUserBean completeCreateNewUserBean, Call call, Response response) {.........}`

具体如下：
`03-06 18:33:31.691 14173-14827/com.yuntu.tianzehanyu W/OkGo: --> POST http://192.168.1.250/rest/user/completeCreateNewUser http/1.1
03-06 18:33:31.691 14173-14827/com.yuntu.tianzehanyu W/OkGo: 	Accept-Language: zh-CN,zh;q=0.8
03-06 18:33:31.691 14173-14827/com.yuntu.tianzehanyu W/OkGo: 	User-Agent: Mozilla/5.0 (Linux; U; Android 6.0.1; zh-cn; MI MAX Build/MMB29M) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30
03-06 18:33:31.691 14173-14827/com.yuntu.tianzehanyu W/OkGo: 	Content-Length: 446
03-06 18:33:31.691 14173-14827/com.yuntu.tianzehanyu W/OkGo:  
03-06 18:33:31.692 14173-14827/com.yuntu.tianzehanyu W/OkGo: 	body:realName=%E5%BB%96%E5%9B%BD%E5%A8%81&sex=%E7%94%B7&enterpriseName=%E6%B7%B1%E5%9C%B3%E5%89%8D%E6%B5%B7%E4%BA%91%E9%80%94%E4%BF%A1%E6%81%AF%E6%8A%80%E6%9C%AF%E6%9C%89%E9%99%90%E5%85%AC%E5%8F%B8&departmentId=3&position=%E5%B8%82%E5%9C%BA%E9%83%A8%E7%BB%8F%E7%90%86&email=10528765%40qq.com&phoneNo=13265438008&age=0&education=0&profession=&institutions=&springMVCToken=7ZRS9E39TB0M3JCZVZASOS9RC63K77LX&createType=%E4%BC%81%E4%B8%9A%E7%94%A8%E6%88%B7
03-06 18:33:31.692 14173-14827/com.yuntu.tianzehanyu W/OkGo: --> END POST
03-06 18:33:31.712 14173-14827/com.yuntu.tianzehanyu E/拦截的结果: {"success":false,"errMsg":"该手机号已注册！","otherMsg":null,"data":null,"total":0,"rows":null,"enterpriseName":null,"enterpriseId":0,"otherList":null,"otherList1":null}--------
03-06 18:33:31.736 14173-14827/com.yuntu.tianzehanyu W/OkGo: <-- 404 Not Found http://192.168.1.250/rest/user/test.jsp (44ms）
03-06 18:33:31.736 14173-14827/com.yuntu.tianzehanyu W/OkGo: 	Server: Apache-Coyote/1.1
03-06 18:33:31.736 14173-14827/com.yuntu.tianzehanyu W/OkGo: 	Content-Type: text/html;charset=utf-8
03-06 18:33:31.736 14173-14827/com.yuntu.tianzehanyu W/OkGo: 	Content-Language: en
03-06 18:33:31.736 14173-14827/com.yuntu.tianzehanyu W/OkGo: 	Content-Length: 949
03-06 18:33:31.736 14173-14827/com.yuntu.tianzehanyu W/OkGo: 	Date: Mon, 06 Mar 2017 10:35:03 GMT
03-06 18:33:31.736 14173-14827/com.yuntu.tianzehanyu W/OkGo:  
03-06 18:33:31.737 14173-14827/com.yuntu.tianzehanyu W/OkGo: 	想要的结果body:<html><head><title>Apache Tomcat/7.0.53 - Error report</title><style></style> </head><body><h1>HTTP Status 404 - </h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u></u></p><p><b>description</b> <u>The requested resource is not available.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.53</h3></body></html>
03-06 18:33:31.737 14173-14827/com.yuntu.tianzehanyu W/OkGo: <-- END HTTP
03-06 18:33:31.754 14173-14173/com.yuntu.tianzehanyu W/System.err: com.lzy.okgo.exception.OkGoException: 服务器数据异常!
03-06 18:33:31.754 14173-14173/com.yuntu.tianzehanyu W/System.err:     at com.lzy.okgo.adapter.CacheCall$1.onResponse(CacheCall.java:155)
03-06 18:33:31.754 14173-14173/com.yuntu.tianzehanyu W/System.err:     at okhttp3.RealCall$AsyncCall.execute(RealCall.java:126)
03-06 18:33:31.754 14173-14173/com.yuntu.tianzehanyu W/System.err:     at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
03-06 18:33:31.754 14173-14173/com.yuntu.tianzehanyu W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
03-06 18:33:31.754 14173-14173/com.yuntu.tianzehanyu W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
03-06 18:33:31.754 14173-14173/com.yuntu.tianzehanyu W/System.err:     at java.lang.Thread.run(Thread.java:818)
03-06 18:33:31.759 14173-14173/com.yuntu.tianzehanyu W/System.err: com.lzy.okgo.exception.OkGoException: 服务器数据异常!
03-06 18:33:31.759 14173-14173/com.yuntu.tianzehanyu W/System.err:     at com.lzy.okgo.adapter.CacheCall$1.onResponse(CacheCall.java:155)
03-06 18:33:31.759 14173-14173/com.yuntu.tianzehanyu W/System.err:     at okhttp3.RealCall$AsyncCall.execute(RealCall.java:126)
03-06 18:33:31.759 14173-14173/com.yuntu.tianzehanyu W/System.err:     at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
03-06 18:33:31.759 14173-14173/com.yuntu.tianzehanyu W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
03-06 18:33:31.759 14173-14173/com.yuntu.tianzehanyu W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)`

**Comment by jeasonlzy** [comment]
返回 404 说明地址不对，检查你的url。。

**Comment by jeasonlzy** [comment]
群里已解决，服务端重定向问题。

**Comment by liushuike521** [comment]
问题是由拦截器引起的，关闭拦截器就可以了，对于每次请求参数都要求变更的接口，慎用拦截器。

**Comment by BlackFoxes** [comment]
想问问大家在github上运行curl语句是什么意思，还有刚毕业对Github了解不多不知道这个东西怎么用才能发挥他的最大功效
