### ISSUE TITLE
BitmapCallback 返回的图片未压缩问题

### ISSUE THREAD

**Issue by Android-zc** [jeasonlzy/okhttp-OkGo#191]
BitmapCallback 返回的图片未压缩问题，项目加载网络bitmap大图出现OOM，如何压缩，需要继承AbsCallback<Bitmap>，自己重新写一个callback，里面压缩？

**Comment by jeasonlzy** [comment]
对。自带的 callback 只提供基本功能，任何定制化的功能，可以自己实现。

**Comment by jeasonlzy** [comment]
okgo更新3.0， 对BitmapCallback进行了增强，已经自动压缩了。。
