### ISSUE TITLE
 关于连接超时等时间设置6秒，时间已经超过6秒还没提示连接超时。

### ISSUE THREAD

**Issue by dazhi186** [jeasonlzy/okhttp-OkGo#198]
OkGo.getInstance()
                    //如果使用默认的 60秒,以下三行也不需要传
                    .setConnectTimeout(6*1000)  //全局的连接超时时间

您好，咨询个问题，现在接口20秒才返回数据，app已经设置6秒超时，为什么请求接口超过了6秒依然没有提示连接超时？

**Comment by jeasonlzy** [comment]
超时6秒的意思不是6秒数据没返回就一定会超时，比如你有 100k 的数据，网速是 1k/s  ，你把所有的时间都设置为 10 秒，但是网络正常全部连上，这些数据也要 100 秒才能返回，你最后看到的结果是 100 秒后数据正常返回了，但是你的 10秒超时并不会触发，因为并没有超时。

**Comment by dazhi186** [comment]
如果想实现指定时间内（6秒）接口还没返回数据就提示超时，这个该怎么触发指定时间内超时呢？

**Comment by Tesp** [comment]
同问  （如果想实现指定时间内（6秒）接口还没返回数据就提示超时，这个该怎么触发指定时间内超时呢？）

**Comment by dazhi186** [comment]
你好，请问超时6秒的意思是不是 6秒内http请求都没连接成功才响应？或者什么情况下才响应6秒超时？



dazhi.zhang@zingfon.com
 
发件人： 廖子尧
发送时间： 2017-03-17 09:31
收件人： jeasonlzy/okhttp-OkGo
抄送： dazhi186; Author
主题： Re: [jeasonlzy/okhttp-OkGo] 关于连接超时等时间设置6秒，时间已经超过6秒还没提示连接超时。 (#198)
超时6秒的意思不是6秒数据没返回就一定会超时，比如你有 100k 的数据，网速是 1k/s ，你把所有的时间都设置为 10 秒，但是网络正常全部连上，这些数据也要 100 秒才能返回，你最后看到的结果是 100 秒后数据正常返回了，但是你的 10秒超时并不会触发，因为并没有超时。
