### ISSUE TITLE
缓存的方式不够灵活。

### ISSUE THREAD

**Issue by Misayanice** [jeasonlzy/okhttp-OkGo#200]
拜读源码，看到缓存的data，是以blob直接存入数据库中的。这样的话，如果要更新一个列表上的单条数据
，就很难操作了，数据结构不够灵活。

**Comment by jeasonlzy** [comment]
其实缓存是存储的数据对象，无论你改单条还是多条，还是某一条的某个字段，最后都只是将这个对象再次更新下保存到数据库中，这样想的话，也就不能算不灵活了。。而且这个库中的CacheManager可以替代项目中的sp，文件等需要缓存的数据，还能有过期时间控制。。
