### ISSUE TITLE
我觉得cache success和http请求成功的接口应该合并。参看okhttp本来的缓存模块，无论缓存成功还是http请求成功，都是通过“onResponse()”返回。您觉得呢。

### ISSUE THREAD

**Issue by Misayanice** [jeasonlzy/okhttp-OkGo#201]

**Comment by jeasonlzy** [comment]
在 1.8.2 的版本以前，他们是合并的，但是实际使用的时候并不方便，所以 从 1.8.2 以后拆分了。至少拆开后，我可以决定是否使用缓存，知道当前数据是否是来自缓存等等。。合并之后的问题多多，与缓存模式不好共存。。

**Comment by cervy** [comment]
虽然题主的逻辑是一般成功后肯定会缓存， 不过 给用户做到可选也是有必要的吧

**Comment by jeasonlzy** [comment]
正式因为为了可选才分两个回调，并且提供了5种缓存模式，如果对模式的回调顺序不满意，甚至可以自己决定是否使用缓存。。无论从哪方便讲，都要好于一个回调的形式。
