### ISSUE TITLE
为什么在StringCallback()中的onError()获取不到返回的 josn的值

### ISSUE THREAD

**Issue by lsyz0021** [jeasonlzy/okhttp-OkGo#202]
为什么在StringCallback()中的onError()获取不到返回的 json的值，我们需在onError()获取响应的json，要做“手机已注册”、“身份证已注册”这样的提示，但是发现获取的json不是我们想要的，我可以在convertSuccess()获取到想要的json，但是这是子线程，不能ui操作。请问怎么样才能在错误的时候获取json呢??

**Comment by jeasonlzy** [comment]
看demo，抛异常。把数据用异常抛出去，onError中就获取到了。

**Comment by lsyz0021** [comment]
谢谢，已经解决了，其实我也是采用类似的处理方式，只不过不是抛异常，而是利用eventBus  发送msg到主线程
