### ISSUE TITLE
关于setRetryCount好像不起作用

### ISSUE THREAD

**Issue by conghuahuadan** [jeasonlzy/okhttp-OkGo#204]
你好，作者，我在使用你的请求库去请求接口，非常偶然的情况下，我这边请求成功，但是后台发现我执行了两到多次的操作，同时后台服务器的网络不是很稳定，所以我不确定是我的问题，还是后台的问题,，我已经setRetryCount=0

**Comment by jeasonlzy** [comment]
是有作用的。。okgo更新了3.0  欢迎体验。。
