### ISSUE TITLE
有没有可能加入 断点/分片 上传的功能

### ISSUE THREAD

**Issue by weituotian** [jeasonlzy/okhttp-OkGo#205]
上传文件的时候如果能加入暂停功能就高大上了.

不过这是史上android上传最大最难的问题, 目前还没有开源库能够实现

**Comment by cervy** [comment]
我觉得都是端对端通信， 可模拟下载的思路， 可能需要服务端做类似平时客户端暂停下载的操作

**Comment by weituotian** [comment]
@cervy 的确有点为难了,除非服务器分片上传,在合并,o(︶︿︶)o 唉

**Comment by jeasonlzy** [comment]
断点上传不提供的原因是 主要逻辑在服务端而不是客户端，所以重点是服务器要支持，就算我按我的思路提供一套断点上传的逻辑，你们服务器不是我的规范，那不就白扯了么。。

**Comment by jeasonlzy** [comment]
并不是开源库不提供，而不是没法提供，不同的服务器实现思路都不一样，总不能统一全部的服务器逻辑吧。。

**Comment by weituotian** [comment]
@jeasonlzy 能不能推一个规范出来,然后要求大家都用这套逻辑.

**Comment by jeasonlzy** [comment]
不可能，先不说服务端会不会遵守，就算遵守，有的还需要有自己的业务逻辑。。所以这个功能都是自己和服务端约定实现，任何开源库都不会提供的。

**Comment by weituotian** [comment]
@jeasonlzy 
手机百度云好像可以上传暂停的,比如熄屏后就会中断什么的,这个很厉害

**Comment by weituotian** [comment]
@jeasonlzy 
如果我想自己实现暂停怎么办?
参考文章:
[Spring MVC大文件的断点续传（File Transfer Resume）](http://rensanning.iteye.com/blog/2248760)

**Comment by jeasonlzy** [comment]
主要逻辑还是在服务端，服务端不确定的情况，客户端是不会统一的。。

**Comment by weituotian** [comment]
我找到另外一篇文章
[springmvc mybatis fileupload实现文件断点续传](http://blog.csdn.net/wang_keng/article/details/50968843)

它的主要思路是使用jQuery fileupload插件进行，它负责将文件分为N个片段进行传输，同时会在http请求头部添加一个请求头：Content-Range；此请求头用于告诉服务器此时传输的是哪个区间的片段。

oK-Go说不定也可以按照这个思路走

**Comment by weituotian** [comment]
@jeasonlzy 
[SSM框架+Plupload实现断点续传（Spring+SpringMVC+MyBatis+Plupload）](http://www.cnblogs.com/yiye/p/5798521.html)

这篇文章也是考虑将文件分片
b/s模式下实现文件中断只能通过这种方式了
至于服务器怎么合并分片那是服务器的事情
oK-Go只需要分片上传就可以了
可以给用户一个选项,是否开启大文件分片上传

这个方法的实现,oK-Go可以参考[Plupload](https://github.com/moxiecode/plupload)
或者[jQuery-File-Upload](https://github.com/blueimp/jQuery-File-Upload)
又或者自己实现, 分片也是可以做到的

**Comment by jeasonlzy** [comment]
核心问题不是okgo做分片，而是客户端如何和服务端约定一套分片规则，这才是重点，这个规则约定好了，分片也就几行代码的事，但是这个规则没有规范，没有统一，不同的服务端和业务要求都可能不一样，所以我自己做分片没有意义，最终还是依靠双方的约定，所以结论就是，并不是okgo不能做分片，而是做了也没有意义，没有意义的事情，何必要做呢？

**Comment by weituotian** [comment]
最后再发一个百度的官方上传插件
[webuploader](https://github.com/fex-team/webuploader)




它的服务端核心上传代码
[fileupload.php](https://github.com/fex-team/webuploader/blob/master/server/fileupload.php)
```
$index = 0;
$done = true;
for( $index = 0; $index < $chunks; $index++ ) {
    if ( !file_exists("{$filePath}_{$index}.part") ) {
        $done = false;
        break;
    }
}
if ( $done ) {
    if (!$out = @fopen($uploadPath, "wb")) {
        die('{"jsonrpc" : "2.0", "error" : {"code": 102, "message": "Failed to open output stream."}, "id" : "id"}');
    }
    if ( flock($out, LOCK_EX) ) {
        for( $index = 0; $index < $chunks; $index++ ) {
            if (!$in = @fopen("{$filePath}_{$index}.part", "rb")) {
                break;
            }
            while ($buff = fread($in, 4096)) {
                fwrite($out, $buff);
            }
            @fclose($in);
            @unlink("{$filePath}_{$index}.part");
        }
        flock($out, LOCK_UN);
    }
    @fclose($out);
}
// Return Success JSON-RPC response
die('{"jsonrpc" : "2.0", "result" : null, "id" : "id"}');
```
上面的代码就是检验是否分片都齐全,齐全的话就遍历所有分片
写到一个文件中

而它是怎么发送分片的呢
```
$chunk = isset($_REQUEST["chunk"]) ? intval($_REQUEST["chunk"]) : 0;
$chunks = isset($_REQUEST["chunks"]) ? intval($_REQUEST["chunks"]) : 1;
```
```
rename("{$filePath}_{$chunk}.parttmp", "{$filePath}_{$chunk}.part");
```

它是上传一个文件的时候, 分片之后, 

每一个分片都发一个post请求去上传,
带一个参数chunk表示分片的索引
带一个参数chunks表示分片的总数

每个分片保存在服务器后的名字就是{$filePath}_{$chunk}.part这种形式

当最后一个分片上传完毕的时候,就开始合并分片.

所以大概所有服务器,无论后端语言是什么,都必须做的合并分片

**所以oK-Go做的工作只需要将文件分片之后
带参数逐个上传, 表示或者并发上传(控制在指定数量)**

之后合并文件就是服务器的事情了

**就是说oK-Go提供分片上传, 但是你要按我这个规范搞服务器的上传代码,
百度的webuploader也是,要使用它的分片上传功能,也是要我们配合它的上传方式写代码的,当然它也准备了例子**

**Comment by jeasonlzy** [comment]
这些我知道，所以核心问题就是，这个框架写出来，**想使用分片的话，对服务端是有约束的**。

如果是个老项目，想改动服务器就比较困难了，如果是个新项目，对于对象存储，分片上传的功能，绝大部分创业公司都用七牛或者阿里云，他们都有自己的sdk，默认已经提供了分片逻辑，这时候也是用他们的服务和sdk，而不会用okgo，所以如果 对于分片这个功能，目前需求并不是很大，而且成本高，效果不好。这也是众多开源网络框架都找不到这个功能的原因。 

当然，如果你特别希望这个功能，你可以自己实现一个，然后pr合并到这个项目来，开源项目需要的是众多开发者共同开发，来保证功能的完整性和易用性。

**Comment by weituotian** [comment]
@jeasonlzy ok!我有空试试。
