### ISSUE TITLE
多个应用使用OKGo之后，应用存在相同Provider的authorities

### ISSUE THREAD

**Issue by shejishi** [jeasonlzy/okhttp-OkGo#206]
`<provider
            android:name="android.support.v4.content.FileProvider"
            android:authorities="com.lzy.imagepicker.provider"`
            android:exported="false"
            android:grantUriPermissions="true" >
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/provider_paths" />
</provider>
`
多个应用存在相同的authorities之后，我的魅族手机就安装不了，能不能将authorities设置为软编码的形式动态获取值？

**Comment by jeasonlzy** [comment]
这是 ImagePicker 的问题，详细请看 imagepicker 的文档和解决办法。
