### ISSUE TITLE
getOkHttpClient没有考虑多线程调用

### ISSUE THREAD

**Issue by haipinghuang** [jeasonlzy/okhttp-OkGo#207]
public OkHttpClient getOkHttpClient() {
        if (okHttpClient == null) okHttpClient = okHttpClientBuilder.build();
        return okHttpClient;
    }
如上，这里应该使用单例懒加载模式，因为此处涉及多线程调用，相应的代码可以如下
 public OkHttpClient getOkHttpClient() {
        if (okHttpClient == null)
            synchronized (OkGo.class){
                if (okHttpClient == null) okHttpClient = okHttpClientBuilder.build();
            }
        return okHttpClient;
    }

**Comment by jeasonlzy** [comment]
收到，感谢。。

**Comment by jeasonlzy** [comment]
okgo3.0 已经修改使用方法。欢迎体验。。
