### ISSUE TITLE
Logcat无法打印出接口请求日志

### ISSUE THREAD

**Issue by wankey** [jeasonlzy/okhttp-OkGo#208]
OkGo.init(this);
File cacheDir = new File(getCacheDir(), "okhttp3");
Cache cache = new Cache(cacheDir, 20 * 1024 * 1024);
OkGo.getInstance()
	.setConnectTimeout(10000)
	.setReadTimeOut(10000)
	.setWriteTimeOut(10000)
	.setRetryCount(1)
	.setCertificates(HttpsUtils.UnSafeTrustManager)
	.setCacheMode(CacheMode.NO_CACHE)
	.getOkHttpClientBuilder()
	.cache(cache);
OkGo.getInstance().debug("ArenaAPI", Level.INFO, false).getOkHttpClientBuilder().addNetworkInterceptor(new StethoInterceptor());

已在Application中加入以上代码，但是Logcat中没有tag为 ArenaAPI的日志被输出，chrome的 debug tool里也没有网络请求日志被捕捉到（Stetho）

使用的lib版本：
    compile 'com.lzy.net:okgo:2.1.4' 
    compile 'com.squareup.okhttp3:okhttp:3.6.0'
    Compile 'com.facebook.stetho:stetho:1.4.2'
    Compile 'com.facebook.stetho:stetho-okhttp3:1.4.2'

测试机型：
Nexus5，android 6.0.1

**Comment by cuiwang** [comment]
一样,求解

**Comment by jeasonlzy** [comment]
okgo升级3.0，可以试试新版本。。
