### ISSUE TITLE
The constructor JsonCallback<LzyResponse<ServerModel>>(Test) is undefined

### ISSUE THREAD

**Issue by lohas923** [jeasonlzy/okhttp-OkGo#213]
复制示例中的文件到工程，出现这样的一个错误，需要怎么解决了？
有导入这三个文件
import com.lzy.okgo.callback.JsonCallback;
import com.lzy.okgo.model.LzyResponse;
import com.lzy.okgo.model.ServerModel;

The constructor JsonCallback<LzyResponse<ServerModel>>(Test) is undefined

**Comment by jeasonlzy** [comment]
请 仔细阅读文档，这个类库并不提供。
