### ISSUE TITLE
下载的时候downloadProgress方法返回的totalSize不到值

### ISSUE THREAD

**Issue by liushuike521** [jeasonlzy/okhttp-OkGo#215]
![3](https://cloud.githubusercontent.com/assets/20858219/24498111/28aaeb00-1570-11e7-9dab-154ba455dec5.png)
![2](https://cloud.githubusercontent.com/assets/20858219/24498113/2b66e9a2-1570-11e7-8964-95301a503007.png)
![1](https://cloud.githubusercontent.com/assets/20858219/24498117/2d2af062-1570-11e7-83da-fc6f56f268b5.png)

**Comment by liushuike521** [comment]
![1](https://cloud.githubusercontent.com/assets/20858219/24498068/07628642-1570-11e7-95a9-c768a8a3bba4.png)
![2](https://cloud.githubusercontent.com/assets/20858219/24498078/0c484aac-1570-11e7-8901-9ccdec148d9f.png)
![3](https://cloud.githubusercontent.com/assets/20858219/24498079/0ea6bd56-1570-11e7-9005-5fcf0619d005.png)

**Comment by jeasonlzy** [comment]
服务端没有返回 content-length  ，所以是 -1

**Comment by liushuike521** [comment]
没注意·····谢谢啦！
