### ISSUE TITLE
大佬中文乱码怎么搞呀。。谢谢

### ISSUE THREAD

**Issue by ZJLeBron** [jeasonlzy/okhttp-OkGo#216]

**Comment by tanweijiu** [comment]
是不是直接post中文呢？

**Comment by jeasonlzy** [comment]
目前没有乱码问题，所谓乱码

1. 使用者错误的把 % 表示的 url 编码，当成乱码
2. 后台没有使用 url 和 u8 解码
3. 后台没有返回 content-type 字段表明编码格式

目前所有反应乱码的，没有这三点之外的。。

**Comment by tanweijiu** [comment]
@jeasonlzy 是的，目前中文乱码都是这几点，而且基本上可以确定，都是因为后台没有强制修改中文的编码为u8造成的（tomcat默认使用的并不是u8..）。所以目前对于中文乱码的解决办法，@ZJLeBron  最简单的应该是直接使用.isMuitlPart(true).

**Comment by tanweijiu** [comment]
@jeasonlzy  在okgo里，并不能强制设置post的默认header里的content-type自带u8格式设置，在post的时候会给去掉这个属性，恕我愚笨..试过在几个地方添加后还是给去掉了。
