### ISSUE TITLE
在oppo的5.0 5.1手机上有个这样的问题

### ISSUE THREAD

**Issue by Gundam0079** [jeasonlzy/okhttp-OkGo#217]
错误日志如下 貌似是rx库问题
https://github.com/square/retrofit/issues/1088

Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void rx.functions.Action0.call()' on a null object reference
2    at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
3    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
4    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
5    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
6    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
7    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
8    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
9    at java.lang.Thread.run(Thread.java:818)

**Comment by jeasonlzy** [comment]
okgo升级3.0，对okrx进行了重构，欢迎使用。
