### ISSUE TITLE
Android 4.4.2 出现 NoClassDefFoundError

### ISSUE THREAD

**Issue by yangkun19921001** [jeasonlzy/okhttp-OkGo#224]
java.lang.NoClassDefFoundError: okhttp3.OkHttpClient$Builder
at com.lzy.okgo.OkGo.<init>(OkGo.java:60)
at com.lzy.okgo.OkGo.<init>(OkGo.java:44)
at com.lzy.okgo.OkGo$OkGoHolder.<clinit>(OkGo.java:73)
 at 

- 

- [ ] 

- # 

com.lzy.okgo.OkGo.getInstance(OkGo.java:69)

**Comment by yangkun19921001** [comment]
请问下这个问题怎么造成的啊?应该怎么解决啊?运行在6.0手机上是没有问题的!

**Comment by yangkun19921001** [comment]
已解决 不是 OKGO 问题

**Comment by yanlianhanlin** [comment]
我也碰到了这个问题 请问这个怎么解决

**Comment by 494293346** [comment]
我也碰到了这个问题 请问这个怎么解决 求指导

**Comment by niorgai** [comment]
应该是 Multidex 的问题, 仔细检查一下 Multidex 的配置吧
