### ISSUE TITLE
OkGo双向验证第二次连接报错：javax.net.ssl.SSLHandshakeException: Connection closed by peer

### ISSUE THREAD

**Issue by Staray** [jeasonlzy/okhttp-OkGo#225]
在Application中初始化：

    OkGo.init(this);
    HttpHeaders headers = new HttpHeaders();
    headers.put("accept", "application/json");   
    try {   
        OkGo.getInstance()
            .setCookieStore(new PersistentCookieStore())
            .setCertificates(OkGo.getContext().getAssets().open("rsa.bks"),         "12345678",OkGo.getContext().getAssets().open("ca.cer"))
            .addCommonHeaders(headers); 
    } catch (Exception e) { 
            Log.e("okgo init", e.getMessage()); 
    }

然后调用ssl链接：

    OkGo.get(url).execute(StringObjectCallback);

出错情况是这样的，第一次调用，能够成功，第二次调用，就会返回这个错误：
javax.net.ssl.SSLHandshakeException: Connection closed by peer.
是不是我使用的方式有问题?

**Comment by jeasonlzy** [comment]
添加一个  .headers("Connection", "close")  试试
