### ISSUE TITLE
关于取消网络请求

### ISSUE THREAD

**Issue by happinesspeople** [jeasonlzy/okhttp-OkGo#226]
正在请求网络时，此时推出界面，想要暂停网络的请求操作，请问是否有相关的调用呢？

**Comment by weilixing00** [comment]
@Override
    protected void onDestroy() {
        super.onDestroy();

        //根据 Tag 取消请求
        OkGo.getInstance().cancelTag(this);
    }
请求的时候加上tag
建议认真看看文档

**Comment by imxy** [comment]
建议你试试是否这样真的可以取消请求。。。

**Comment by zhumeiteng** [comment]
上传文件 即使cancelTag 也会走onSuccess方法

**Comment by aSmartTortoise** [comment]
@zhumeiteng ，@jeasonlzy 我也是遇到 “正在请求网络时候，退出界面，而且退出界面之前调用了cancle(tag)，结果仍然有回调”，请问你解决了么？
