### ISSUE TITLE
求更新。

### ISSUE THREAD

**Issue by zhaoxiuyu** [jeasonlzy/okhttp-OkGo#228]
OKHttp 和 RxJava 。。。 不是最新的。能否依赖最新的 jar  。

**Comment by jeasonlzy** [comment]
最近要准备更新了。。

**Comment by feer921** [comment]
@jeasonlzy 不支持断点续传吗？

**Comment by jeasonlzy** [comment]
okgo3.0 已经更新，欢迎使用。。okserver 支持断点续传。。
