### ISSUE TITLE
老大.....如果用了 泛型解析 有数据和没数据返回来的格式不一样 咋办 .......

### ISSUE THREAD

**Issue by k354250377** [jeasonlzy/okhttp-OkGo#231]

**Comment by jeasonlzy** [comment]
意思就是成功和失败的数据结构是不一样的，一般泛型只用于成功的回到，至于失败的格式，使用异常抛出或者其他自己喜欢的方法解析，demo里面有相关的代码。_

**Comment by Misayanice** [comment]
我的做法是：比如{"code":200,"msg":"","obj':{}}，对于这种结构，在请求成功的情况下，先获取返回的字符串，然后用普通的解析，只解析出code,然后改造回调:
if(code==200){
  callback.onResponse(msg)//业务正确
}else{
  callback.onFailure(code,msg);//业务错误
}。仅供参考

**Comment by k354250377** [comment]
不是 不是 重点是 同样是成功  但是 有数据的时候是 []没数据的时候变成了{}

**Comment by Misayanice** [comment]
我们这边api，会区分业务code， {"code":200,"msg":"',“obj”:[]}--->   有数据；{"code":（不等于200）201,"msg":"",“obj”:{}} --- > 无数据或其他业务错误。在这种场景下，我们可以用系统自带json解析出code,在code等于200的情况下，才对其进行全部解析，也保证了业务逻辑正确的情况下的解析json的结构。

**Comment by liuzheng9110** [comment]
https://github.com/k354250377  这个比较好的解决方案是让服务端统一格式
