### ISSUE TITLE
短时间请求不同productId的接口返回数据出现覆盖现象

### ISSUE THREAD

**Issue by wcglws** [jeasonlzy/okhttp-OkGo#233]
for (int i = 0; i < productsBeanList.size(); i++) {
                if (TextUtils.equals(ConstantString.DUAN_XIAN, productsBeanList.get(i).getGroupName())) {
                    mJinProductId = productsBeanList.get(i).getProductId();
                    getProductData(mJinProductId);
                } else if (TextUtils.equals(ConstantString.GU_HAI, productsBeanList.get(i).getGroupName())) {
                    mNiuProductId = productsBeanList.get(i).getProductId();
                    getProductData(mNiuProductId);
                } else if (TextUtils.equals(ConstantString.NIUREN_ZHANGGU, productsBeanList.get(i).getGroupName())) {
                    mGuProductId = productsBeanList.get(i).getProductId();
                    getProductData(mGuProductId);
                } else if (TextUtils.equals(ConstantString.NIUGU_CLASSROOM, productsBeanList.get(i).getGroupName())) {               
                    mClassroomId = productsBeanList.get(i).getProductId();
                    getProductData(mClassroomId);
                }
            }
像这种用法最后只能得到getProductData(productsBeanList.get(productsBeanList.size()-1).getProductId());这一个接口的数据，前几次都被最后一次覆盖了。。请问大神我这用法有问题么？请指点一二

**Comment by jeasonlzy** [comment]
没太看懂你的意思。。
