### ISSUE TITLE
发送多个网络请求

### ISSUE THREAD

**Issue by SmallTony** [jeasonlzy/okhttp-OkGo#235]
大神，由于项目需要，我们需要自己统计用户的行为（例如：用户的每一次点击的相关信息需要上传到我们的服务器），那这样有可能会发出很多的请求，如果网络不是很好的时候，就有可能同时存在很多个请求并行的情况，这种情况如果用户需要访问某个重要的接口，会不会出现阻塞等待的情况呢。是不是有可以设置请求优先级来让我们优先进行重要接口的访问，然后那些不重要的统计请求就设置较低优先级让他不影响主线呢？还有一个要补充的，就是按照我前面说的这种情况，我在做用户行为统计的时候，需不需要自己维护一个线程池来控制网络请求呀？还是说就算我有可能要进行接口的频繁调用，也不需要做其他的处理，只需要按照正常的请求调用你的网络框架就行了？

**Comment by SmallTony** [comment]
还有一个要补充的，就是按照我前面说的这种情况，我在做用户行为统计的时候，需不需要自己维护一个线程池来控制网络请求呀？还是说就算我有可能要进行接口的频繁调用，也不需要做其他的处理，只需要按照正常的请求调用你的网络框架就行了？

**Comment by jeasonlzy** [comment]
okhttp内部使用线程池的，默认并发数是5个，当你访问慢时候，超时就会走onError了，所以你的问题应该换个角度。 至于优先级队列，很可惜，okhttp内部的队列不支持优先级，需要改变okhttp的源码，这个就得不偿失了，如果一定要修改，网上很多帖子，搜索 okhttp优先级就能找到很多。。
