### ISSUE TITLE
https问题,发生SSLHandshakeException异常

### ISSUE THREAD

**Issue by LigerShuai** [jeasonlzy/okhttp-OkGo#236]
OkGo配置如下:
OkGo.init(this);
        try {
            OkGo.getInstance()
                    .setConnectTimeout(OkGo.DEFAULT_MILLISECONDS)
                    .setReadTimeOut(OkGo.DEFAULT_MILLISECONDS)
                    .setWriteTimeOut(OkGo.DEFAULT_MILLISECONDS)
                    .setCertificates();
        } catch (Exception e) {
            e.printStackTrace();
        }

在华为(刷MIUI 7.6.1.8, Android4.4.2)上进行OAuth认证的时候发生异常,但在模拟器7.0上没有问题.如下:
W/System.err: javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x750c3fa8: Failure in SSL library, usually a protocol error
W/System.err: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version (external/openssl/ssl/s23_clnt.c:744 0x750d46fd:0x00000000)

google了一下发现貌似4.4系统默认没有开启TLSv1.1 TLSv1.2的支持
http://stackoverflow.com/questions/29916962/javax-net-ssl-sslhandshakeexception-javax-net-ssl-sslprotocolexception-ssl-han
http://tarkrul.info/category/coding/android/

可是不知道怎么将解决方法跟okgo关联起来?

**Comment by santong** [comment]
同样的问题，请问解决了吗

**Comment by jeasonlzy** [comment]
okgo升级3.0，欢迎体验。。

**Comment by buttonXin** [comment]
我也遇到了同样的问题，就算使用3.0好像也不行啊...

**Comment by jeasonlzy** [comment]
如果有问题，可以参考上面给出的链接，或者 http://blog.csdn.net/qq_16666847/article/details/54092297 这个博客，去实现自己的SSLSocketFactory，okgo是基于okhttp的，所以你只需要配置好okhttp的SSLSocketFactory就行。。
