### ISSUE TITLE
如何updata HashMap<String,File> map

### ISSUE THREAD

**Issue by missZhaoXiong** [jeasonlzy/okhttp-OkGo#241]
how to updata map

**Comment by jeasonlzy** [comment]
没太明白？

**Comment by missZhaoXiong** [comment]
就是我想上传好多图片，但是每个图片对应的一个key上传

**Comment by jeasonlzy** [comment]
建议多看看文档和demo，里面都有方法   [https://github.com/jeasonlzy/okhttp-OkGo/wiki/OkGo](https://github.com/jeasonlzy/okhttp-OkGo/wiki/OkGo)
