### ISSUE TITLE
在6.0上设置缓存，读取时很慢

### ISSUE THREAD

**Issue by SweetCate** [jeasonlzy/okhttp-OkGo#242]
不知道Google对Android6.0上做了什么样的处理，在Android6.0上缓存的数据量比较大时，读取比较耗时。有没有什么好的解决方案？或者说自己开线程做缓存？

**Comment by jeasonlzy** [comment]
这个应该不是缓存的原因，读取缓存的过程就是一个查询数据库的过程，其实是很快的。。

**Comment by jeasonlzy** [comment]
okgo升级3.0，缓存模块也升级成 缓存策略，欢迎体验。。
