### ISSUE TITLE
OkGo下载一个文件出现尺寸变大和乱码问题

### ISSUE THREAD

**Issue by T-mans** [jeasonlzy/okhttp-OkGo#246]
http://jj-test.oss-cn-shanghai.aliyuncs.com/b2c%E5%95%86%E5%9F%8E%E8%A7%84%E5%88%92.docx

上面是出现问题的文件地址，可以用浏览器直接下载，文件大小是21k多。
这个文件地址使用OkGo的FileCallBack进行下载，文件总是变大很多（39k左右），而且打开后乱码。
最后我用原生OkHttp封装了一个下载，自己从Response里通过流进行读取文件才正确。
排查了半天，我没发现怎么在OkGo里面怎么解决这个问题。

**Comment by jeasonlzy** [comment]
可能是log的原因，你把初始化中的 debug 那行注释掉再试试。

**Comment by T-mans** [comment]
你说的没错，注释了debug配置后，文件可以正确的下载了。
暂时没时间研究这个源码，希望作者可以修复下这个bug。
毕竟没有debug还怎么调试
辛苦了

**Comment by yale8848** [comment]
这个问题解决了吗？

**Comment by jeasonlzy** [comment]
okgo升级3.0，已解决。欢迎使用。。
