### ISSUE TITLE
文件上传，参数出错

### ISSUE THREAD

**Issue by dengtuo** [jeasonlzy/okhttp-OkGo#250]
开发者你好，我今天用OKGo发现一个问题，我要上传图片，参数如下：
键：值
userID:0
token:*********************
files:<file>
然而当我用OkGo上传之后，通过抓包发现，格式变成了如下：
![这是抓包图](https://camo.githubusercontent.com/d260946f9124b75ede7a7e925fae5220fc5059c2/687474703a2f2f7778312e73696e61696d672e636e2f6d773639302f39636432636362316c7931666634777866316a34356a3230773330626b6161782e6a7067)

然后我的后台服务器通过key获取value，结果现在所有的key自动添加了一些东西。这个怎么办呢

**Comment by jeasonlzy** [comment]
这个是正常的，http协议就是这个格式。。
