### ISSUE TITLE
这个好的框架，是不是不维护了？

### ISSUE THREAD

**Issue by richfuns** [jeasonlzy/okhttp-OkGo#251]
都半年了，没有任何更新嘛，issues还不少

**Comment by androidscx** [comment]
维护很麻烦吧..............

**Comment by jeasonlzy** [comment]
issue看起来很多，但基本是不会用，属于bug的issue基本没有，没有更新是因为很稳定了。

目前还在维护，也准备了一个大版本更新，更新比较大，稍微有点滞后。

**Comment by jeasonlzy** [comment]
已更新3.0，欢迎使用。。
