### ISSUE TITLE
取消网络请求有问题

### ISSUE THREAD

**Issue by weilixing00** [jeasonlzy/okhttp-OkGo#257]
我递归调用网络请求，用new Handler()设置间隔1s，但是取消不掉，用Thread.sleep()就可以取消掉，请问这个可以修复吗

**Comment by weilixing00** [comment]
貌似只能取消主线程的请求？

**Comment by wxy520ll** [comment]
是的 取消请求有问题。。我也遇到了

**Comment by jeasonlzy** [comment]
取消是根据tag来的，检查你的tag是否一致。。
