### ISSUE TITLE
特殊wifi情况下网络返回结果类型有误

### ISSUE THREAD

**Issue by crazyxiong** [jeasonlzy/okhttp-OkGo#258]
如果连接的免费wifi需要手机注册，wifi连接成功用户不进行注册此时返回的类型出错是html的，没处理的情况下会直接崩溃,，希望在Response里面加上类型判断！type, "text"   subtype, "plain"

**Comment by jeasonlzy** [comment]
这是业务逻辑，框架不应该做这个逻辑的。。
