### ISSUE TITLE
StringCallback 返回字符串不能解析成json

### ISSUE THREAD

**Issue by fmfeggman** [jeasonlzy/okhttp-OkGo#261]
StringCallback 返回字符串使用gson的JsonParser不能识别是json对象，之前一直使用的是android-async-http解析的没问题，换成okhttp-OkGo就不能解析，okhttp-OkGo是不是对字符串做了一些转义处理导致解析失败？

**Comment by fmfeggman** [comment]
public void onSuccess(String json , Call call, Response response)
json = json.substring(1, json.length() - 1).replace("\\", "");
手工调整一下才能解析，不过这样也不是办法啊，这种错误也太低级了吧

**Comment by fmfeggman** [comment]
get方式有问题，post正常

**Comment by jeasonlzy** [comment]
这种转义字符串是服务端返回的，本地是不处理这种数据的，你拿到的json也是原始服务端给你的数据。所以，叫服务端别转义嘛。。要么你就自己处理下。。框架怎么知道需不需要转义呢。
