### ISSUE TITLE
AS2.3下打包报错，运行不报错

### ISSUE THREAD

**Issue by GanHuaLin** [jeasonlzy/okhttp-OkGo#265]
直接运行不会报错，打包的时候就报错。请问下这是什么原因呢?

Error:Execution failed for task ':app:transformClassesWithDexForRelease'.
> com.android.build.api.transform.TransformException: 
com.android.ide.common.process.ProcessException: 
java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: 
Error while executing java process with main class com.android.dx.command.Main with arguments 
{--dex --num-threads=4 --multi-dex --main-dex-list /Users/ganhualin/Documents/Remote/RemoteCare/app/build/intermediates/multi-dex/release/maindexlist.txt --output /Users/ganhualin/Documents/Remote/RemoteCare/app/build/intermediates/transforms/dex/release/folders/1000/1f/main /Users/ganhualin/Documents/Remote/RemoteCare/app/build/intermediates/transforms/jarMerging/release/jars/1/1f/combined.jar}

**Comment by wuconghui** [comment]
我的也是这情况，测试版不报错，正式打包就报错了

**Comment by boysHe** [comment]
我也是

**Comment by boysHe** [comment]
我的也是,怎么解决
