### ISSUE TITLE
NetworkOnMainThreadException

### ISSUE THREAD

**Issue by againTry** [jeasonlzy/okhttp-OkGo#267]
你好，非常感谢你开源的此项目，很好用，不过发现个错误，在我使用StringCallback时，我重写了onError方法，当我想把Response中返回的信息保存下来时，发现只能放在子线程去获取，不可以直接获取，因为OnError是在主线程执行的,不知道有没有简便的方法，本来想修改源码，将Response对象中的返回数据传递到onError方法中，即不传Response对象，但是比较麻烦，不知道是不是这样，望告知，感谢！

**Comment by jeasonlzy** [comment]
在convertSuccess中解析数据，这个方法在子线程，然后抛出异常，你抛的数据就会在onError中回调。。
