### ISSUE TITLE
 PostRequest为什么不设置upForm（Formbody formbody）方法？

### ISSUE THREAD

**Issue by changety** [jeasonlzy/okhttp-OkGo#268]
类似upString，upJson upbytes， 为什么PostRequst不添加一个类似的upForm方法？
还有一个疑问是，系统的FormBody的Media_Type 为什么不带charset？

**Comment by jeasonlzy** [comment]
有这个方法，只是不叫upForm，叫upRequestBody（）,  okhttp自带的可能认为国际通用的就是u8，默认就按u8来了，至于其他原因，得去问写的人。。
