### ISSUE TITLE
如果返回的是xml数据,

### ISSUE THREAD

**Issue by linjhak** [jeasonlzy/okhttp-OkGo#269]
是不是只能当文本方式处理啊,大神,json数据可以有Gson解析,xml数据只能用StringCallBack这个吗?

**Comment by pye52** [comment]
json还是xml返回来都是一个string，json要解析给gson，xml要解析也有相应的处理方式

**Comment by liuzheng9110** [comment]
参考 jsoncallback 自定义个 xmlcallback 或者直接用 stringcallback 再解析
