### ISSUE TITLE
能从Request对象中拿到Post请求带参数的完整url吗?

### ISSUE THREAD

**Issue by lyylock** [jeasonlzy/okhttp-OkGo#273]

**Comment by liuzheng9110** [comment]
同想知道

**Comment by jeasonlzy** [comment]
完整的url只能在请求时才拼接，如果想提前知道，可以使用内置的工具类，GetRequest的源码也有，如下：
![image](https://user-images.githubusercontent.com/13421975/27065070-ad068da8-502d-11e7-9e70-0725e72134d8.png)
