### ISSUE TITLE
廖神，我都等不及你放大招了。

### ISSUE THREAD

**Issue by Todyzhou** [jeasonlzy/okhttp-OkGo#274]
l

**Comment by Troll4it** [comment]
//Activity销毁时，取消网络请求
        unSubscribe();

想问下如果没有调用这个方法会出现什么问题,是爆OOM吗

**Comment by Todyzhou** [comment]
我觉得应该不是，只是网络请求继续发送，数据回来之后没有办法处理而已，还在研究学习

**Comment by jeasonlzy** [comment]
快啦快啦。。改动比较大。所以慢。。绝大部分已经完成了。。

**Comment by ayuhani** [comment]
看来是要有个大新闻

**Comment by jeasonlzy** [comment]
已更新3.0，欢迎使用
