### ISSUE TITLE
小米5 7.0系统，打开demo的新闻就直接崩了

### ISSUE THREAD

**Issue by ayuhani** [jeasonlzy/okhttp-OkGo#276]
![qq 20170607143114](https://user-images.githubusercontent.com/20321550/26865160-0fff7a86-4b8e-11e7-9b5b-fab7fd9f0c1a.png)

**Comment by ayuhani** [comment]
找到原因了，易源的api下架了。

**Comment by jeasonlzy** [comment]
okgo升级到 3.0， 换了api，感谢关注。。
