### ISSUE TITLE
onerror和onCacheError都已经覆盖了，为什么还会爆出错误，小白求指点

### ISSUE THREAD

**Issue by 1371030** [jeasonlzy/okhttp-OkGo#277]
W/System.err: com.lzy.okgo.exception.OkGoException: 服务器数据异常!
06-07 20:38:54.116 2377-2377/net.xianduadmin.app W/System.err:     at com.lzy.okgo.adapter.CacheCall$1.onResponse(CacheCall.java:155)
06-07 20:38:54.116 2377-2377/net.xianduadmin.app W/System.err:     at okhttp3.RealCall$AsyncCall.execute(RealCall.java:126)
06-07 20:38:54.116 2377-2377/net.xianduadmin.app W/System.err:     at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
06-07 20:38:54.116 2377-2377/net.xianduadmin.app W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
06-07 20:38:54.116 2377-2377/net.xianduadmin.app W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
06-07 20:38:54.116 2377-2377/net.xianduadmin.app W/System.err:     at java.lang.Thread.run(Thread.java:841)

**Comment by jeasonlzy** [comment]
这个异常是响应码 404 或者 500，详细检查你的url地址，然后看服务端是否有问题。。
