### ISSUE TITLE
建议改进execute(new SomeCallback)中parseResponse()的实现方法

### ISSUE THREAD

**Issue by moonmanbu** [jeasonlzy/okhttp-OkGo#283]
有的使用场景是后台特意返回携带参数的400或者404的响应体, 代表未找到资源或者找到的资源不符合要求, OkGo目前的处理方式有点一概化, 这是库中的代码: 

                //响应失败，一般为服务器内部错误，或者找不到页面等
                if (responseCode == 404 || responseCode >= 500) {
                    sendFailResultCallback(false, call, response, OkGoException.INSTANCE("服务器数据异常!"));
                    return;
                }

                try {
                    Response<T> parseResponse = parseResponse(response);
                    T data = parseResponse.body();
                    //网络请求成功，保存缓存数据
                    handleCache(response.headers(), data);
                    //网络请求成功回调
                    sendSuccessResultCallback(false, data, call, response);
                } catch (Exception e) {
                    //一般为服务器响应成功，但是数据解析错误
                    sendFailResultCallback(false, call, response, e);
                }

这样导致上述表述的功能无法实现, 携带的参数信息无法获取! 建议作者在这方面加以改进!

**Comment by moonmanbu** [comment]
研究了一下, 这样也可以, 继承一个Callback, 用一个字段保存response.body()的content的就可以了

**Comment by ypf168326** [comment]
我目前也是遇到和你一样的情况，就是服务端返回500错误，但是有错误信息，我在onError方法中，就是解析不到返回的错误，你是怎么改造的？ @moonmanbu @jeasonlzy
