### ISSUE TITLE
不支持Content-Disposition: attachment; filename*=

### ISSUE THREAD

**Issue by BenjaminChoou** [jeasonlzy/okhttp-OkGo#284]
看到源代码中只处理了Content-Disposition:attachment;filename=FileName.txt这种类型的。
比如这种Header就不能正确处理，希望能够解决一下，支持编码
Content-Disposition: attachment; filename*="UTF-8''3777-12281001%E6%9F%BB%E6%98%8E%E6%98%8E_Linux%E5%91%BD%E4%BB%A4%E8%A7%A3%E9%87%8A%E5%99%A8%E8%AE%BE%E8%AE%A1%E4%B8%8EShell%E6%9B%BF%E6%8D%A2%E5%AE%9E%E9%AA%8C%E6%8A%A5%E5%91%8A.pdf"

`    private static String getHeaderFileName(Response response) {
        String dispositionHeader = response.header(HttpHeaders.HEAD_KEY_CONTENT_DISPOSITION);
        if (dispositionHeader != null) {
            String split = "filename=";
            int indexOf = dispositionHeader.indexOf(split);
            if (indexOf != -1) {
                String fileName = dispositionHeader.substring(indexOf + split.length(), dispositionHeader.length());
                fileName = fileName.replaceAll("\"", "");   //文件名可能包含双引号,需要去除
                return fileName;
            }
        }
        return null;
    }`

**Comment by jeasonlzy** [comment]
okgo升级3.0 已经修复。欢迎使用。。
