### ISSUE TITLE
自己做的网盘，下载某些URL文件出现损坏

### ISSUE THREAD

**Issue by BenjaminChoou** [jeasonlzy/okhttp-OkGo#285]
http://clouddisk-1252089086.cossh.myqcloud.com/usercontent/5836-%E6%A8%A1%E6%9D%BF.docx
比如这个链接，用浏览器下载是正常的，但是用OkGo下载会出现损坏，该文件大小为15.1KB，下载完变成24.34KB

以下是该文件的下载日志，目前发现下载pptx,docx等office文件会出现此情况，看了下源码，也没怎么定位到错误原因，希望能给出解决方法，谢谢。

`
<-- 206 Partial Content http://clouddisk-1252089086.cossh.myqcloud.com/usercontent/5836-%E6%A8%A1%E6%9D%BF.docx (152ms）

 	Content-Range: bytes 0-15479/15480
 	Content-Type: application/vnd.openxmlformats-officedocument.wordprocessingml.document
 	Content-Disposition: attachment; filename*="UTF-8''5836-%E6%A8%A1%E6%9D%BF.docx"
 	Content-Language: zh-CN
 	ETag: baacf94540b74fb8eb746fbf1403095273b58031
 	x-cos-object-type: normal
 	Accept-Ranges: bytes
 	Last-Modified: Sat, 10 Jun 2017 22:52:36 GMT
 	Content-Length: 15480
`

**Comment by jeasonlzy** [comment]
这个和 okgo 的debug中的 HttpLoggingInterceptor 的编码问题，关了debug就好了。。
