### ISSUE TITLE
获取全部下载任务

### ISSUE THREAD

**Issue by alienzh** [jeasonlzy/okhttp-OkGo#286]
看源码中下载任务全部是保存在数据库中的，请问能开放下查询所有已经完成任务的方法么？
我现在是在自己表中保存一份，监听downlistener，下载完成后更改我自己表中状态。
但我发现有时候监听有问题，获取不到。

**Comment by jeasonlzy** [comment]
okgo 升级到 3.0，实现了你的功能。。欢迎使用。。
