### ISSUE TITLE
cookie可以绑定url而不是host吗

### ISSUE THREAD

**Issue by a154225859** [jeasonlzy/okhttp-OkGo#287]
cookie可以绑定url而不是host吗
比如http://www.xxxx.com/123和http://www.xxxx.com/456
cookie是不一样的 但自动管理的cookie两个url取出来的是同样的

**Comment by jeasonlzy** [comment]
内置的cookie是这个管理策略，不过okgo是支持自定义cookie管理的，[详细参考文档](https://github.com/jeasonlzy/okhttp-OkGo/wiki/Cookie#%E8%87%AA%E5%AE%9A%E4%B9%89cookie%E7%AE%A1%E7%90%86%E7%AD%96%E7%95%A5)
