### ISSUE TITLE
作者需要考虑一下以前的版本的完整，今天构建项目，回调的包已经没有了

### ISSUE THREAD

**Issue by firefecker** [jeasonlzy/okhttp-OkGo#294]
作者需要考虑一下以前的版本的完整，今天构建项目，回调的包已经没有了

**Comment by jeasonlzy** [comment]
加群看公告，报错可以用以前的老版本，新版本改动很大，所以没兼容，更多的时候，抛弃以前的老代码，使用新代码才能保持工程的整洁和健壮是吧，小改动是会兼容的。。
