### ISSUE TITLE
minSdkVersion为什么改成16了？

### ISSUE THREAD

**Issue by 1079107009** [jeasonlzy/okhttp-OkGo#296]

**Comment by jeasonlzy** [comment]
失误了。这两天修一波bug，顺便把版本号改回14，发个小版本。。

**Comment by 1079107009** [comment]
minSdkVersion rootProject.ext.libMinSdkVersion =14，为什么我这边是15却不行，提示
Manifest merger failed : uses-sdk:minSdkVersion 15 cannot be smaller than version 16 declared in library [com.lzy.net:okgo:3.0.0]

**Comment by beginWith** [comment]
大哥 能不能修改回14呢?我这边这个错修改了好多回也不行 能不能现在就修改一下呀?

**Comment by jeasonlzy** [comment]
你把你主项目app的最小版本号先改到16，其他哪都不用改了，然后这两天我会发个小版本，到时候用新的，在把你主项目的最小版本号改回去就行了。。

**Comment by beginWith** [comment]
我不能改自己的最低版本 报了一大堆错...没事 我直接使用上一个版本就是了 希望大哥你可以解决这个问题吧 过几天我再更新为最新的版本就可以了

**Comment by jeasonlzy** [comment]
okgo 3.0.1 版本发布，欢迎使用。该问题已解决。
