### ISSUE TITLE
太坑了 

### ISSUE THREAD

**Issue by chain911** [jeasonlzy/okhttp-OkGo#297]
我引用时候是用+默认引用最新版本  本来昨天还可以跑的项目突然今天报错：Error:Execution failed for task ':app:processBaiduDebugManifest'. > Manifest merger failed with multiple errors, see logs 简直莫名其妙，网上找解决办法，都说缺少一些重要组件没有下载，我就去更新studio了，还得用代理，墨迹半天还不能解决，我就把minSdkVersion改高，clean不报错了，但是okgo有关的全报错，我来github一看，尼玛 更新版本了。更新版本api全变了，坑啊。哪有更新版本把api都改了的，这要升级版本，所有的网络请求都得改一遍，逗我呢

**Comment by jeasonlzy** [comment]
OkGo升级到3.0，本次升级为不兼容升级，和以前2.1.4的版本差距非常大，我已经写了详细的文档，欢迎大家尝试，积极反馈bug！

如果使用老版本，参看以前的文档：
https://github.com/jeasonlzy/okhttp-OkGo/tree/v2.1.4 
同时将版本号+，固定为：
compile 'com.lzy.net:okgo:2.1.4'
compile 'com.lzy.net:okrx:0.1.2' 
compile 'com.lzy.net:okserver:1.1.3' 

欢迎使用okgo3.0 新版：
项目地址：https://github.com/jeasonlzy/okhttp-OkGo
文档地址：https://github.com/jeasonlzy/okhttp-OkGo/wiki
demo下载：http://7xss53.com1.z0.glb.clouddn.com/file/okgo_v3.0.0.apk

**Comment by jeasonlzy** [comment]
不需要你改任何代码，使用老版本不升级就行了。。

**Comment by YouCii** [comment]
自己设计的不好还要怪三方库么？不能自己再封一层？

**Comment by chain911** [comment]
不懂别BB行么 API变了懂吗？跟你封装几次有屁关系，你自己再封装100层，底层还是用别人的，别人这个API都没了，你调用毛线，弱智总爱瞎BB，我只是吐槽一下，有几个版本升级直接换API的，对使用者造成不必要的麻烦，人家版主自己都没说啥，只是studio报错很奇怪，不容易发现错误。

**Comment by YouCii** [comment]
所以说你傻逼啊，你要是封了一层还用“所有的网络请求都得改一遍”？只改你的封装不就行了，真是人傻脾气大

**Comment by chain911** [comment]
所以说你傻逼 不懂装你麻痹呢 你封装的特么的改不是改？给你逼脸了，你特么给老子封装一个试试，回调StringCallBack都没了，你特么不懂就闭嘴，臭傻逼，总有你这样的爱装逼，去你妈的

**Comment by chain911** [comment]
所以说你傻逼 不懂装你麻痹呢 你封装的特么的改不是改？给你逼脸了，你特么给老子封装一个试试，回调StringCallBack都没了，初始化以及全局配置好多API都没了，你特么不懂就闭嘴，臭傻逼，总有你这样的爱装逼，去你妈的，你这种标准的说你是狗你就上去咬人的家伙

**Comment by YouCii** [comment]
第三方的东西很有可能会变，它自己本身不变也有可能你的CTO要你改，你封装一个OkSetting，一个BaseRequst和一个BaseCallBack，要比你所有的网络请求都改一遍要好的太多，看你这谁也不服的样子，我也说不服你，你就用你自己的一套慢慢捣鼓吧

**Comment by chain911** [comment]
你自己好好想想 BaseCallBack，只是抽象的，具体某个请求用什么CallBack还是看情况定的，怎么可能改一个Base就完事了。比如你的BaseCallBack，一个接口用的StringCallBack,一个是jsoncallback还有一些别的，难道不用变么？？只改一个Base就解决了？不是谁也不服，就好比问起Java三大特性封装继承多态，都会说，问你具体什么是封装继承多态知道的就少了，能举出例子灵活运用的又少了一部分，别一遇到问题就会说封装啊，再封装一次，说的简单，你给个Demo我看看你怎么封装的我学习学习。如果确实可行，我跟你道歉

**Comment by YouCii** [comment]
`package com.youcii.mvplearn.base;

import android.content.Context;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.widget.Toast;

import com.alibaba.fastjson.JSON;
import com.lzy.okgo.callback.AbsCallback;
import com.lzy.okgo.convert.FileConvert;

import java.io.File;
import java.io.IOException;
import java.lang.reflect.ParameterizedType;

import okhttp3.Call;
import okhttp3.Response;

/**
 * Created by Administrator on 2017/4/25.
 */

public abstract class BaseCallBack<T> extends AbsCallback<T> {
	protected Context context;
	protected String destFileDir;
	protected String destFileName;

	public BaseCallBack(Context context) {
		this.context = context;
	}

	public BaseCallBack(Context context, String destFileDir, String destFileName) {
		this.context = context;
		this.destFileDir = destFileDir;
		this.destFileName = destFileName;
	}

	@Override
	public void onSuccess(T t, Call call, Response response) {
		String json = null;
		try {
			json = response.body().string();
		} catch (IOException e) {
			e.printStackTrace();
			onError(call, response, new Exception("网络请求失败"));
			return;
		}

		if (t instanceof BaseResponse) {
			Object responseObject;
			try {
				responseObject = JSON.parseObject(json, getTClass());
			} catch (Exception e) {
				onError(call, response, new Exception("回调格式错误"));
				return;
			}

			if (!((BaseResponse) responseObject).status.equals("success")) {
				onError(call, response, new Exception("网络请求失败：" + ((BaseResponse) responseObject).msg));
				return;
			}

			onSuccess(responseObject);
		} else if (t instanceof String) {
			onSuccess(json);
		} else if (t instanceof Bitmap) {
			onSuccess(BitmapFactory.decodeStream(response.body().byteStream()));
		} else if (t instanceof File) {
			onSuccess(convertToFile(response));
		}
		response.close();
	}

	protected abstract void onSuccess(Object response);

	@Override
	public void onError(Call call, Response response, Exception e) {
		super.onError(call, response, e);

		if (response.body().toString().contains("ConnectTimeoutException"))
			Toast.makeText(context, "服务器超时无响应", Toast.LENGTH_SHORT).show();
		else
			Toast.makeText(context, e.toString(), Toast.LENGTH_SHORT).show();
	}

	// 反射获取T.class
	private Class<T> getTClass() {
		Class<T> tClass = (Class<T>) ((ParameterizedType) getClass().getGenericSuperclass()).getActualTypeArguments()[0];
		return tClass;
	}

	// 返回file
	private File convertToFile(Response response) {
		FileConvert convert = new FileConvert(destFileDir, destFileName);
		convert.setCallback(this);
		File file = null;
		try {
			file = convert.convertSuccess(response);
		} catch (Exception e) {
			e.printStackTrace();
		}
		response.close();
		return file;
	}
}
`

**Comment by jeasonlzy** [comment]
额，这个别吵哈，首先我也考虑到api兼容的问题，但是注意版本号的命名，既然大版本号都换成3了，肯定是有大改动是吧，就像你们自己的项目一样，重大改动才会更新大版本号。而大版本号的改动一般都是不兼容升级的，开源库也是这样，举个例子：
1. ButterKnife 7.x -> ButterKnife 8.x
2. EventBus 2.x -> EventBus 3.x
3. okhttp 2.x -> okhttp 3.x
4. RxJava 1.x -> RxJava 2.x

还有很多哈， 我就说几个常见的。所以偶尔出现api的不兼容升级也在所难免。当然，对于小版本升级，我肯定会努力做到最大限度的兼容的。

其次， @YouCii 的写法和做法也是很值得推荐的，其实我也是鼓励大家这么定义一个自己的Callback基类的，既方便了自己的业务逻辑，也当以后出现api改动的时候方便升级，至少只改几个有限的基类就可以了，工作量大大减少。

这里给大家带来不便，敬请谅解。

**Comment by Pgrammerybj** [comment]
我非常的赞成 @YouCii 的写法和作者的态度，很多的东西不要照搬，用之前先看文档说明！！！@chain911 本来就用人家的轮子，态度稍微的好一些嘛，这个OKGo本公司用的飞起，棒棒的！！！

**Comment by guojunliang** [comment]
支持@YouCii的做法，这样改动起来就方便多了，以后不管第三方框架怎么修改，都不用改业务代码了

**Comment by chain911** [comment]
嗯嗯 我的问题 我错了 @YouCii 有没有Demo发我一份15142399375@yeah.net 我学学 OkSetting，BaseRequst和一个BaseCallBack，看看具体怎么使用的

**Comment by YouCii** [comment]
OkSetting就放初始化的部分，比如
`        
OkGo.init(this);
OkGo.getInstance().setConnectTimeout(10000);
`
BaseRequst是回调 json 解析的基类Bean，几个公共的参数比如code、msg等放在这里面，每个请求的不同requst都继承BaseRequst，只写自己独有的参数。

**Comment by xiaolongwuhpu** [comment]
@YouCii  顺便发我一份,参考一下,谢谢   longwuhpu@163.com

**Comment by 1371030** [comment]
@YouCii 麻烦发一份学习，谢谢！1371030@qq.com

**Comment by chenzixue** [comment]
@YouCii 能否发一份BaseRequest，在封装作者的okgo的时候遇到了一些问题，谢谢 czx525363859@163.com

**Comment by YouCii** [comment]
可以看看我github上LearnApp的登录部分 @chenzixue
