### ISSUE TITLE
请求数据回调接口中的onError()方法获取属性值时出现NullPointerException

### ISSUE THREAD

**Issue by xiao91** [jeasonlzy/okhttp-OkGo#298]
OkGo.<String>get(url)
               .tag(this)
               .execute(new StringCallback() {
                   @Override
                   public void onSuccess(Response<String> response) {
                       Log.d(TAG, "onSuccess：" + response.body());
                   }

                   @Override
                   public void onError(Response<String> response) {
                       super.onError(response);
                       Log.d(TAG, "onError():code=" + response.code());
                   }
               });
当获取code时报异常java.lang.NullPointerException: Attempt to invoke virtual method 'int okhttp3.Response.code()' on a null object reference；
当获取response.body()时，是null，获取其他属性值也会报NullPointerException，请查看响应体的包装类Response，有一个属性private okhttp3.Response rawResponse，请检查该对象中是否有值。

**Comment by jeasonlzy** [comment]
okgo 3.0.1 版本发布，欢迎使用。该bug已修复。。

**Comment by alienzh** [comment]
我用的3.0.1，关闭网络，启动app，没有回调onError

**Comment by whj-sky** [comment]
我用的3.0.4
 OkGo.<String>get(signedUrl).execute(new StringCallback() {
@override
public void onSuccess(com.lzy.okgo.model.Response<String> response) {
Log.d(TAG, "onSuccess：" + response.body());
}

               @Override
               public void onError(com.lzy.okgo.model.Response<String> response) {
                   super.onError(response);
                Toast.makeText(getContext(), "获取信息失败", Toast.LENGTH_SHORT).show();
               }
           });


在  super.onError(response);  这一行报错

java.lang.NullPointerException
Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference

这个是偶尔出现  我还没找出规律
