### ISSUE TITLE
上传界面的进度不变，一直显示为0

### ISSUE THREAD

**Issue by BeforeFuture** [jeasonlzy/okhttp-OkGo#299]
先添加上传任务，之后会发现上传界面的进度不变，一直显示为0，
等待约5秒钟左右，会直接toast上传成功，进度条从0直接跳到100；
不是因为文件太小速度太快，我上传的文件都是9M左右的图片，
已经测试好几次，而且用了不同的Android手机，均出现不显示实时进度的情况。

**Comment by jeasonlzy** [comment]
okgo 3.0.1 版本发布，欢迎使用。该bug已修复。。
