### ISSUE TITLE
OkDownload.restore(DownloadManager.getInstance().getDownloading())读不到数据

### ISSUE THREAD

**Issue by alienzh** [jeasonlzy/okhttp-OkGo#301]
实际上文件已经下载了，但是数据库中读不到数据OkDownload.restore(DownloadManager.getInstance().getDownloading())
OkDownload.restore(DownloadManager.getInstance().getFinished()) 都读不到数据

**Comment by jeasonlzy** [comment]
要先 register ,才能 start， register 是写入数据库的过程。。
