### ISSUE TITLE
PersistentCookieStore这个类没了？

### ISSUE THREAD

**Issue by wuyang049679** [jeasonlzy/okhttp-OkGo#302]

**Comment by jeasonlzy** [comment]
OkGo升级到3.0，本次升级为不兼容升级，和以前2.1.4的版本差距非常大，我已经写了详细的文档，欢迎大家尝试，积极反馈bug！

如果使用老版本，参看以前的文档：
https://github.com/jeasonlzy/okhttp-OkGo/tree/v2.1.4
同时将版本号+，固定为：
compile 'com.lzy.net:okgo:2.1.4'
compile 'com.lzy.net:okrx:0.1.2'
compile 'com.lzy.net:okserver:1.1.3'

欢迎使用okgo3.0 新版：
项目地址：https://github.com/jeasonlzy/okhttp-OkGo
文档地址：https://github.com/jeasonlzy/okhttp-OkGo/wiki
demo下载：http://7xss53.com1.z0.glb.clouddn.com/file/okgo_v3.0.0.apk

**Comment by ollie100** [comment]
你好，目前项目用你的2.1.4的版本，建议升级到3.0版本吗？

**Comment by jeasonlzy** [comment]
okgo 3.0.1 版本发布，欢迎使用。修复了一些bug，建议使用3.0.1 版本。。
