### ISSUE TITLE
初始化的问题

### ISSUE THREAD

**Issue by zhuhonglei** [jeasonlzy/okhttp-OkGo#306]
最新版发现的问题:
在Application里初始化的时候,不写OkHttpClient.Builder builder = new OkHttpClient.Builder();不调用setCacheMode(CacheMode.NO_CACHE)设置缓存,请求的时候就会报错,建议给缓存和okHttpClient默认值

**Comment by jeasonlzy** [comment]
是的。3.0.1 版本已发布。 该问题已经修复。。

**Comment by tomasky** [comment]
为什么一定要在Application里面初始化?

**Comment by jeasonlzy** [comment]
只是建议。因为初始化一次就够了。。
