### ISSUE TITLE
下载列表获取到的数量一直为0

### ISSUE THREAD

**Issue by a154225859** [jeasonlzy/okhttp-OkGo#307]
添加了很多任务 并且重复添加也提示已经在队列 但获取到的列表是0
GetRequest<File> request = OkGo.get(urls);
request.headers(header);
OkDownload.request(bean.getUrl(),request)
.priority(1)
.extra1(bean)
.start();

DownloadManager.getInstance().getAll();
这样获取的一直是0

**Comment by jeasonlzy** [comment]
要先register(), 然后start(),  使用3.0.1 版本，如果不调用 register() 会给出异常提示。。详细也可以看demo。

**Comment by a154225859** [comment]
是不是可以把register里面的 DownloadManager.getInstance().replace(progress);放到start里
有时候只是想添加一个后台下载任务 并不需要进度回调

**Comment by a154225859** [comment]
或者提供一个无参的register

**Comment by jeasonlzy** [comment]
不可以，register 和 start 功能不一样，不是所有register的地方都需要start的，可以只register但是不start，但是要start必须register。
