### ISSUE TITLE
webservice返回数据包含map的时候怎么解析

### ISSUE THREAD

**Issue by wyy0567** [jeasonlzy/okhttp-OkGo#308]

**Comment by jeasonlzy** [comment]
1. 首先什么服务器不重要，okgo只是个网络请求框架，他不在乎也不需要知道你是什么服务器
2. okgo做的唯一的事情就是按你的要求请求服务器，然后把服务器的数据返回来给你
3. 至于数据是什么格式，在怎么解析，okgo使用接口或者回调的方式让用户自己去解析，这个并不是okgo干的事情
4. 为了方便，okgo内置了一些简单的数据解析方法，比如返回string，bitmap，file等等，但是其他的复杂的数据，还需要用户自己来做。
5. 至于你说的返回map是什么，我并不太清除，这个解析过程应该是你和服务端商量的，常用的json类型的格式的自定义封装，我在文档中都有写到，你的特殊格式请参照该文档自行改写。

[https://github.com/jeasonlzy/okhttp-OkGo/wiki/JsonCallback](https://github.com/jeasonlzy/okhttp-OkGo/wiki/JsonCallback)
