### ISSUE TITLE
全局的单个任务的下载监听3.0版本为什么去掉，需要全局监听并对每个文件下载完时做处理怎么解决呢？

### ISSUE THREAD

**Issue by chordw** [jeasonlzy/okhttp-OkGo#310]

**Comment by jeasonlzy** [comment]
并没有去掉，简写了。代码如下：

OkDownload.addOnAllTaskEndListener() ;
OkDownload.removeOnAllTaskEndListener();

OkUpload.addOnAllTaskEndListener() ;
OkUpload.removeOnAllTaskEndListener();

**Comment by chordw** [comment]
谢谢。
OkDownload.addOnAllTaskEndListener() 设置后只有这一个回调方法void onAllTaskEnd();而且里面没有参数。
我需要的是在全局监听每个任务的下载完成，而不是当所有的任务下载完成后的事件监听。可以解决吗？

**Comment by jeasonlzy** [comment]
globeDownloadListener 完全可以使用DownloadListener替代，使用一个基类的DownloadListener，抽取代码即可。。
