### ISSUE TITLE
onError 无网络时候，有时候不回调

### ISSUE THREAD

**Issue by alienzh** [jeasonlzy/okhttp-OkGo#311]
我用的3.0.1，关闭网络，启动app，没有回调onError

**Comment by alienzh** [comment]
若是刚打开程序时候有网，后来没有网络，onError会执行，但是若一开始就没有网络则不会执行

**Comment by alienzh** [comment]
经反复测试，com.lzy.okgo.cache.policy.RequestFailedCachePolicy  的onError()方法中，有时候cacheEntity不为空  就调用mCallback.onCacheSuccess(cacheSuccess); mCallback.onFinish();

**Comment by jeasonlzy** [comment]
这个和缓存模式有关，一般来说是需要 onCacheSuccess() 中调用 onSuccess() 方法的，因为他们的逻辑是一样的。。关于这个调用顺序，也是正常的，详细文档里面都有描述： [缓存回调顺序介绍](https://github.com/jeasonlzy/okhttp-OkGo/wiki/Cache#%E5%9B%9E%E8%B0%83%E9%A1%BA%E5%BA%8F)

**Comment by alienzh** [comment]
明白了，3Q
