### ISSUE TITLE
put 和 delete 请求时候 Content-length 为0  请求不成功

### ISSUE THREAD

**Issue by onebee** [jeasonlzy/okhttp-OkGo#312]
![518119c5-10f2-4b3c-b5d6-de668883bfeb](https://user-images.githubusercontent.com/8468626/27253629-e5ae3dd8-53aa-11e7-8118-bd2b4097d6cf.png)
<img width="989" alt="qq20170617-221853 2x" src="https://user-images.githubusercontent.com/8468626/27253638-f701ec2e-53aa-11e7-9fda-ab92163f4c50.png">

**Comment by jeasonlzy** [comment]
这个错误并不是网络框架返回的，而是你们服务端返回的，详细原因，还需要问你们服务端。。和content-length好像并没有什么关系。

**Comment by onebee** [comment]
put  和 delete  时候  Content-Type 怎么修改呢 .想修改成 application/json

**Comment by jeasonlzy** [comment]
详细看文档。。所有问题都可以在文档里面找到答案： [上传JSON类型的文本](https://github.com/jeasonlzy/okhttp-OkGo/wiki/OkGo#7%E4%B8%8A%E4%BC%A0json%E7%B1%BB%E5%9E%8B%E7%9A%84%E6%96%87%E6%9C%AC)
