### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by Troll4it** [jeasonlzy/okhttp-OkGo#313]
再看大佬的demo使用OkRx2时每个网络连接都写了这几句，是否考虑封装下
.converter(new JsonConvert<LzyResponse<ServerModel>>() {})//
                .adapt(new ObservableBody<LzyResponse<ServerModel>>())//
                .subscribeOn(Schedulers.io())//

**Comment by Troll4it** [comment]
您好，中间还需要自己去导入rxandroid的包，不懂rx的新手都不知道有这回事，希望放在框架中

**Comment by jeasonlzy** [comment]
1. 首先，作为一个三方库，是要最小化自己对其他库的依赖，既然没有使用rxandroid，何必放入库中
2. 作为一个想使用okrx的用户来说，连RxAndroid都不知道要导入，还是建议不要使用okrx了，或者rxjava了
3. 那几句共性代码就像你用原生的okhttp或者HttpUrlConnection一样，每次都要写同样的几句代码一样，过度的封装只会让框架失去灵活性而变成定制性的框架，你说的那几句代码，这必然是应该让用户自己去做的，而不应该放入库中的。

感谢你的建议和认可。

**Comment by Troll4it** [comment]
按照你说的，在重新Convert类时，需要导入 compile 'com.readystatesoftware.chuck:library:1.0.4'，这个就是依赖其他人的库。。。大佬，我首先申明我说的这些并不是像有些人一样去指责什么，或者表示自己有多厉害，说实在的我就是一个新手菜鸟，我这些只是想表达自己的想法，可能方式有点不对，想让这个第三库变得越来越完善，希望你能理解，谢谢

**Comment by jeasonlzy** [comment]
这个Chuck依赖库是在demo中加的，库中并没有加，我只是放在demo中说需要的话可以加上，但其实我的代码是注释掉的。

**Comment by jeasonlzy** [comment]
提供这个dem的意思就是，库只需要一个  OkHttpClient就可以，至于你是怎么构建的，用了什么其他库，我都不关心，我只需要要一个 OkHttpClient 对象，包括我内置提供的 log， https，cookie相关的类和方法，完全可以不用，自己写一套，只是内置的基本满足需要了，所以用起来方便。
