### ISSUE TITLE
上传文件总是失败

### ISSUE THREAD

**Issue by roger66** [jeasonlzy/okhttp-OkGo#314]
同样的代码用2.1.4的版本上传文件是成功的

**Comment by jeasonlzy** [comment]
log 呢？

**Comment by roger66** [comment]
你的log是哪一个？

**Comment by roger66** [comment]
上传进度回调出来到了100，然后就走到了onError里面返回time out

**Comment by roger66** [comment]
06-19 15:21:30.161 17362-17662/com.huanlv.plus360 I/OkGo: --> POST https://graph-video.facebook.com/v2.9/310568459380536/videos http/1.1
06-19 15:21:30.161 17362-17662/com.huanlv.plus360 I/OkGo: 	Accept-Language: zh-CN,zh;q=0.8
06-19 15:21:30.161 17362-17662/com.huanlv.plus360 I/OkGo: 	User-Agent: Mozilla/5.0 (Linux; U; Android 7.0; zh-cn; FRD-AL10 Build/HUAWEIFRD-AL10) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30
06-19 15:21:30.161 17362-17662/com.huanlv.plus360 I/OkGo: 	Content-Length: 8748219
06-19 15:21:30.162 17362-17662/com.huanlv.plus360 I/OkGo:  
06-19 15:21:30.162 17362-17662/com.huanlv.plus360 I/OkGo: 	body: maybe [file part] , too large too print , ignored!
06-19 15:21:30.162 17362-17662/com.huanlv.plus360 I/OkGo: --> END POST
06-19 15:21:48.548 17362-17662/com.huanlv.plus360 I/OkGo: <-- HTTP FAILED: java.net.SocketTimeoutException: timeout

**Comment by jeasonlzy** [comment]
如果你使用了Chuck，请关闭，还不行，请关闭所有的拦截器，包括okgo自己的，再试试。
