### ISSUE TITLE
OkRx2的缓存功能只能用Response才能实现吗?

### ISSUE THREAD

**Issue by ppg408331701** [jeasonlzy/okhttp-OkGo#319]
我自定义的实体类是没有isFromCache这个属性的

比如 .adapt(new ObservableBody<LzyResponse<ServerModel>>())//这种该如何使用缓存

**Comment by jeasonlzy** [comment]
1. 不是你定义的实体类没有这个属性，而是你用的是ObservableBody这个类，如果你使用ObservableResponse不就有了，详细看文档：[CallAdapter介绍](https://github.com/jeasonlzy/okhttp-OkGo/wiki/OkRx#calladapter%E8%AF%A6%E8%A7%A3)
2. 如果你使用ObservableBody，不是没有缓存，而是无法区分当前的数据是来自缓存还是网络，当然如果你不关心来自哪里，那么一点影响没有。。比如缓存模式  FIRST_CACHE_THEN_REQUEST ，会调用两次onNext方法，一般第一次是缓存回调的，第二次是网络回调的。这样你就不好区分了。如果你使用ObservableResponse这个类，那么就可以直接区分了，所以看你需求了。。
