### ISSUE TITLE
你好 关于加密的问题

### ISSUE THREAD

**Issue by zilingyao** [jeasonlzy/okhttp-OkGo#322]
我看了关于加密的callback 都是直接给参数加密  而我们的项目是把参数分别加密，然后转换json然后在加密装换为字符串 上传服务器，现在想在callback做统一加密解密，不知道怎么把string字符串直接上传，
求指点下 ，谢谢！
![image](https://user-images.githubusercontent.com/16448548/27370222-306eea44-568e-11e7-9ed1-304cb233724c.png)

**Comment by jeasonlzy** [comment]
这个并没有什么难度，在onStart方法中在传一次参就行了。

**Comment by zilingyao** [comment]
params.put("" , data) 吗？但是这样会多出来一个=

**Comment by zilingyao** [comment]
大神 实在是搞不定 求几分钟详细指点下

**Comment by jeasonlzy** [comment]
在onStart中直接把你得到的值  upString
