### ISSUE TITLE
多任务下载，重下时如果tag相同会报空指针异常

### ISSUE THREAD

**Issue by buildcodeworld** [jeasonlzy/okhttp-OkGo#327]
//这里第一个参数是tag，代表下载任务的唯一标识，传任意字符串都行，需要保证唯一,我这里用url作为了tag
            OkDownload.request(apk.url, request)//
                    .priority(apk.priority)//
                    .extra1(apk)//
                    .register(new LogDownloadListener())//
                    .start();
            adapter.notifyDataSetChanged();

**Comment by jeasonlzy** [comment]
详细的异常呢？具体代码怎么写的？
