### ISSUE TITLE
能否把多个异步网络请求然后把结果糅合到一块 的方法

### ISSUE THREAD

**Issue by onebee** [jeasonlzy/okhttp-OkGo#328]

**Comment by jeasonlzy** [comment]
okgo 和其他所有网络框架一样，只提供请求网络的方法，至于怎么柔和到一起，属于业务逻辑，不在框架的范畴

okrx也是一样，只是将网络请求包装成Observable对象，具体的柔和一起，还是依靠的rxjava实现，也并不是框架实现的

所以以上两点要搞清楚。
