### ISSUE TITLE
文件下载的后缀名问题

### ISSUE THREAD

**Issue by shaycormac** [jeasonlzy/okhttp-OkGo#330]
你好，请问可不可以修改一下下载文件后缀名的策略呢，因为我这边下载文件，响应头中没有文件名，以第二种方式，即请求url的后缀名作为文件名字，因为带有汉字，所以下载下来的是URL编码后的一串字符，如%E%2B.doc。我已经通过重新继承AbsCallback抽象类,重新实现Converter接口，以及重新写HttpUtils里面的那个方法，对url进行Url.decode解码解决这个问题，顺便给你提一下自己的想法，谢谢~~

**Comment by jeasonlzy** [comment]
ok，感谢提出， 我会考虑将文件名进行一次 decode
