### ISSUE TITLE
我加了网络拦截器    .addInterceptor(new MInterceptor(getApplicationContext()))    然后下载的时候不推送进度了，我要怎么把进度找回来

### ISSUE THREAD

**Issue by xiaobaoCat** [jeasonlzy/okhttp-OkGo#331]

**Comment by xiaobaoCat** [comment]
拦截器中对响应做了判断，判断登录是否超时，超时重新登录后再发起请求

**Comment by xiaobaoCat** [comment]
呃呃呃，单独对下载的请求设置OkHttpClient，才想到。

其他请求我加了那个网络拦截器会有其他的影响吗？

**Comment by jeasonlzy** [comment]
详细是和你设置的拦截器的写法有关。。

**Comment by xiaobaoCat** [comment]
能帮我看下嘛：

 public Response intercept(final Chain chain) throws IOException {
        Request request = chain.request();
   
        Response response = chain.proceed(request);
        ResponseBody responseBody = response.body();
        BufferedSource source = responseBody.source();
        source.request(Long.MAX_VALUE);
        String responseString = source.buffer().clone().readString(Charset.defaultCharset());

        // TODO 判断是否登录超时
        try {
            JSONObject json = new JSONObject(responseString);
            String code=json.optString("code");
            String msg=json.optString("msg");
            if ("2".equals(code)){
                //说明登录超时了，需要重新登录
                Log.e("登录过期","重新登录");
                String telno=(String) SPFUtils.get(mContext,"telno","");
                String passwd=(String)SPFUtils.get(mContext,"passwd","");
                //创建登录的请求Request
                Request loginRequest = new Request.Builder()
                        .url(Constants.BaseUrl+"find_money/userLogin?"
                                +"telno="+telno
                                +"&passwd="+passwd
                                +"&imei="+ PhoneIntoUtil.getDeviceId(mContext)
                                +"&deviceToken="+ PushAgent.getInstance(AApplication.getInstance()).getRegistrationId())
                        .build();

                //登录的请求Request获取登录的响应，再根据响应判断再次登录是否成功
                Response loginResponse = chain.proceed(loginRequest);
                BufferedSource loginSource = loginResponse.body().source();
                loginSource.request(Long.MAX_VALUE);
                String loginResponseString = loginSource.buffer().clone().readString(Charset.defaultCharset());
                try {
                    JSONObject loginJson = new JSONObject(loginResponseString);
                    String loginCode=loginJson.optString("code");
                    if ("0".equals(loginCode)){
                        //重新登录成功,再次发起请求
                        Log.e("登录过期","重新登录成功,再次发起请求");
                        //保存用户信息
                        UserInfoUtil.savedUserInfo(loginResponseString);
                        try{
                            response = chain.proceed(request);
                        }catch(Exception e){
                        }
                    }else{
                        //重新登录失败,则请求完成,此时可以提示用户主动去登录
                        Log.e("登录过期","重新登录失败");
                    }
                } catch (JSONException e) {
                    e.printStackTrace();
                }
            }
        } catch (JSONException e) {
            e.printStackTrace();
        }
        return response;
    }
