### ISSUE TITLE
只要是在下载列表中暂停，然后在开始下载，就会出现下载异常，下载进度超过百分百，优先级高！！！

### ISSUE THREAD

**Issue by leigejiayou** [jeasonlzy/okhttp-OkGo#332]
06-23 11:26:32.834 19359-19359/com.lzy.demo W/System.err: com.lzy.okgo.exception.OkGoException: breakpoint file has expired!
06-23 11:26:32.836 19359-19359/com.lzy.demo W/System.err:     at com.lzy.okserver.download.DownloadTask.run(DownloadTask.java:308)
06-23 11:26:32.837 19359-19359/com.lzy.demo W/System.err:     at com.lzy.okserver.task.PriorityRunnable.run(PriorityRunnable.java:35)
06-23 11:26:32.837 19359-19359/com.lzy.demo W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
06-23 11:26:32.837 19359-19359/com.lzy.demo W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
06-23 11:26:32.837 19359-19359/com.lzy.demo W/System.err:     at java.lang.Thread.run(Thread.java:848)
06-23 11:26:32.838 19359-19359/com.lzy.demo W/System.err: com.lzy.okgo.exception.OkGoException: breakpoint file has expired!
06-23 11:26:32.838 19359-19359/com.lzy.demo W/System.err:     at com.lzy.okserver.download.DownloadTask.run(DownloadTask.java:308)
06-23 11:26:32.838 19359-19359/com.lzy.demo W/System.err:     at com.lzy.okserver.task.PriorityRunnable.run(PriorityRunnable.java:35)
06-23 11:26:32.838 19359-19359/com.lzy.demo W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
06-23 11:26:32.838 19359-19359/com.lzy.demo W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
06-23 11:26:32.838 19359-19359/com.lzy.demo W/System.err:     at java.lang.Thread.run(Thread.java:848)

**Comment by liajt** [comment]
我也遇到过这个问题，breakpoint file has expired!说断点文件过期

**Comment by wangchengyan** [comment]
确实有这个问题

**Comment by jeasonlzy** [comment]
ok  已发现问题，正在排查。。

**Comment by jeasonlzy** [comment]
这是 demo 的 bug，😓😓，为了演示上传数据，把下载文件的get请求换成了post请求，导致服务端不支持range头了，每次返回全量的数据。。库没问题，放心用哈。。

**Comment by wangchengyan** [comment]
感谢大神回复！！！



w-chengyan@163.com
 
发件人： 廖子尧
发送时间： 2017-06-29 12:26
收件人： jeasonlzy/okhttp-OkGo
抄送： wangchengyan; Comment
主题： Re: [jeasonlzy/okhttp-OkGo] 只要是在下载列表中暂停，然后在开始下载，就会出现下载异常，下载进度超过百分百，优先级高！！！ (#332)
这是 demo 的 bug，????????，为了演示上传数据，把下载文件的get请求换成了post请求，导致服务端不支持range头了，每次返回全量的数据。。库没问题，放心用哈。。

**Comment by zjsa** [comment]
怎么解决的？
