### ISSUE TITLE
OkDownload.pauseAll多线程报错，建议换成ConcurrentHashMap

### ISSUE THREAD

**Issue by liajt** [jeasonlzy/okhttp-OkGo#333]
1 java.lang.RuntimeException:Unable to start service com.led.player.download.MyDownLoadService@42433468 with Intent { cmp=com.led.player/.download.MyDownLoadService (has extras) }: java.util.ConcurrentModificationException
2 android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2673)
3 ......
4 Caused by:
5 java.util.ConcurrentModificationException:
6 java.util.LinkedHashMap$LinkedHashIterator.nextEntry(LinkedHashMap.java:350)
7 java.util.LinkedHashMap$EntryIterator.next(LinkedHashMap.java:379)
8 java.util.LinkedHashMap$EntryIterator.next(LinkedHashMap.java:377)
9 com.lzy.okserver.OkDownload.pauseAll(OkDownload.java:126)
10 com.led.player.download.MyDownLoadService.pauseAllDownload(MyDownLoadService.java:150)
11 com.led.player.download.MyDownLoadService.onStartCommand(MyDownLoadService.java:116)

**Comment by jeasonlzy** [comment]
ok，感谢。我考虑一下。。
