### ISSUE TITLE
使用缓存的时候 ,已经序列化了 cachekey也设置了. 但是有时候读取缓存的时候 会报 类型转换异常

### ISSUE THREAD

**Issue by onebee** [jeasonlzy/okhttp-OkGo#334]
使用缓存的时候 ,已经序列化了 cachekey也设置了. 但是有时候读取缓存的时候 会报 类型转换异常

**Comment by jeasonlzy** [comment]
那就是不同的网络请求返回的数据类型不一样，但是被你设置了同样的 cacheKey。。所以类型转换异常了。仔细检查代码。。
