### ISSUE TITLE
demo中的JsonConvert耦合性是否太强？

### ISSUE THREAD

**Issue by dotfeng** [jeasonlzy/okhttp-OkGo#335]
demo中关于json的示例适合所有response满足固定格式，JsonConvert还要处理LzyResponse，这样是不是就要不同格式的请求response就要定义不同的convert了？retrofit的处理方式是convert进行通用处理，其他格式类交给逻辑层处理更好。

**Comment by dotfeng** [comment]
我的意思是现在普遍的应用是请求object，返回object，可否像retrofit一样，出一个官方gsonconverter，至于特殊json格式封装，可以以此扩展。

**Comment by jeasonlzy** [comment]
详细的看[文档关于 JsonCallback 的介绍](https://github.com/jeasonlzy/okhttp-OkGo/wiki/JsonCallback)，想不想要耦合性，取决于自己。。

**Comment by xchengDroid** [comment]
你可以看看我的[EasyOkhttp](https://github.com/xchengDroid/EasyOkHttp)封装，复用性很强，自定义解析器，框架只把http请求简化处理，对解析抛出给外层
