### ISSUE TITLE
关于使用okgo缓存的问题

### ISSUE THREAD

**Issue by Troll4it** [jeasonlzy/okhttp-OkGo#336]
我这里能成功实现使用缓存，但是有一个疑问;假如一个接口有实现分页的效果，接口通过page=1，page=2,page=3，来实现，当数据请求到page=3时，断开网络，重新启动App，为什么只缓存了page=3的数据，page=1，page=2的数据没有缓存，求解？谢谢

**Comment by jeasonlzy** [comment]
因为你认为你的page不一样，是不一样的数据，但是你给的 cachekey 又是同一个，框架怎么知道你同一个 cachekey 还有不同的page呢，所以你如果想就算page不一样，缓存也要不一样，那就给不一样的key，不过我觉得没有必要，详细看demo里面关于缓存supercache包下的代码。。没必要把个网络app做成跟个单机离线一样。。缓存有一部分就行了，不是所有的地方都需要缓存的，也不是所有的页面都需要缓存的。

**Comment by Troll4it** [comment]
后来想了一下通过这种方式来写，应该没有问题吧
   PostRequest<MegaoResponse<RxHomeDataBean>> postRequest = OkGo.<MegaoResponse<RxHomeDataBean>>post(Api.OKGOAPI)
                .cacheKey("FashionFragment");
        if (page == 1) { //只缓存第一页数据
            postRequest.cacheMode(CacheMode.FIRST_CACHE_THEN_REQUEST);
        }
        postRequest.params("data", getHomeBean("home", "1", String.valueOf(page), "15"))

**Comment by jeasonlzy** [comment]
详细看文档中缓存这一部分  [点击看文档](https://github.com/jeasonlzy/okhttp-OkGo/wiki/Cache#%E9%A1%B9%E7%9B%AE%E4%B8%AD%E4%BD%BF%E7%94%A8%E7%BC%93%E5%AD%98)
