### ISSUE TITLE
https配置请求失败

### ISSUE THREAD

**Issue by yhc74470** [jeasonlzy/okhttp-OkGo#337]
android4.4手机，引用okgo框架，接口请求用的是https，用方法一的信任所有证书结果请求失败
javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x775e4300: Failure in SSL library, usually a protocol error
error:14077102:SSL routines:SSL23_GET_SERVER_HELLO:unsupported protocol (external/openssl/ssl/s23_clnt.c:714 0x73545cf8:0x00000000)

**Comment by jeasonlzy** [comment]
这种情况一般是两个原因
1. 部分国产手机对 SSL/TLS 协议的支持有定制化的改动，导致某些版本不支持
2. 服务端对 SSL/TLS 的配置过高，不信任低安全级别的协议，因为目前最高安全等级的协议是 TLS1.2 版本，可能你服务端只支持1.2版本及以上，而android4.4版本的手机一般内置的是 SSL 或者 TLS1.0 1.1 版本的协议，导致TLS握手失败。

上面的错误日志也显示出来了，SSL23_GET_SERVER_HELLO:unsupported protocol ，握手异常发生在GET_SERVER_HELLO阶段，原因是不支持的协议。

所以最理想的解决方案是检查服务端对 TLS 的配置。
