### ISSUE TITLE
关于缓存处理

### ISSUE THREAD

**Issue by JustinChiang123** [jeasonlzy/okhttp-OkGo#338]
接口请求返回值：
> 12345

此时界面展示：
> 12345

用户添加其他值：
> 6

此时界面展示：
> 612345

上面这个情况，能不能直接找到缓存值，直接修改？
达到接口请求返回值：
> 612345

其实说白了，就是手动修改缓存值。

**Comment by jeasonlzy** [comment]
详细看文档的缓存部分，关于data字段的解释  [点击这里看文档](https://github.com/jeasonlzy/okhttp-OkGo/wiki/Cache#%E7%BC%93%E5%AD%98%E7%9A%84%E6%89%8B%E5%8A%A8%E6%93%8D%E4%BD%9C)
