### ISSUE TITLE
在fragment 中的onResume（） 中 OkGo.<String>get 只走onStart 之后就没走别的了

### ISSUE THREAD

**Issue by gaoguanqi** [jeasonlzy/okhttp-OkGo#339]
在fragment 中的onResume（） 中 OkGo.<String>get 只走onStart 之后就没走别的了

**Comment by jeasonlzy** [comment]
我经过测试并没有遇到，以下是在 demo 中的测试代码
![image](https://user-images.githubusercontent.com/13421975/27635391-583f6002-5c39-11e7-82f8-8fdc063a0887.png)
![image](https://user-images.githubusercontent.com/13421975/27635401-5fdf5ee8-5c39-11e7-9715-023a408d43fe.png)

**Comment by gaoguanqi** [comment]
多谢，应该是我的问题，我在去排查原因
