### ISSUE TITLE
关于拦截器中增加公共参数

### ISSUE THREAD

**Issue by saurylip** [jeasonlzy/okhttp-OkGo#340]
老大 我们的需求是这样:每次请求网络时,拿到全部参数转换成json格式并加密,生成一个新的参数"sign",然后传给后台.我目前使用拦截器拿到了全部参数,生成sign了,但是无法在拦截器中添加参数,想问下有办法实现吗?

**Comment by jeasonlzy** [comment]
拦截器的使用方法请自行百度。。如果拦截器不能添加参数的话，okhttp早就没人用了。
