### ISSUE TITLE
下载文件的时候，文件名有空格，不能下载了

### ISSUE THREAD

**Issue by BeforeFuture** [jeasonlzy/okhttp-OkGo#342]
文件名有空格，解析时出错，不能下载。。。。

**Comment by BeforeFuture** [comment]
我的下载链接里，文件名里面有两个空格，但是okgo只解析到一个空格，然后服务器就不认识这个链接了。。

**Comment by BeforeFuture** [comment]
这个是OKgo解析的：%E9%9C%80%E6%B1%82%231226+DTLWG_R705B_04B0_0600+%E9%A1%B9%E7%9B%AE%E7%89%88%E6%9C%AC%E5%8F%91%E5%B8%83%E8%AF%B4%E6%98%8E.xlsx

这个是别的框架解析的：
%E9%9C%80%E6%B1%82%231226+DTLWG_R705B_04B0_0600++%E9%A1%B9%E7%9B%AE%E7%89%88%E6%9C%AC%E5%8F%91%E5%B8%83%E8%AF%B4%E6%98%8E.xlsx
仔细看，发现少一个“+”号，其实是少解析一个空格。。。。

**Comment by BeforeFuture** [comment]
建议大神在请求的时候，判断一下参数里空格的个数，比如两个空格的时候，应该替换成两个“++”，
然后解析相对应的结果

**Comment by jeasonlzy** [comment]
这个不是解析导致的，是你传的url就是一个+号吧。。你仔细看看。然后试试 3.0.2 版本。。

**Comment by BeforeFuture** [comment]
我传 的不是加号，因为文件名里有两个地方包含了空格，，第一个地方是一个空格，第二个地方是2个空格，因为我用别的框架解析出来的就是第一个地方对应了一个+号，第二个地方对应了两个+号，但是okgo解析之后，第二个出现2个空格的地方，就剩下一个加号了。。。。。然后服务器就返回404，说不认识这个链接。。。

**Comment by jeasonlzy** [comment]
应该是你代码中原本就只有一个空格，我测试是没有问题的。多少个空格转换后的地址都是对的。

**Comment by BeforeFuture** [comment]
需求#1226 DTLWG_R705B_04B0_0600  项目版本发布说明.xlsx
上面这一句是文件原名，那个0600后面是两个空格，如果方便的话，麻烦你试试，看看是否有问题。。。

**Comment by jeasonlzy** [comment]
你发出来的只有一个空格

**Comment by BeforeFuture** [comment]
大神，对不起，是我这边解析时用了HTML的格式化，导致出了问题，实在不好意思。。这个可以issues关闭了。。。
再次抱歉！
