### ISSUE TITLE
无法连接网络

### ISSUE THREAD

**Issue by YuHaoOi** [jeasonlzy/okhttp-OkGo#345]
无网络启动app后，在开启网络，以后的接口请求永远报无法链接网络，app卸载重装也是报这个错误，但是实际上是有网络的，换一台手机就可以连接网络了，很奇怪的bug, 烦死我了，我使用的版本是2.1.4，请问可能原因是什么呢？

**Comment by jeasonlzy** [comment]
这个不是网络库的问题哦。仔细检查其他地方的代码逻辑，可能有控制请求相关的代码。。实在不行你可以试试okgo的demo，无网启动，然后再联网获取数据。
