### ISSUE TITLE
OkDownload强杀进程或者异常断电，断点信息没有了，从头开始下载了，有点严重

### ISSUE THREAD

**Issue by liajt** [jeasonlzy/okhttp-OkGo#346]

**Comment by jeasonlzy** [comment]
目前没有复现，建议使用最新的 3.0.2 版本。。相关bug已经修复了。。

**Comment by liajt** [comment]
好的，感谢，我再试一下

**Comment by liajt** [comment]
你好，我升级3.0.2测试了下，发现异常断电和强杀断点丢失的问题还存在，应该是没有修复， 请关注一下

**Comment by jeasonlzy** [comment]
你用demo看吧，demo是没有问题的。。估计是你写的问题。。

**Comment by liajt** [comment]
我写的代码是：
okDownload.request(bean.getRealUrl(), request)
                    .fileName(bean.getRealName() + "_")
                    .folder(dir)
                    .register(loopListener).start();
请问这个会有明显不合适的写法吗？
我check下demo看下，thankyou！！！

**Comment by jeasonlzy** [comment]
可能是 realurl 每次都不一样吧。第一个参数是tag，相同的下载url地址，如果使用不一样的tag，也会认为是两个下载任务，不同的下载url地址，如果使用相同的tag，会认为是同一个任务，导致断点错乱

**Comment by liajt** [comment]
我下载地址是相同的，我就是拿url作为唯一的tag的；
断网的断点续传是ok的，强杀不行，so我觉得是bug，我再测试下吧，有问题反馈给你

**Comment by jeasonlzy** [comment]
你先测试demo吧，看demo是否有问题。

**Comment by liajt** [comment]
ok

**Comment by liajt** [comment]
我测试了下，demo没问题呢。应该是我的问题，非常感谢回复。。。

**Comment by sundyli** [comment]
此问题解决了吗，我也遇到了
