### ISSUE TITLE
请教一个返回数据的问题

### ISSUE THREAD

**Issue by HeJingWei** [jeasonlzy/okhttp-OkGo#347]
代码如下：
LzyResponse lzyResponse = Convert.fromJson(jsonReader, type);
                response.close();
                int code = lzyResponse.code;
                if (code == 0) {
                    //noinspection unchecked
                    return (T) lzyResponse;
                } else if (code == 104) {
                    throw new IllegalStateException("用户过期");
                }

如果我在这里处理了code。此时服务器code给我返回104了，在callback的
onError(com.lzy.okgo.model.Response<T> response) {
        super.onError(response);
    }
这个回调里，能拿到服务器给的lzyResponse吗？

**Comment by jeasonlzy** [comment]
你可以在 convertResponse 中把你转换后的这个值保存为成员变量，在onError 中不就拿到了。

**Comment by HeJingWei** [comment]
convertResponse 中return的数据会直接到onsuccess去吗
