### ISSUE TITLE
post请求乱码

### ISSUE THREAD

**Issue by mangZengLiao** [jeasonlzy/okhttp-OkGo#352]
作者你好:
首先非常感谢你贡献的这个库，在post请求时，发现请求的参数会默认utf_8进行编码，再由服务端进行解码，这无疑加重了服务端哥们的工作量，有什么方式，使在请求的时候**默认不对传递的参数进行编码**呢？

**Comment by jeasonlzy** [comment]
不编码怎么传数据，网络数据是流，必然要编码。。
