### ISSUE TITLE
使用OKdownload，打开所有任务界面，跳转时会卡顿

### ISSUE THREAD

**Issue by BeforeFuture** [jeasonlzy/okhttp-OkGo#353]
我使用OKdownload做统一下载管理，有个下载列表界面，我每次从别的界面跳转过去到下载列表界面的时候，都会卡顿一下，而且，我测试了几次，发现任务越多（无论这些任务是什么下载状态），跳转时卡顿时间越久，反而任务越少，跳转时的卡顿时间就越小。

**Comment by jeasonlzy** [comment]
已解决。详细看升级日志，okgo v3.0.3    okserver v2.0.3 版本

**Comment by BeforeFuture** [comment]
我刚刚测试了（有20次以上），确实相比3.0.2版本的获取列表快了，尤其是任务列表数量非常多的时候，变化非常明显！
只不过还有稍微一点卡顿的感觉（任务列表共计193条数据，跳转大约有1.30秒）。

**Comment by jeasonlzy** [comment]
在 demo 中有这么几行代码 
![image](https://user-images.githubusercontent.com/13421975/28099128-083d5b5e-66ed-11e7-83f3-c14378f7889d.png)
这个是读取数据库的数据，理论上你的数据很多的时候，这几行代码最好放在子线程中，你的耗时也是发生在这里读数据库的时候，所以这个耗时应该靠自己解决，库是解决不了的。。
