### ISSUE TITLE
【requestAsync方法】异步请求prepareRawCall() 异常时建议

### ISSUE THREAD

**Issue by horsechestnut** [jeasonlzy/okhttp-OkGo#354]
1、问题描述： 
     prepareRawCall();异常无法捕获，例如传递一个无效URL时，
代码查阅后，认为DefaultCachePolicy.requestAsync（）方法的catch 不太合理

2、建议修改：
2.1、代码位置: DefaultCachePolicy.requestAsync（） ,以 DefaultCachePolicy为例
2.2、
try {
         prepareRawCall();
        } catch (Throwable throwable) {
          onError(Response.error(false, rawCall, null, throwable));
          return;
 }

3、当前代码：
 try {
                    prepareRawCall();
        } catch (Throwable throwable) {
                    Response.error(false, rawCall, null, throwable);
                    return;
        }

**Comment by jeasonlzy** [comment]
感谢你的建议，已修复，将在 3.0.4 版本发布，预计两天左右。
