### ISSUE TITLE
好像除了下载中的任务，其他状态的progress的filePath和fileName会为空

### ISSUE THREAD

**Issue by iota9star** [jeasonlzy/okhttp-OkGo#355]
如题，不清楚设计是这样还是出现了什么问题

**Comment by jeasonlzy** [comment]
我测试并没有出现，不知道你是怎么出现的。。。log 贴一下。。

**Comment by iota9star** [comment]
等一下下，现在我程序还跑不起来，我在重构，以前用的retrofit+rxdownload，改的有点多，哭。。。。

**Comment by iota9star** [comment]
![uc 20170712141108](https://user-images.githubusercontent.com/21272154/28104193-6c5900d8-670c-11e7-886a-96c519521f3b.png)
![uc 20170712141204](https://user-images.githubusercontent.com/21272154/28104194-6c9c929e-670c-11e7-8185-dbfc1e364f41.png)

就像这样，如果我应用重启之后，第一次打开管理界面的时候，这时候filePath和fileName是空的，如果我点了继续，然后他们的值才会出来

**Comment by iota9star** [comment]
这样的话就存在我刚打开下载管理界面的时候没有数据的窘境，希望看一下

**Comment by jeasonlzy** [comment]
已修复，最近两天发布 3.0.4 即可自动解决。。

**Comment by zhengxuan666** [comment]
我也遇到了同样的问题是通过 
Progress progress = DownloadManager.getInstance().get(url);
OkDownload.restore(progress);
恢复的Task 很多属性都是Null.
