### ISSUE TITLE
FileCallback 的downloadProgress(Progress progress)方法，不能监听到进度

### ISSUE THREAD

**Issue by 912419804** [jeasonlzy/okhttp-OkGo#357]
FileCallback 的downloadProgress(Progress progress)方法，不能监听到进度，没有回调改方法，在下载文件的时候，debug状态不能断点到

**Comment by jeasonlzy** [comment]
估计是用了 chuck 的拦截器或者其他自己写的拦截器，关掉拦截器就行了。

**Comment by 912419804** [comment]
@jeasonlzy 什么是chuck 的拦截器，怎么关掉，指的是okhttp3的拦截器吗？

**Comment by 912419804** [comment]
确实后台返回的头部包含

Transfer-Encoding:chunked

**Comment by huoxiang** [comment]
为什么关闭了，怎么解决问题的？

**Comment by DotMatrixDev1024** [comment]
拦截器不能关闭怎么办

**Comment by DotMatrixDev1024** [comment]
拦截器当中写了token失效的处理逻辑

**Comment by DotMatrixDev1024** [comment]
@jeasonlzy
