### ISSUE TITLE
关于上传任务的一个问题？

### ISSUE THREAD

**Issue by ddssingsong** [jeasonlzy/okhttp-OkGo#358]
首先说一下我遇到的问题
   我的app中有两个地方用到Upload任务管理，分为A场景和B场景，这个两个地方都是使用的是OkUpload来管理，且同时只进行一个任务
   现在我在B场景中开启了10个下载，大概需要耗时20分钟，我开启了B场景的下载之后，去开启A场景的发送消息队列，这个队列也是使用的OkUpload去管理，
  现在问题来了，A场景的队列只有等到B场景的队列走完才会开始，这时候我需要怎么做，让两个场景不互相影响，或者将A场景的队列的优先级高于B场景

**Comment by jeasonlzy** [comment]
以目前的版本来看，是无法解决这个问题的，这个问题需要等待下一次估计在 3.1.0 版本会尝试解决你的问题。

**Comment by jeasonlzy** [comment]
你可以建议产品把两个场景的上传列表放在一个单独的位置，这样就可以统一管理了。

**Comment by ddssingsong** [comment]
因为我看到有个参数是优先级，能否上传列表也有优先级，就是A场景的优先级高于B场景，就先执行A场景的请求，后执行b场景的请求

**Comment by jeasonlzy** [comment]
上传本来就有优先级，看demo 和文档就可以。与下载一样。。
