### ISSUE TITLE
代码混淆之后app崩溃

### ISSUE THREAD

**Issue by ypf168326** [jeasonlzy/okhttp-OkGo#359]
按照文档说明进行混淆，接口调用直接崩溃，没能捕获异常信息，不混淆，网络调用正常。

**Comment by jeasonlzy** [comment]
检查日志吧，肯定有其他的库没有混淆。。比如你用了 gson，rxjava，等可能不允许混淆的库。

**Comment by ypf168326** [comment]
好的，我再检查一下。

廖子尧 <notifications@github.com>于2017年7月13日 周四19:06写道：
