### ISSUE TITLE
项目中使用OKdownload，OKGO2.14版本，下载apk时，退出整个app，进程也清理了，再次进app时， DownloadInfo中对应这个apk的状态是无状态

### ISSUE THREAD

**Issue by Greathfs** [jeasonlzy/okhttp-OkGo#365]
项目中使用OKdownload，OKGO2.14版本，下载apk时，退出整个app，进程也清理了，再次进app时， DownloadInfo中对应这个apk的状态是无状态，应该是暂停状态才对啊，求大神指点下

**Comment by Greathfs** [comment]
![image](https://user-images.githubusercontent.com/18097997/28195887-a1b4e5de-687f-11e7-95d4-755dca72c892.png)

**Comment by jeasonlzy** [comment]
![image](https://user-images.githubusercontent.com/13421975/28196281-2e1460c0-6882-11e7-936c-1847c931b4f4.png)
OkDownload 在初始化的时候，会重置以前的状态。源码里面是这么设计的。

**Comment by Greathfs** [comment]
我是否可根据DownLoadInfo中字段判断下，如果已下载大小大于0，就表示这个apk之前下载过，我就把它的状态置为pause

**Comment by jeasonlzy** [comment]
按照自己的业务逻辑处理即可。
