### ISSUE TITLE
2.14 版本demo 上传图片可以,3.0以后的 demo  上传图片一直失败

### ISSUE THREAD

**Issue by onebee** [jeasonlzy/okhttp-OkGo#366]
跑的是demo  , 基本上没做任何改动  可能是什么原因呢

**Comment by jeasonlzy** [comment]
3.0 demo 可以上传呀。。。

**Comment by onebee** [comment]
![b4d4-5616-4b1d-a291-666eb5d07491-p](https://user-images.githubusercontent.com/8468626/28256290-64621fd2-6af3-11e7-9ae2-83c302eea556.jpeg)
现在是3.0.4 了  一直是最新的demo    上传图片一直失败
