### ISSUE TITLE
3.0.2版本文件上传失败，请求头中没有表单上传的header

### ISSUE THREAD

**Issue by xiaoxiaohu** [jeasonlzy/okhttp-OkGo#368]
![image](https://user-images.githubusercontent.com/13919009/28256710-7774fc6c-6af7-11e7-89fa-297d9e51d100.png)
![image](https://user-images.githubusercontent.com/13919009/28256731-9ba1c26e-6af7-11e7-92b0-bba6c61e91a8.png)
![image](https://user-images.githubusercontent.com/13919009/28256759-e321fe60-6af7-11e7-935a-fc61a84a5bf4.png)

![image](https://user-images.githubusercontent.com/13919009/28256735-b0badca8-6af7-11e7-908e-13ebc4f06a81.png)

![image](https://user-images.githubusercontent.com/13919009/28256759-e321fe60-6af7-11e7-935a-fc61a84a5bf4.png)

**Comment by jeasonlzy** [comment]
1. 你说的请求头的content-type是log没打印而已，并不是没有上传
2. 这个异常也是网络连接失败的异常，检查你的网络连接，是否开代理什么的
3. 可以升级到最新版 ，详细看github说明。

**Comment by xiaoxiaohu** [comment]
3.0.2版本调试时，header中确实没有看见content-type
后面替换为3.0.4 版本，log中有 相应日志，但是还是不能正常上传文件
demo
![image](https://user-images.githubusercontent.com/13919009/28259128-60d851ba-6b07-11e7-8d11-77d033d1a194.png)

![screenshot_20170717-154324](https://user-images.githubusercontent.com/13919009/28259107-40775af6-6b07-11e7-951e-b7294e4cc7c1.png)

自己的工程
![image](https://user-images.githubusercontent.com/13919009/28259147-746bc176-6b07-11e7-8185-b3466865764c.png)
![image](https://user-images.githubusercontent.com/13919009/28259195-abd57b48-6b07-11e7-9276-7fbcc0a49474.png)
经服务器确认，该文件上传请求不是一个表单提交
![image](https://user-images.githubusercontent.com/13919009/28259339-643d1a7e-6b08-11e7-98ca-188245329585.png)

**Comment by jeasonlzy** [comment]
应该是你服务器的问题，异常显示无法解析mutipart 的请求格式。。所以，多检查服务器把。。

**Comment by xiaoxiaohu** [comment]
服务器也许有问题，但是使用postman是能正常上传文件的，iOS端也是能正常使用的。
为了避免是我使用错误，我又重新下载的最新demo，同样不能上传文件

![screenshot_20170717-211904](https://user-images.githubusercontent.com/13919009/28270088-d48ca2b2-6b36-11e7-91d3-464275633a13.png)

这个应该是你服务器那边出问题了
![image](https://user-images.githubusercontent.com/13919009/28269895-2d5390fa-6b36-11e7-9e5a-1ca412bc42bd.png)


后面我是用okhttp自己 实现 单文件上传，能够正常上传文件
![image](https://user-images.githubusercontent.com/13919009/28269955-5edea2ea-6b36-11e7-857a-996fc0ab73a4.png)
![image](https://user-images.githubusercontent.com/13919009/28269963-67200e1c-6b36-11e7-91b7-d3eb2f392fa3.png)
![image](https://user-images.githubusercontent.com/13919009/28269997-82ba3224-6b36-11e7-9b5c-eb1624afe3c7.png)
![image](https://user-images.githubusercontent.com/13919009/28270059-bc40646e-6b36-11e7-9c5a-d4e66b6c855a.png)

**Comment by jeasonlzy** [comment]
可能环境问题吧。。我这边一直正常。。

**Comment by jeasonlzy** [comment]
详细的可以进群里说吧。。异常只能说明是网络的问题。。

**Comment by xiaoxiaohu** [comment]
是网络问题，同一个路由器，有线是正常的，无线就是不能上传了。。。
