### ISSUE TITLE
实现缓存需要实现序列化问题

### ISSUE THREAD

**Issue by zouzhenglu** [jeasonlzy/okhttp-OkGo#371]
在缓存的实体中用到了泛型T在解析完成保存，这样需要 序列化，那么，如果在convertResponse之前就缓存下来呢？这时候就是一个json字符串，那就不需要序列化了吧。

**Comment by jeasonlzy** [comment]
如果想用okgo自带的缓存功能，那么必须实现序列化接口，如果不用okgo自己的缓存功能，怎么保存，是否序列化，那就看你自己的写法了。

**Comment by zouzhenglu** [comment]
哎，提个建议而已。close#
