### ISSUE TITLE
关于400问题

### ISSUE THREAD

**Issue by zouzhenglu** [jeasonlzy/okhttp-OkGo#372]
既然404跟500的可以走onError方法，为什么你在设计的时候不让400走onError方法呢？再不济让他都另外一个方法也行啊，eg:  on400Error()

**Comment by jeasonlzy** [comment]
建议多看看文档  [callback讲解](https://github.com/jeasonlzy/okhttp-OkGo/wiki/Callback)

![image](https://user-images.githubusercontent.com/13421975/28309547-4ae56322-6bdc-11e7-887a-fddbae1cf392.png)

**Comment by zouzhenglu** [comment]
我是看了才建议你这么做的。

**Comment by jeasonlzy** [comment]
嗯，这个建议不采纳。。。

**Comment by 751811032** [comment]
但是 如果是 401  402  403明明已经是错误的了，返回的错误数据了，你却不走 onError方法，太坑了

**Comment by 751811032** [comment]
垃圾
