### ISSUE TITLE
普通请求不支持获取txt文件中的文本内容吗？

### ISSUE THREAD

**Issue by xzermu** [jeasonlzy/okhttp-OkGo#373]
`OkGo.<String>get(Urls.TXT)
                    .tag(this)
                    .execute(new StringCallback() {
                        @Override
                        public void onSuccess(Response<String> response) {
                            Logger.show(TAG, "request text onSuccess calling... String:" + response.body());
                        }

                        @Override
                        public void onError(Response<String> response) {
                            super.onError(response);
                            Logger.show(TAG, "request text onError calling... String:" + response.message());
                        }
                    });`
通过上面的方式去请求一个txt文本文档里的文本内容，每次都回调onError,msg为null.

**Comment by jeasonlzy** [comment]
你这是读取本地文件？okgo是做网络请求的，只能与服务器交互。。

**Comment by xzermu** [comment]
没有啊！是服务器上的txt文本

**Comment by jeasonlzy** [comment]
那就是下载文件，无论什么文件，读文件内容还是需要自己做的。。

**Comment by xzermu** [comment]
主要是我发现可以通过okhttp，直接获取txt文档中的文本内容。所以我以为okgo也可以。。嘿嘿
`OkHttpClient okClient = new OkHttpClient();
        Request build = new Request.Builder().url(Urls.UPDATE_TXT).build();
        okClient.newCall(build).enqueue(new Callback() {
            @Override
            public void onFailure(Call call, IOException e) {
                Logger.show(TAG, "checkUpdate request text onError calling... error:" + e.getMessage());
            }

            @Override
            public void onResponse(Call call, okhttp3.Response response) throws IOException {
                ResponseBody body = response.body();
                if (body == null)
                    return;
                byte[] b = body.bytes(); //获取数据的bytes
                String text = new String(b, "GB2312"); //然后将其转为gb2312
                Logger.show(TAG, "checkUpdate request text onSuccess calling... text:" + text);
                
            }
        });`

**Comment by jeasonlzy** [comment]
那你直接用 StringCallback 就可以了。。

**Comment by xzermu** [comment]
好吧！不知道说什么了，是我的错，这个text文本文档是存在于一个https协议链接上的，而我没有配置https访问证书及主机验证规则，一直回调onError()，刚刚把Throwable打印出来，才看见。。。
但是我还有一个问题，为什么 同样的https请求没做配置，okhttp就可以拿到数据呢？

**Comment by xzermu** [comment]
我想我找到原因了，我copy了okgodemo中的全局配置，主机验证默认return false。。。。
而通过okhttp访问时，重新new了一个okhttpclient ，所以是没有配置的。
谢谢你的回答！！！

**Comment by yuesetaimei** [comment]
做配置了就可以了吧
