### ISSUE TITLE
关于下载 文件大小为 -1 的情况

### ISSUE THREAD

**Issue by isYuriBoyka** [jeasonlzy/okhttp-OkGo#374]
http://wap.csc108.com/download/zxjt-2.1.0.20170620-zxjt.apk
此地址 用 OkGo.<File>get()  下载时所返回的文件大小为 -1 ，所以结果你知道的，无法绘制进度条，
（建议此情况 直接返回 已下载的总大小 和 下载速度 ）

**Comment by LinkGitcode** [comment]
我也遇到这个问题   可否具体一点  怎么解决？
