### ISSUE TITLE
泛型约束问题

### ISSUE THREAD

**Issue by kimonic** [jeasonlzy/okhttp-OkGo#375]
当callback约束为stringcallback时,使用该方法时传入stringcallback报错
public void GET(final Context context, String url, Callback (StringCallback)  callback) {
        OkGo. (StringCallback)  get(url)     // 请求方式和请求url
                .tag(context)                       // 请求的 tag, 主要用于取消对应的请求
                .cacheMode(CacheMode.DEFAULT)       // 缓存模式，详细请看缓存介绍
                .execute(callback);
    }

HttpMethods.getInstance().GET(this, "", new StringCallback() {//此处使用stringcallback报错
            @Override
            public void onSuccess(Response<String> response) {

            }
        });
不指定约束类型时,ide报没有泛型检查警告.
请问该如何处理??

**Comment by jeasonlzy** [comment]
详细的看demo吧，demo也有封装。。。
