### ISSUE TITLE
网络问题

### ISSUE THREAD

**Issue by JueShouGitHub** [jeasonlzy/okhttp-OkGo#376]
大佬，我的报错，提示为：
com.lzy.okgo.exception.HttpException: network error! http response code is 404 or 5xx!
这是啥问题？

这是我的代码：
网络权限
`<uses-permission android:name="android.permission.INTERNET"/>`

`OkGo.<String>post(Urls.ROOTURL).upString(s).execute(new StringCallback() {
            @Override
            public void onSuccess(Response<String> response) {
                Log.d("log", response.body());
            }

            @Override
            public void onError(Response<String> response) {
                super.onError(response);
            }
        });`

**Comment by jeasonlzy** [comment]
提示很清楚啊。。response code is 404 or 5xx!。。。响应码 404 或者 500 了。。  多看文档  https://github.com/jeasonlzy/okhttp-OkGo/wiki/Callback

**Comment by JueShouGitHub** [comment]
嗷嗷，好的。谢谢啊。一开始我还以为无法连接网络呢，现在懂了
