### ISSUE TITLE
使用问题

### ISSUE THREAD

**Issue by KiWiLss** [jeasonlzy/okhttp-OkGo#379]
使用偶尔出现这个问题
 java.net.SocketException
Socket closed
com.lzy.okgo.request.Request.execute(Request.java:383)

**Comment by wannoo1990** [comment]
我使用OkGo.getInstance().cancelTag(this);取消请求也会出现java.net.SocketException
Socket closed这句日志

**Comment by jeasonlzy** [comment]
取消请求了，必然会抛异常呀。。

**Comment by wannoo1990** [comment]
我是取消请求,但一楼不一定是
