### ISSUE TITLE
取消请求没有回调？

### ISSUE THREAD

**Issue by wannoo1990** [jeasonlzy/okhttp-OkGo#381]
使用 OkGo.getInstance().cancelTag(this); 能取消请求，并打印信息：
<-- HTTP FAILED: java.net.SocketException: Socket closed
如果tag设置失败，是不会出现这句话的，所以不是tag的问题。
但是并没有进入onError或onFinish()回调中。
请问是不是设计的原因？

**Comment by jeasonlzy** [comment]
请求都取消了。。。干嘛还要回调。。。

**Comment by wannoo1990** [comment]
请求取消不一定是在onDestory()里取消,有可能是加载时间过长可让用户主动取消,,,
有些在onFinish统一做的回调就要分开判断了。
就像异常try{ }catch{ }最后一定会进finally{ }里面，感觉应该onFinish()或别的方法是一定会进入的

**Comment by wannoo1990** [comment]
之前看到 一个okHttp的简单封装库http://blog.csdn.net/lmj623565791/article/details/49734867，里面取消请求回回调onError和onAfter

**Comment by jeasonlzy** [comment]
那就是思路不一样了。。okgo 就是取消请求就什么都没有了。。而且一般取消请求发生在 onDestory 中，这时候最好不需要任何回调。。如果需要回调，可以使用其他库，或者修改源码，目前不修改的源码的情况下是做不到的。。而且以后也不会加入回调。。

**Comment by wannoo1990** [comment]
收到,感谢回复
