### ISSUE TITLE
Okhttp设置请求日志过滤器

### ISSUE THREAD

**Issue by missyou2013** [jeasonlzy/okhttp-OkGo#382]
Okhttp设置请求日志过滤器，支持打印Post请求参数 
request.body() 获取到的是com.lzy.okgo.request.ProgressRequestBody
不是FormBody类  ，所以没法获取对应的参数！
请问怎么解决？

**Comment by jeasonlzy** [comment]
暂时没有提供方法，可以修改 ProgressRequestBody 类，返回其中的 requestBody 对象，这个对象就是真实的请求对象。。

预计3.1 版本加入这个方法。。

okgo也可以不需要使用拦截器，在 onStart 方法中做一些公共的事情，与拦截器效果一样。。

**Comment by missyou2013** [comment]
好的，谢谢！

**Comment by CnRiven** [comment]
但是如果我是使用的RxJava了，那么就用不到callback了，所以onStart方法也用不到了呢，还是需要使用拦截器的
