### ISSUE TITLE
okgo2.0 在android 6.0下即使设置了信任所有证书也会验证证书失败？

### ISSUE THREAD

**Issue by pdog18** [jeasonlzy/okhttp-OkGo#384]
我在初始化的okgo的时候设置了，我确定我全局就用到一个okgo               
```
  .setCertificates();    //信任所有https证书
```
但是在请求网络的时候依然是发生SSL验证失败？
I/Okgo: <-- HTTP FAILED: javax.net.ssl.SSLHandshakeException: Handshake failed

**Comment by cervy** [comment]
同问

**Comment by jeasonlzy** [comment]
参考demo，可能没有设置 hostnameVerifier

**Comment by pangrongxian** [comment]
同问+1 。。
