### ISSUE TITLE
3.0.3上传Header，请求头中看不到

### ISSUE THREAD

**Issue by yudongyy** [jeasonlzy/okhttp-OkGo#385]
发送请求，上传了header，但是在请求头中看不到相关的信息，求解释
<img width="294" alt="default" src="https://user-images.githubusercontent.com/12558863/28743223-1744c67c-7477-11e7-9d9f-11e7da71f486.png">

**Comment by jeasonlzy** [comment]
抓包看吧，log可能不打印。。实际上是传上去了。。

**Comment by DotMatrixDev1024** [comment]
+1传不上去
