### ISSUE TITLE
当遇到ProtocolException: unexpected end of stream，点击出错断续下载，text进度会出现超100%情况，已读文件大小也已超

### ISSUE THREAD

**Issue by zhp075366** [jeasonlzy/okhttp-OkGo#387]
![image](https://user-images.githubusercontent.com/22560319/28769751-52ea6cc4-760f-11e7-878a-3dfb1825e373.png)
demo里面也这个问题，下载蘑菇街就会复现：ProtocolException: unexpected end of stream
点击重新下载，还是会有ProtocolException: unexpected end of stream
点击出错继续下载的话，就会出现我截图的情况。

请看看，谢谢！

**Comment by zhp075366** [comment]
是服务器的问题？

**Comment by zhp075366** [comment]
![image](https://user-images.githubusercontent.com/22560319/28771306-e37823d0-7614-11e7-816c-73713b99781b.png)
![image](https://user-images.githubusercontent.com/22560319/28771341-fcb5503e-7614-11e7-8885-bc589916c83b.png)
大小获取不对，同样的链接，360浏览器获取就是对的

**Comment by jeasonlzy** [comment]
1. 使用了 post，put 等请求
2. 服务器不支持 range 头

**Comment by MickeyDaddy** [comment]
我是偶现这个问题，正常下载都是可以的，但是 偶尔出现这个问题
