### ISSUE TITLE
在下载阿里云的pptx，word等微软全家桶的时候，没有显示进度， 但是等到下载完了，直接就结束了

### ISSUE THREAD

**Issue by husongzhen** [jeasonlzy/okhttp-OkGo#388]
不知道什么原因，通过抓包工具还在一直下载，但是就是没有进度

**Comment by jeasonlzy** [comment]
1. 关闭 chuck 拦截器
2. 关闭自己的拦截器
3. 关闭okgo的日志拦截器

总之就是关闭所有的拦截器。。。

**Comment by Vancly** [comment]
将demo中的apk下载地址替换成阿里云上的文件，就没有进度了，如何解决
