### ISSUE TITLE
关于继续下载的问题

### ISSUE THREAD

**Issue by wuxingtianxia** [jeasonlzy/okhttp-OkGo#389]
`[我下载自己的应用，在网上找的下载地址，点击下载下载一段时间再点击暂停，再点击继续下载等到下载完成后下载进度超过了100%，我见前面有人提问过，说是服务器的问题，但是我这个并没有使用你的服务器，不知道是什么原因，我下载和继续下载都调用的是task.start()方法，帮忙看下，谢谢。
![qq 20170801164842](https://user-images.githubusercontent.com/13298118/28817282-4925706e-76da-11e7-9d27-af4ab23634ca.png)
`

**Comment by wuxingtianxia** [comment]
第一次下载和继续下载服务器返回来的数据是一样的大小，LOG如下：
[socket][/192.168.123.205:53042] connected
08-01 09:21:53.180 20070-20653/com.wisky.myokgodownloadtest I/System.out: [CDS]rx timeout:60000
08-01 09:21:53.228 20070-20653/com.wisky.myokgodownloadtest I/OkGo: <-- 200 OK http://gdown.baidu.com/data/wisegame/ca9305e85a08b26d/kugouyinle_8851.apk?commonParamsKey1=commonParamsValue1&commonParamsKey2=%E8%BF%99%E9%87%8C%E6%94%AF%E6%8C%81%E4%B8%AD%E6%96%87%E5%8F%82%E6%95%B0 (131ms）
08-01 09:21:53.228 20070-20653/com.wisky.myokgodownloadtest I/OkGo: 	Server: JSP3/2.0.14
08-01 09:21:53.228 20070-20653/com.wisky.myokgodownloadtest I/OkGo: 	Date: Tue, 01 Aug 2017 09:21:48 GMT
08-01 09:21:53.228 20070-20653/com.wisky.myokgodownloadtest I/OkGo: 	Content-Type: application/vnd.android.package-archive
08-01 09:21:53.228 20070-20653/com.wisky.myokgodownloadtest I/OkGo: 	Content-Length: 45741101
08-01 09:21:53.228 20070-20653/com.wisky.myokgodownloadtest I/OkGo: 	Connection: close
08-01 09:21:53.228 20070-20653/com.wisky.myokgodownloadtest I/OkGo: 	ETag: "c170ec7dca9305e85a08b26d671d34a9"
08-01 09:21:53.228 20070-20653/com.wisky.myokgodownloadtest I/OkGo: 	Last-Modified: Thu, 13 Jul 2017 16:57:04 GMT
08-01 09:21:53.228 20070-20653/com.wisky.myokgodownloadtest I/OkGo: 	Expires: Thu, 03 Aug 2017 23:13:04 GMT
08-01 09:21:53.228 20070-20653/com.wisky.myokgodownloadtest I/OkGo: 	Age: 36523
08-01 09:21:53.229 20070-20653/com.wisky.myokgodownloadtest I/OkGo: 	Accept-Ranges: bytes
08-01 09:21:53.229 20070-20653/com.wisky.myokgodownloadtest I/OkGo: 	Content-MD5: wXDsfcqTBehaCLJtZx00qQ==
08-01 09:21:53.229 20070-20653/com.wisky.myokgodownloadtest I/OkGo: 	x-bce-debug-id: MTAuNjEuMjQ1LjQ3OkZyaSwgMTQgSnVsIDIwMTcgMDc6MTI6MTkgQ1NUOjczOTM5NjQ3Ng==
08-01 09:21:53.229 20070-20653/com.wisky.myokgodownloadtest I/OkGo: 	x-bce-request-id: 2ee9e73f-7fa0-4b69-8bb3-a6181697a122
08-01 09:21:53.229 20070-20653/com.wisky.myokgodownloadtest I/OkGo: 	x-bce-storage-class: STANDARD
08-01 09:21:53.229 20070-20653/com.wisky.myokgodownloadtest I/OkGo: 	Ohc-Response-Time: 1 0 0 0 0 0
08-01 09:21:53.229 20070-20653/com.wisky.myokgodownloadtest I/OkGo:  
08-01 09:21:53.229 20070-20653/com.wisky.myokgodownloadtest I/OkGo: 	body: maybe [binary body], omitted!
08-01 09:21:53.229 20070-20653/com.wisky.myokgodownloadtest I/OkGo: <-- END HTTP

**Comment by wuxingtianxia** [comment]
Content-Length: 45741101，这个值不变化，不清楚是怎么回事

**Comment by jeasonlzy** [comment]
1. 使用了 post，put 等请求
2. 服务器不支持 range 头

**Comment by wuxingtianxia** [comment]
是不是将请求方式改成get就可以了，要修改的话在哪里修改呢，谢谢

**Comment by jeasonlzy** [comment]
请求方式是你自己写的。。不是框架写的。。框架不限制请求方式。。

**Comment by wuxingtianxia** [comment]
奥，好的，明白了，谢谢大神

**Comment by wuxingtianxia** [comment]
我又检查了一下我的代码，我使用的是GetRequest<File> request= OkGo.<File>get(apkUrl);get请求，没有使用post请求或者put请求，还是出现继续下载时返回全部数据的问题，能不能帮忙解释一下这个现象，我实在是找不出哪里错了。

**Comment by jeasonlzy** [comment]
服务器不支持 range 头

**Comment by wuxingtianxia** [comment]
好吧，看来不是我这边的问题了，我去找服务器端的解决吧，谢谢了。

**Comment by wuxingtianxia** [comment]
我找后台检查了一遍，他说是可以支持Range头的，我又使用了Xutils框架填充了同样的url地址，是可以断点下载的，有空了你自己试一下这个断点下载，看看是不是确实是存在这个问题，我觉着是http请求时添加Header("Range","bytes="+startposition+"-")时，该请求头没有添加进去导致的，但是我并没有具体的找到原因，我通过下面的代码想要打印一下header中的Range信息，

` Headers headers1=new Headers.Builder().build();
            request.headers(HttpHeaders.HEAD_KEY_RANGE, "bytes=" + startPosition + "-");
            Log.d("tag33","Range="+headers1.get(HttpHeaders.HEAD_KEY_RANGE));`

得到的结果都是空的，如下所示：

08-03 02:23:46.441 10944-11772/com.lzy.demo D/tag33: 当前已经下载的大小是：6682220
08-03 02:23:46.441 10944-11772/com.lzy.demo D/tag33: Range=null
08-03 02:23:46.441 10944-11772/com.lzy.demo D/tag33: request.toString()=com.lzy.okgo.request.GetRequest@a10270f
08-03 02:23:46.577 10944-11772/com.lzy.demo D/tag33: response.toString()=Response{protocol=http/1.1, code=200, message=OK, url=http://gdown.baidu.com/data/wisegame/74ac7c397e120549/QQ_708.apk?commonParamsKey1=commonParamsValue1&commonParamsKey2=%E8%BF%99%E9%87%8C%E6%94%AF%E6%8C%81%E4%B8%AD%E6%96%87%E5%8F%82%E6%95%B0&bbb=222}
08-03 02:23:46.577 10944-11772/com.lzy.demo D/tag33: response.headers().toString()=Server: JSP3/2.0.14
                                                     Date: Thu, 03 Aug 2017 02:23:40 GMT
                                                     Content-Type: application/vnd.android.package-archive
                                                     Content-Length: 43566497
                                                     Connection: close
                                                     ETag: "4c08686774ac7c397e1205497e43c20c"
                                                     Last-Modified: Wed, 19 Jul 2017 11:21:03 GMT
                                                     Expires: Thu, 03 Aug 2017 11:50:03 GMT
                                                     Age: 225217
                                                     Accept-Ranges: bytes
                                                     Content-MD5: TAhoZ3SsfDl+EgVJfkPCDA==
                                                     x-bce-debug-id: MTAuNjEuMjQ1LjQ4OldlZCwgMTkgSnVsIDIwMTcgMTk6NTA6MDMgQ1NUOjMwMDMzNjg5MDg=
                                                     x-bce-request-id: dc78e2de-5817-4486-876d-86f1dc97c92c
                                                     x-bce-storage-class: STANDARD
                                                     Ohc-Response-Time: 1 0 0 0 0 0

**Comment by wuxingtianxia** [comment]
我又通过以下代码打印了一下request中的内容：
`Log.d("tag33","request.toString()="+request.toString());`
得到的结果如下：
` D/tag33: request.header=HttpHeaders{headersMap={Accept-Language=zh-CN,zh;q=0.8, User-Agent=只有安装在/system/app中的软件包支持FACTORY_TEST操作。, commonHeaderKey1=commonHeaderValue1, commonHeaderKey2=commonHeaderValue2, aaa=111, Range=bytes=3129652-43566497}}`
从这里看到request中的header确实添加上了Range，但是response.header中的Accept-Rangers却是空的，可能确实是服务器不支持Range头吧，但我更倾向于我们的request中的header信息没有发送到服务器。
`response.headers().toString()=Server: JSP3/2.0.14
                                                     Date: Thu, 03 Aug 2017 03:05:32 GMT
                                                     Content-Type: application/vnd.android.package-archive
                                                     Content-Length: 43566497
                                                     Connection: close
                                                     ETag: "4c08686774ac7c397e1205497e43c20c"
                                                     Last-Modified: Wed, 19 Jul 2017 11:21:03 GMT
                                                     Expires: Thu, 03 Aug 2017 11:50:03 GMT
                                                     Age: 227729
                                                     Accept-Ranges: bytes
                                                     Content-MD5: TAhoZ3SsfDl+EgVJfkPCDA==
                                                     x-bce-debug-id: MTAuNjEuMjQ1LjQ4OldlZCwgMTkgSnVsIDIwMTcgMTk6NTA6MDMgQ1NUOjMwMDMzNjg5MDg=
                                                     x-bce-request-id: dc78e2de-5817-4486-876d-86f1dc97c92c
                                                     x-bce-storage-class: STANDARD
                                                     Ohc-Response-Time: 1 0 0 0 0 4`
上面相应头中的Accept-Ranges应该是：Accept-Ranges: bytes=“startposition”-"endposition"/allsize这种形式的，真是令人费解，我还得继续修行啊，感觉越学越觉着啥都不会了。

**Comment by jeasonlzy** [comment]
断点下载肯定是没问题的，上传的range头一定是传了的，传的数值肯定也是对的，这几点你可以通过抓包来确定，最好不要看log，通过抓包你就能清楚的看到双方交互的数据信息了。。。

**Comment by jeasonlzy** [comment]
把demo下载下来，只需要修改DownloadListActivity中这个url，下载列表的第一个就是要下载的你的东西，后面的图片表示下载过程中暂停两次的请求头与响应头的抓包信息，一切正常，apk正常下载。。
![qq20170803-185248](https://user-images.githubusercontent.com/13421975/28918772-4980756e-787d-11e7-83d7-fffc4b348a5e.png)

<img width="803" alt="qq20170803-184955 2x" src="https://user-images.githubusercontent.com/13421975/28918624-a168d70e-787c-11e7-83f1-908f04ba2d04.png">
<img width="909" alt="qq20170803-185141 2x" src="https://user-images.githubusercontent.com/13421975/28918659-d1a54222-787c-11e7-92b5-68f6b7eb1503.png">
<img width="817" alt="qq20170803-185004 2x" src="https://user-images.githubusercontent.com/13421975/28918626-a3629216-787c-11e7-8bdc-21bd9bfcd538.png">
<img width="881" alt="qq20170803-185128 2x" src="https://user-images.githubusercontent.com/13421975/28918663-d556fc62-787c-11e7-8279-7711705f740d.png">
<img width="810" alt="qq20170803-185011 2x" src="https://user-images.githubusercontent.com/13421975/28918629-a6efc2fa-787c-11e7-8d1b-36299b72d29e.png">
<img width="954" alt="qq20170803-185115 2x" src="https://user-images.githubusercontent.com/13421975/28918665-d78d9162-787c-11e7-919d-4e41c6d6ed8b.png">

**Comment by wuxingtianxia** [comment]
确实是这样的，我自己再理理思路，看看代码，谢谢大神百忙之中回复，麻烦了。

**Comment by zt631008757** [comment]
我也碰到这个问题了，返回  body: maybe [binary body], omitted!  
文件下载，没有哪里设置请求方式，参数的，就一个链接，  大部分手机能下， 有的不能下
