### ISSUE TITLE
okgo  下载的文件打开乱码

### ISSUE THREAD

**Issue by zhangchaoqun** [jeasonlzy/okhttp-OkGo#391]
我使用okgo下载的docx文档打开乱码，但是我使用okhttp下载的docx文档打开没问题，求大神解答，急等

**Comment by jeasonlzy** [comment]
关闭拦截器。。乱码 99.9999999%  都是拦截器的问题。。

**Comment by yemh111** [comment]
我上传的PPT excel word然后下载之后也是乱码,有些打开直接提示文件损坏了

**Comment by yemh111** [comment]
这个拦截器指的是哪个拦截器

**Comment by zhangchaoqun** [comment]
已解决，就按大佬给的解决方案就可以，@yemh111

**Comment by zhangchaoqun** [comment]
@yemh111 就是初始化的时候把debug给注释掉就可以了，就是这句话  ：：：：.debug("OkGo", Level.INFO , true)

**Comment by yemh111** [comment]
我貌似就没开这个东西,我把日志拦截器那块也注释了,上传文件成功之后,内容不是原有内容,下载下来打开的时候也不行,PPT直接报文件损坏,方便加个Q吗,597150633

**Comment by zhangchaoqun** [comment]
@yemh111 没问题啊，你在检查一下你的初始化，我下载后调用wps打开都是可以的
