### ISSUE TITLE
3.0.4 upJson() upString() 方法怎么找不到了?

### ISSUE THREAD

**Issue by hookbin** [jeasonlzy/okhttp-OkGo#392]
![image](https://user-images.githubusercontent.com/13349733/28863956-7a75fbf2-779d-11e7-9cd4-2ced37693022.png)

**Comment by hookbin** [comment]
使用Json必须使用post的方式请求！！！！

但是实际http请求中Get也是有Body的！！！！

**Comment by jeasonlzy** [comment]
get怎么有 up 方法？  用post 或者 put 啊！！！！

**Comment by hookbin** [comment]
HTTP的底层是TCP/IP。所以GET和POST的底层也是TCP/IP，也就是说，GET/POST都是TCP链接。GET和POST能做的事情是一样一样的。你要给GET加上request body，给POST带上url参数，技术上是完全行的通的。

**Comment by jeasonlzy** [comment]
男人和女人都是人，那么男人和女人能做的事一样么？

既然HTTP是基于TCP/IP的，那么还要分GET和POST干嘛呢？不干脆直接用TCP不就行了。。肯定是在上层对他们做了差异化的区分。。框架定义up系列方法是在请求体里面添加参数，get和head是没有请求体的，如何添加参数？
