### ISSUE TITLE
上传的word ppt excel 打开提示文件错误

### ISSUE THREAD

**Issue by yemh111** [jeasonlzy/okhttp-OkGo#393]
我是用put方式上传的文件,从后台拿到上传的文件打开提示文件错误,
再下载下来的时候手机打开提示文件损坏
大佬帮我看看什么问题,和上传方式有关系吗
急等

**Comment by jeasonlzy** [comment]
可能服务端编码和客户端不一致。

**Comment by yemh111** [comment]
客户端编码可以在哪里进行查看呢

**Comment by jeasonlzy** [comment]
上传请求头中的  content-type

**Comment by yemh111** [comment]
PutRequest<String> request = OkGo.<String>put(url + "transfer/objects?isoverwrite=true")
                                    .headers("accesskey", BaseUtils.getAccessKey())
                                    .headers("token", BaseUtils.getToken())
                                    .headers("remotename", remotePath)
                                    .headers("Content-Type","application/octet-stream")
                                    .headers("Content-Length", length + "")
                                    .params("fileKey" + i, new File(path))
                                    .converter(new StringConvert());
我在这里添加了 Content-type, 上传的文件还是错误的
