### ISSUE TITLE
打开应用时会application会报异常

### ISSUE THREAD

**Issue by istarvip** [jeasonlzy/okhttp-OkGo#394]
android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5): 

在自定义application类中初始化时有一段代码是：

     builder.cookieJar(new CookieJarImpl(new DBCookieStore(this)));  

包数据被locked了。就退出了。这个异常偶尔发生

**Comment by jeasonlzy** [comment]
哪个版本？

**Comment by istarvip** [comment]
最新的
