### ISSUE TITLE
Rx2线程相关问题

### ISSUE THREAD

**Issue by gzasgjq** [jeasonlzy/okhttp-OkGo#395]
1.默认请求返回Flowable是在主线程回调的？？？？
2.我看源码请求方式的切换是用AdapterParam控制的，但是我加上之后返回的Flowable确实变成了io线程，但是Converter里面抛的错都不会被Subscriber接收了？？？？
文档里面对于线程和错误排除的说明基本没有，希望能完善下

**Comment by jeasonlzy** [comment]
1. AdapterParam的本意是控制你希望是使用okhttp的同步方式（也就是execute方法请求网络），还是希望使用异步方式（也就是enquene方法请求网络）

2. 但是okgo对okhttp的enquene方法做了包装，所有异步回调处于主线程，也就导致了如果你使用同步方式请求网络，rx的所有回调（onNext，onError，onComplete三个方法）默认是在网络请求的子线程的，而如果使用异步的请求方式，rx的回调全部默认在主线程的。

3. 无论是使用同步方式，还是异步方式请求，converter的转换异常都会导致回调onError

4. 文档后期会慢慢完善。。。

5. 感谢支持。
