### ISSUE TITLE
接口调用

### ISSUE THREAD

**Issue by xymorlLd** [jeasonlzy/okhttp-OkGo#396]
如果一个类里面有几个接口调用网络请求.如何判断是哪一个接口调用的呢?

**Comment by jeasonlzy** [comment]
一个接口创建一个callback，不需要判断。。

**Comment by xymorlLd** [comment]
我是把okgo当成了基类同时进行了公共方法的抽取.把success里面的返回值放到了一个方法里面.如果多个接口调用数据都是在同一个方法中提取.那么就无法判断是那个接口调用的了?如果用请求码的话就可以进行区分.但是没有找到就问一下看看有没有内置的方法进行区分

**Comment by jeasonlzy** [comment]
抽取基类可以抽，但是你每个接口的业务逻辑是基本没有关联的，干嘛要把callback复用呢？哪里需要callback就传递一个callback

**Comment by JeremyHwc** [comment]
我也遇到这个问题了，只是个人习惯在一个页面需要请求多个接口时，不太想每一个回调都new一个CallBack 然后就想抽取，把同个页面的网络请求返回到同一个方法里面，用请求码来区分

**Comment by jeasonlzy** [comment]
我不建议这么做，也没必要这么做，就算你把业务代码写在一个callback又能怎么样呢？不同的接口他们的逻辑还是不一样，callback里面还是要区分。。还不如一个接口一个callback
