### ISSUE TITLE
3.0版本的数据与2.0版本的数据是通用的吗？

### ISSUE THREAD

**Issue by hongyang51** [jeasonlzy/okhttp-OkGo#397]
2.0的数据会迁移到3.0吗？
是否毁灭性升级？
求帮助啊

**Comment by jeasonlzy** [comment]
不知道你说的数据指什么。。。

如果你是说是否解析服务端数据有区别，那是基本没区别的

不过3.0的api方法与2.0的api接口很多不一样了。。所以如果没有自己包装过，直接升级，量还是很大的。。

**Comment by hongyang51** [comment]
@jeasonlzy 谢谢您的回复 我的意思是 下载中 下载完成 那些数据库数据是否保存 以前是用的 2.0  就是升级到 3.0 之后是否 进入下载管理还有旧版数据显示。

**Comment by jeasonlzy** [comment]
没有显示。数据库表和字段都修改了，老数据会删除。。
