### ISSUE TITLE
添加公共参数为时间时，是否是在拦截器中去做？

### ISSUE THREAD

**Issue by itdais** [jeasonlzy/okhttp-OkGo#398]
现在公司需求是请求头有参数time，动态的肯定不能直接写在初始化中，是否是在okhttp拦截器中去操作

**Comment by jeasonlzy** [comment]
在 callback 的onstart 方法中即可。可以自定义一个基类的callback

**Comment by itdais** [comment]
嗯 用了！因为我还要做md5处理 我用拦截器完成了
