### ISSUE TITLE
rx方法中300以上异常的处理

### ISSUE THREAD

**Issue by bobingxin** [jeasonlzy/okhttp-OkGo#400]
![image](https://user-images.githubusercontent.com/3241059/29061391-48b67206-7c50-11e7-87f9-4b2a7ea55cc1.png)
大于300的方法直接抛出别的异常了。
这里让后面捕获不到http的异常，希望作者给解决一下。

**Comment by jeasonlzy** [comment]
看起来是 2.x 的版本的代码。。。这些已经在 3.x 版本删除了。。建议升级到 3.x 版本。。

**Comment by bobingxin** [comment]
是2.x的代码，那我升级3.x试试吧。
