### ISSUE TITLE
post需要提交数组[]乱码

### ISSUE THREAD

**Issue by dyfan** [jeasonlzy/okhttp-OkGo#403]
您好.服务器让移动端解码,传输格式是user[1][name]=133;
但是中括号为编码,有什么方法避免吗

**Comment by jeasonlzy** [comment]
有，只能改源码，改一行。。 HttpUtils 类中有这个方法，将 bodyBuilder.add 改成bodyBuilder.addEncoded 即可。。。

![image](https://user-images.githubusercontent.com/13421975/29203177-6f800458-7ea1-11e7-89e9-5104364a48a0.png)

**Comment by jeasonlzy** [comment]
这个改动将会在 3.0.5 版本中加上。。

**Comment by cccfly-bake** [comment]
好的，那我暂时先让服务器解码,多谢.期待新版本
