### ISSUE TITLE
自定义RequestBody

### ISSUE THREAD

**Issue by yemh111** [jeasonlzy/okhttp-OkGo#406]
您好,我使用自定义RequestBody+put方法来上传文件,上传成功后再打开上传文件列表,prograss.request为null
 RequestBody requestBody = RequestBody.create(parse, file);

                            long length = file.length();
                            PutRequest<String> request = OkGo.<String>put(url + "transfer/objects?isoverwrite=true", requestBody)
                                    .headers("accesskey", BaseUtils.getAccessKey())
                                    .headers("token", BaseUtils.getToken())
                                    .headers("remotename", remotePath)
                                    .headers("Content-Length", length + "")
                                    .params("fileKey" + i, file)
                                    .converter(new StringConvert());
                            OkUpload.request(length, path, request)
                                    .priority(i)
                                    .extra1(item)
                                    .fileName(fileName)
                                    .register(null)
                                    .start();

okgo里面我给put请求加了一个requestbody的参数
 /**
     * put请求
     */
    public static <T> PutRequest<T> put(String url, RequestBody requestBody) {
        return new PutRequest<>(url, requestBody);
    }

然后在PutRequest中调用了 upRequestBody(requestBody);
public class PutRequest<T> extends BodyRequest<T, PutRequest<T>> {

    public PutRequest(String url,RequestBody requestBody) {
        super(url);
        upRequestBody(requestBody);
    }

    @Override
    public HttpMethod getMethod() {
        return HttpMethod.PUT;
    }

    @Override
    public Request generateRequest(RequestBody requestBody) {
        Request.Builder requestBuilder = generateRequestBuilder(requestBody);
        return requestBuilder.put(requestBody).url(url).tag(tag).build();
    }
}

麻烦帮我看看是什么问题导致的,谢谢了

**Comment by jeasonlzy** [comment]
可能是序列化问题，不序列化没法存入数据库。。

**Comment by yemh111** [comment]
那我需要修改哪一块呢,如果不使用自定义requestbody我上传的文件会出现损坏打不开.乱码等情况,所以改为自定义的requestbody,RequestBody requestBody = RequestBody.create(parse, file);
