### ISSUE TITLE
用FileCallBack回调无法监听下载进度

### ISSUE THREAD

**Issue by UltramanTIGA** [jeasonlzy/okhttp-OkGo#408]
下载过程中downloadProgress不回调，直到文件下载完成后才会回调到downloadProgress

**Comment by jeasonlzy** [comment]
拦截器问题，关闭 chuck拦截器，关闭日志拦截器。。

**Comment by cd-butterfly** [comment]
不用关闭，调整Interceptor的调用顺序就可以。
.addInterceptor(loggingInterceptor)
.addInterceptor(new FileDownloadInterceptor())

**Comment by DotMatrixDev1024** [comment]
那在拦截器中写了逻辑怎么处理这个问题
