### ISSUE TITLE
OkGo 使用Rxjava2方式获取数据 解析出现 java.lang.Class cannot be cast to java.lang.reflect.ParameterizedType

### ISSUE THREAD

**Issue by tancolo** [jeasonlzy/okhttp-OkGo#415]
参考OkGo 作者提供的wiki 如何自定义（优化JsonCallback）： https://github.com/jeasonlzy/okhttp-OkGo/wiki/JsonCallback。 其中提到 “JsonCallback继续优化” 这小节。 在实际开发过程中我们是使用统一的数据格式。按照作者的提示，修改了为我们具体的JsonConvert.java。 

这里有个小坑，以上完成后，在使用okgo rxjava2方式调用 的时候，需要注意convert的写法。
作者在 https://github.com/jeasonlzy/okhttp-OkGo/wiki/OkRx 问题具体的例子是 
![StringConvert](https://camo.githubusercontent.com/dc77648786c8c1e68bb4e8440298f8c6f3a18219/68747470733a2f2f7773322e73696e61696d672e636e2f6c617267652f303036744e6252776c79316667693970666b6965396a33313075303571337a6b2e6a7067)

如何使用优化后的JsonCallback ， 以作者提供的 Demo为例
```
OkGo.<LzyResponse<List<ServerModel>>>get(Urls.URL_JSONARRAY)//
                .headers("aaa", "111")//
                .params("bbb", "222")//
                .converter(new JsonConvert<LzyResponse<List<ServerModel>>>() {})//
                .adapt(new ObservableBody<LzyResponse<List<ServerModel>>>())//
```
**其中的 converter(new JsonConvert<LzyResponse<List<ServerModel>>>() {})** 一定要加 {} 
否则会报 java.lang.Class cannot be cast to java.lang.reflect.ParameterizedType 错误！

所以，这里建议后来者，最好直接阅读源码，wiki毕竟是作者一个人在维护，并没有把 
```
new JsonConvert<LzyResponse<List<ServerModel>>>() {}
```
这种复杂的实例写出来， 而我是直接参见wiki 所以没有注意这个细节。
这里写出来，让后来者，少点卡壳。
谢谢！

**Comment by chengxingen** [comment]
看到你这个那我也来分享一下吧
文件上传，作者给出的范例使用是如下方式：
PostRequest<String> postRequest = OkGo.<String>post(Urls.URL_FORM_UPLOAD)//
                        .headers("aaa", "111")//
                        .params("bbb", "222")//
                        .params("fileKey" + i, new File(imageItem.path))//
                        .converter(new StringConvert());

但是大多数情况下，文件上传会返回bean，那此处修改如下：
PostRequest<Bean> postRequest = OkGo.<Bean>post(Urls.URL_FORM_UPLOAD)//
                        .headers("aaa", "111")//
                        .params("bbb", "222")//
                        .params("fileKey" + i, new File(imageItem.path))//
                        .converter(new JsonConvert(){});
修改点 ：StringConvert -> JsonConvert
此处强调：new JsonConvert() 需加 {}，即传入参数为new JsonConvert(){};，如果不加{}，也会抛出java.lang.Class cannot be cast to java.lang.reflect.ParameterizedType，导致解析失败；

谢谢！
