### ISSUE TITLE
可以获取到RawResponse的ResponseBody里面的body内容吗

### ISSUE THREAD

**Issue by xj999** [jeasonlzy/okhttp-OkGo#420]
想问下如何获取到这里面的body内容  我们的服务端把异常信息丢到这里面了   客户端okgo连接走了onerror 但是取不出里面的body
![image](https://user-images.githubusercontent.com/5276662/29593667-5c50ed8e-87de-11e7-9e34-2ddd7021bb08.png)

**Comment by jeasonlzy** [comment]
服务器500。。。

**Comment by ypf168326** [comment]
我想问的是，如果服务端返回500，response中是无法获取错误数据吗？
