### ISSUE TITLE
 request.params("data", result);这种result中带有"+"号的话会被转成空格怎么回事呢？

### ISSUE THREAD

**Issue by minmei** [jeasonlzy/okhttp-OkGo#421]
result：fxI6/qbuYCSz5JmLD+pgW5md4SRvFWxViGfkDpQHfK06WPMHGgeNLCTH8QTll+TraJEX9nNZ1DQ+d05WagWm22qIf/0nBXOJbE6DMMxJ16i+yDrtC+BPIJ5PeRiIGR02bPq6agMbHgMATJTkGqfogdfZ9uRtBViBM4gOywqq1dxwqFACAY6wrB0QxV/9r77ulzeCVsnVfjk59C8/lQauId3KUPE3Qu231mA08mWnW5JxdLC7J4Pa6S6LNbKXZu7zq9af+AdJ5LFqWsiSjoEJz4G+/IU3LdP7IAu8uDQJ/1cBUn9nWTn8WeOHYq/+Lx4AMdah3uW7eaZjCQ71m+IvOA==

后台接收到的：fxI6\/qbuYCSz5JmLD pgW5md4SRvFWxViGfkDpQHfK06WPMHGgeNLCTH8QTll TraJEX9nNZ1DQ d05WagWm22qIf\/0nBXOJbE6DMMxJ16i yDrtC BPIJ5PeRiIGR02bPq6agMbHgMATJTkGqfogdfZ9uRtBViBM4gOywqq1dxwqFACAY6wrB0QxV\/9r77ulzeCVsnVfjk59C8\/lQauId3KUPE3Qu231mA08mWnW5JxdLC7J4Pa6S6LNbKXZu7zq9af AdJ5LFqWsiSjoEJz4G \/IU3LdP7IAu8uDQJ\/1cBUn9nWTn8WeOHYq\/ Lx4AMdah3uW7eaZjCQ71m IvOA==

也就是说部分字符被转义了，麻烦。多谢！

**Comment by jeasonlzy** [comment]
get 请求的参数，会自动被编码。。url 中不允许出现 + 号。
