### ISSUE TITLE
如何用Get方式发送json数据

### ISSUE THREAD

**Issue by artem-2024** [jeasonlzy/okhttp-OkGo#422]
post方式可以.upJson(json)，请问get方式怎样发送json？

**Comment by jeasonlzy** [comment]
get请求的参数只能放在url中，使用params方法就行。。

**Comment by artem-2024** [comment]
php同事的所有接口都要求我传递参数时都把参数作为json发送，我用OkGo框架post方式.upJson（）是可以的， 但是有些接口是Get方式，Post方式他不接收， 所以我不知道怎么用get方式传递json数据

以下方法我都试了 还是不行
 OkGo.<JSR_NEW<List<JSRE_NEW>>>get(Api.BASE_URL_NEW+"/migrate/user/"+Api.UID+"/withdraws")
                .tag(this)
                //.isSpliceUrl(true)
                //.headers("body",obj.toString())
                //.upJson(obj)
                //.params("page",index)
                //.params("scale",5)
                //.generateRequest(RequestBody.create(MediaType.parse("application/json; charset=utf-8"),obj.toString()))

**Comment by jeasonlzy** [comment]
这个问题你需要问你服务端怎么接。。凡是满足http协议的传参方式都是可行的。

**Comment by FengZelin** [comment]
请问使用okgo中的get请求传body参数这个问题解决了嘛？如何解决的？麻烦大神沟通告知一下
