### ISSUE TITLE
日志颜色无法更改成ERROR红色？

### ISSUE THREAD

**Issue by RuanJH** [jeasonlzy/okhttp-OkGo#423]
如题，2.X的版本，日志是error,颜色是红色，容易辨别，但是现在好像无法设置了，请问有方法可以设置吗

**Comment by yihuyixi** [comment]
studio里面可以设置 ctrl+alt+s -> 搜索Android Logcat->Use inherited attributes取消勾选后可以设置颜色

**Comment by RuanJH** [comment]
我不是说设置编辑器的日志颜色，因为error本身自带是红色的，所以好奇为什么其他都有，error这种日志输出在okgo不让更改

**Comment by jeasonlzy** [comment]
取消了红色级别。因为有太多的人认为红色是错误。。所以取消了。。
