### ISSUE TITLE
up系列可不可以多个共存?

### ISSUE THREAD

**Issue by keaitao0321** [jeasonlzy/okhttp-OkGo#425]
比如我upJson的同时upFile,我需要在上传图片的时候添加请求参数,但是不能以表单上传

**Comment by jeasonlzy** [comment]
不可以。详细看文档。

https://github.com/jeasonlzy/okhttp-OkGo/wiki/%E4%BC%A0%E5%8F%82%E4%B8%8E%E6%8A%93%E5%8C%85%EF%BC%88%E5%BF%85%E7%9C%8B%EF%BC%89
