### ISSUE TITLE
关于取消请求的问题

### ISSUE THREAD

**Issue by SmallTony** [jeasonlzy/okhttp-OkGo#432]
我在一个界面有很多的网络请求，我有时需要取消其中的某一个，这个时候我就不能用context作为取消的tag，我使用的是一个特定的字符串，比如说我设置了一个tag是：“CANCELTAG”，然后取消的时候我直接这样调用：OkGo.getInstance().cancelTag(“CANCELTAG”); 这样能成功的取消请求吗？
不知道是不是由于网速比较快的原因，我每次点击取消了他还是有响应成功的回调。再加上并没有取消的回调然我知道我取消请求有效果了，所以我就想知道这样子用字符串的方式来作为ta能否真的取消请求？

**Comment by jeasonlzy** [comment]
就是这么用的。取消请求没有任何回调就对了。。还有回调就有问题。
