### ISSUE TITLE
在图片上传过程中获取request为null

### ISSUE THREAD

**Issue by klzhong69** [jeasonlzy/okhttp-OkGo#433]
图片上传过程中，通过uploadProgress回传的progress.request为null，我需要在uploadProgress获取parm怎么办

**Comment by jeasonlzy** [comment]
onstart 中获取 request对象，保存成成员变量

**Comment by klzhong69** [comment]
多张图片分开上传时，保存成成员变量会有问题啊

**Comment by klzhong69** [comment]
解决了 在回调方法里定义成员变量

**Comment by klzhong69** [comment]
谢谢
