### ISSUE TITLE
文件上传post 变 get 问题

### ISSUE THREAD

**Issue by YangMian** [jeasonlzy/okhttp-OkGo#434]
上传文件代码：
 OkGo.<String>post(URLConfig.UPLOAD_FILE)
                    .tag(this)
                    .upFile(file)
                    .execute(new StringCallback() {
                        @Override
                        public void onSuccess(Response<String> response) {
                            LogUtils.e("上传文件", response.body().toString());

                        }

                        @Override
                        public void onError(Response<String> response) {
                            LogUtils.e("上传文件onError", response.code());
                        }
                    });

结果后台返回 There was an unexpected error (type=Method Not Allowed, status=405).
Request method 'GET' not supported

我上传文件用的是post, 但后台那边接受到却是get请求。这是怎么回事呢？

**Comment by jeasonlzy** [comment]
可能服务端的问题。。多和服务端沟通。。

或者你可以抓包确定 当前请求是不是真的变成了 get。。不过应该不可能。。
