### ISSUE TITLE
okgo的.params方法为什么不支持传入Map<String,Object>类型的参数,或者其他扩展类型

### ISSUE THREAD

**Issue by guochuanpei** [jeasonlzy/okhttp-OkGo#437]
![qq 20170904202809](https://user-images.githubusercontent.com/24664660/30026529-dda9102a-91af-11e7-9bb3-840a9ca0c7d5.png)

**Comment by jeasonlzy** [comment]
规范参数类型。。要是object 是个其他对象，我如何上传参数？

**Comment by guochuanpei** [comment]
好的 谢谢

**Comment by chenkexu** [comment]
@guochuanpei 怎么传递list或者map
