### ISSUE TITLE
自定义jsonCallback

### ISSUE THREAD

**Issue by AIlll** [jeasonlzy/okhttp-OkGo#438]
如何让onSuccess直接返回解析后的bean对象，而不是Response对象呢

**Comment by keaitao0321** [comment]
我也想知道

**Comment by jeasonlzy** [comment]
在原有的 JsonCallback 基础上重写 onSuccess 方法即可。。

![image](https://user-images.githubusercontent.com/13421975/30091489-68931a36-92ec-11e7-8f7b-63aabed3ed8c.png)

**Comment by keaitao0321** [comment]
谢谢,

**Comment by AIlll** [comment]
谢谢，再请教一个问题，就是外层套了一层基础包装 如LzyResponse，如何在onSuccess去掉这一层包装呢 @jeasonlzy

**Comment by jeasonlzy** [comment]
@AIlll 上面的回复就是啊。。

**Comment by zhuweiyi** [comment]
@jeasonlzy  3.0.4里面没有 JsonCallback 这个类把

**Comment by jeasonlzy** [comment]
这是自定义的。。
