### ISSUE TITLE
okgo如何修改请求头

### ISSUE THREAD

**Issue by ym666** [jeasonlzy/okhttp-OkGo#457]
在上传json字符串的时候，跟服务端请求头不一致，导致乱码。我这边是默认的	Content-Type: application/x-www-form-urlencoded，服务端是	Content-Type: application/json;charset=UTF-8

**Comment by jeasonlzy** [comment]
使用upJson() 方法，多看文档   https://github.com/jeasonlzy/okhttp-OkGo/wiki/%E4%BC%A0%E5%8F%82%E4%B8%8E%E6%8A%93%E5%8C%85%EF%BC%88%E5%BF%85%E7%9C%8B%EF%BC%89

**Comment by fangood** [comment]
就是不支持修改Content-Type吗
