### ISSUE TITLE
使用里面自带的自定义CallBack例如StringCallBack会报错.求助一下.

### ISSUE THREAD

**Issue by zhuzheng1991** [jeasonlzy/okhttp-OkGo#459]

**Comment by zhuzheng1991** [comment]
感觉是as编译的问题 ..

**Comment by zhuzheng1991** [comment]
已解决

**Comment by wuxingtianxia** [comment]
请问一下怎么解决的

**Comment by codeex** [comment]
哎，这人啊，就不能贴下代码。

调用时增加 <**String**>

`
OkGo.<String>post(url.toString())
                            .tag(this)
                            .upJson(reqContent)
                            .execute(callback);
`
