### ISSUE TITLE
okgo请求回来的json数据很大的时候，显示为null，怎么解决？

### ISSUE THREAD

**Issue by AweiLoveAndroid** [jeasonlzy/okhttp-OkGo#462]
okgo请求回来的数据大的时候，显示为null,
但是我用原生okhttp去请求是没问题的
请楼主解决一下这个问题。

**Comment by jeasonlzy** [comment]
这个理论上是不存在问题的。。很有可能是你的 convertResponse 中的代码有问题。。注意多查看。。
