### ISSUE TITLE
Okgo封装单列模式怎么封装

### ISSUE THREAD

**Issue by Chenshuai770** [jeasonlzy/okhttp-OkGo#463]
作者你好,目前我用的是okgo,使用的时候有时候同一个页面会出现多个post网络请求,但后台只支持params的参数形式,不支持map集合,我不知道怎么封装,,求大神给个列子,讲讲okgo的封装

**Comment by Tomdoog** [comment]
zz

**Comment by Tomdoog** [comment]
我也不会

**Comment by mmdet** [comment]
params的参数形式,和map集合不是一回事吗
