### ISSUE TITLE
upFile这个方法不能上传多张图片?

### ISSUE THREAD

**Issue by keaitao0321** [jeasonlzy/okhttp-OkGo#464]
现在的后台上传文件都不在支持表单上传,需要以二进制流的形式上传?请问要怎么实现?

**Comment by jeasonlzy** [comment]
建议看 文档  ，你就不会有疑惑了。。

https://github.com/jeasonlzy/okhttp-OkGo/wiki/%E4%BC%A0%E5%8F%82%E4%B8%8E%E6%8A%93%E5%8C%85%EF%BC%88%E5%BF%85%E7%9C%8B%EF%BC%89
