### ISSUE TITLE
不能取消请求,怎么解决啊?

### ISSUE THREAD

**Issue by 282167361** [jeasonlzy/okhttp-OkGo#466]
那如果网络不好想返回上一个界面,却在一直Loading,按返回没反应,怎么办啊?

**Comment by jeasonlzy** [comment]
这个应该是自己逻辑上的问题。。多看看自己的代码。。如果是okgo的取消，请看文档。。

https://github.com/jeasonlzy/okhttp-OkGo/wiki/OkGo#9%E5%8F%96%E6%B6%88%E8%AF%B7%E6%B1%82
