### ISSUE TITLE
是否可以自定义请求头中的User-Agent?

### ISSUE THREAD

**Issue by jayleco** [jeasonlzy/okhttp-OkGo#472]
我需要使用iphone的User-Agent去请求一个web页面，请问可以自定义User-Agent的参数为

> Mozilla/5.0` (iPhone; CPU iPhone OS 8_0_2 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12A366 Safari/600.1.4

吗？请问具体如何实现呢？

**Comment by jeasonlzy** [comment]
![image](https://user-images.githubusercontent.com/13421975/31003759-f45c9052-a4b6-11e7-8b19-76cc54ac14ce.png)
可以，就这么传一个header就行。。

**Comment by fangood** [comment]
Okgo返回这个
LzyResponse{
	code=0
	msg='Content type 'application/x-www-form-urlencoded' not supported'
	data=null
}
