### ISSUE TITLE
下载一个40多兆的apk,80%的概率会下载中途中失败...

### ISSUE THREAD

**Issue by olysa** [jeasonlzy/okhttp-OkGo#487]
下载一个40多兆的apk,80%的概率会下载中途中失败...报java.net.SocketTimeoutException异常
就是okgo，基本的下载用法，会失败。不是okServer

**Comment by olysa** [comment]
就是okgo，基本的下载用法。不是okServer

**Comment by LiLingS** [comment]
我也是这样，有概率会发生
