### ISSUE TITLE
公司后端一个接口返回三种json数据格式，问你怎么办？

### ISSUE THREAD

**Issue by fansangg** [jeasonlzy/okhttp-OkGo#510]
`{
  "msg": {
    "mobile": "mobile规则错误",
    "recond_mobile": "recond_mobile规则错误"
  },
  "error_code": 10000,
  "datas": null
}
`

`{
  "msg": {
    "id_card": "id_card规则错误"
  },
  "error_code": 10000,
  "datas": null
}
`
`{
  "msg": "该用户已存在",
  "error_code": "391006",
  "datas": null
}
`

**Comment by fansangg** [comment]
我是把后台揍一顿然后叫他改还是有什么神奇的解决办法？

**Comment by DevXue** [comment]
@fansangg   这很无解啊 ，  我也遇到这情况了，  刚开始用泛型··    可是处理起来 还是很坑啊，  让他改吧！！！

**Comment by shengguan** [comment]
这个可以吧，创建类的时候用合集创建，缺一样都会报错
