### ISSUE TITLE
自定义CallBack时重写onError拦截不到异常

### ISSUE THREAD

**Issue by q296494327** [jeasonlzy/okhttp-OkGo#513]
最近使用OKGo想对服务器返回数据解析以及错误统一处理,然后重写onError时发现我自己抛的异常能拦截到,但是本身的连接超时或者无法连接到HOST等的异常不会走这个回调,我把OKGO初始化时的超时时间改为了1毫秒,结果这个超时异常日志有打印,但是没有走onError方法,以下是我复写的代码,

public abstract class JsonCallBack<T> extends AbsCallback<T> {
    @Override
    public T convertResponse(okhttp3.Response response) throws Throwable {
        ResponseBody body = response.body();
        if (body == null)
            return null;

        //解析出当前类的父类上的泛型的真实泛型
        Type genType = getClass().getGenericSuperclass();
        Type type = ((ParameterizedType) genType).getActualTypeArguments()[0];

        //创建Gson，直接从流解析成对象
        Gson gson = new Gson();
        JsonReader jsonReader = new JsonReader(body.charStream());

        T result = gson.fromJson(jsonReader, type);

        if (result instanceof BaseResponse) {
            BaseResponse baseResponse = (BaseResponse) result;
            if (baseResponse.isOK()) {//请求成功
                return result;
            } else {//请求失败
                throw new ServerException(baseResponse.getResult(), baseResponse.getError());
            }
        } else {
            throw new ServerException(0, "JaveBean请继承BaseResponse");
        }
    }

    @Override
    public void onSuccess(Response<T> response) {
        onSuccess(response.body());
    }

    @Override
    public void onError(Response<T> response) {
        //        super.onError(response);
        Throwable exception = response.getException();
        //处理异常
        ExceptionHandle.ResponeThrowable responeThrowable = ExceptionHandle.handleException(exception);
        onError(responeThrowable);
    }

    /**
     * 成功回调
     */
    protected abstract void onSuccess(T response);

    /**
     * 错误/异常回调
     */
    protected abstract void onError(ExceptionHandle.ResponeThrowable e);

}

**Comment by q296494327** [comment]
后面找到原因了,是因为一直在读缓存

**Comment by wenfengtou** [comment]
好吧 解决我问题了，我网络都没打开，去访问，居然也不返回onError，感觉有毒。

**Comment by zzzsssbo** [comment]
@wenfengtou  我也是这样的 你是怎么解决的
