### ISSUE TITLE
OkRx2 subscribeOn()切换线程无效?

### ISSUE THREAD

**Issue by sumaro** [jeasonlzy/okhttp-OkGo#573]
OkGo.<String>get(url)
        .converter(new StringConvert())
        .adapt(new FlowableResponse<String>())
        .subscribeOn(Schedulers.io())切换线程无效?
        .compose(getFlowableTransformer())在getFlowableTransformer()执行的操作为啥都是在main Thread中,getFlowableTransformer()中我没有执行线程切换操作,还是我使用rxjava2的方式有误吗？

**Comment by mxruan** [comment]
一样 你解决了没？  求解！
