### ISSUE TITLE
怎么全局配置2个实例化对象

### ISSUE THREAD

**Issue by onebee** [jeasonlzy/okhttp-OkGo#613]
怎么全局配置2个实例化对象,自己的服务器是https ,另外还有三方服务器. 怎么初始化2个实例对象. 一个用于自己服务器 https 的请求, 另一个用于三方服务器http的请求

**Comment by cervy** [comment]
可以并发

**Comment by onebee** [comment]
并发指的是? 不用单独实例化2个?
