### ISSUE TITLE
OkDownload强杀进程，断点信息没有了，从头开始下载了

### ISSUE THREAD

**Issue by sundyli** [jeasonlzy/okhttp-OkGo#616]
compile 'com.lzy.net:okgo:3.0.4'
compile 'com.lzy.net:okserver:2.0.5'
OkDownload强杀进程，断点信息没有了，从头开始下载了，请问此问题怎么修改？

**Comment by rcj605600** [comment]
@sundyli  我也遇到了类似问题 我把下载好的apk 删除了 然后点击下载按钮  error 状态值为4

**Comment by sundyli** [comment]
问题已解决

**Comment by blueskky** [comment]
> 问题已解决
请问怎么解决的啊
