### ISSUE TITLE
Rx 方法 使用缓存

### ISSUE THREAD

**Issue by zhaoxiuyu** [jeasonlzy/okhttp-OkGo#63]
用Rx的方式请求网络   如何使用缓存呢。

**Comment by oubowu** [comment]
使用RxCache这个库 @zhaoxiuyu

**Comment by asker517** [comment]
@jeasonlzy Rx方式请求,这个库提供的缓存方式不能配合使用?

**Comment by jeasonlzy** [comment]
目前是rx是不支持缓存的，这个功能 预计 2.2 版本会增加。

**Comment by asker517** [comment]
@jeasonlzy would be so nice~~looking forward 👍

**Comment by loganguo** [comment]
我也想提这个需求呢，看到这里已经有人提了。由于其他的网络请求都是Rx方式请求的，而且做了一层封装，为了支持缓存封装的用不上了。文件上传也有类似情况。希望@jeasonlzy您可以尽快解决。

**Comment by andansky** [comment]
+1

**Comment by jeasonlzy** [comment]
okgo3.0 发布，增加rxjava2的支持，rx同时支持缓存。。欢迎下载体验。。
