### ISSUE TITLE
下载回调 progress.fraction 和progress.totalSize  数值错误

### ISSUE THREAD

**Issue by canglen** [jeasonlzy/okhttp-OkGo#636]
下载demo 打印log无问题
Progress{fraction=0.8637884, totalSize=2197934, currentSize=1898550, speed=514407, status=2
自己的打印出来 fraction 文件的size  totalSize = -1.
Progress{fraction=-1731980.0, totalSize=-1, currentSize=1731980, speed=1828401, status=2
如果有大佬看到的话帮忙解决一下，或者看是什么问题。
as版本 3.0.1  gradle 4.1  引入okgo版本为3.0.4最新版
问题解决，接口问题。

**Comment by liang979zhang** [comment]
请问你怎么解决的?
