### ISSUE TITLE
在没有网络的情况下提示个Toast该在哪个地方判断添加呢？

### ISSUE THREAD

**Issue by MushroomLqy** [jeasonlzy/okhttp-OkGo#65]

**Comment by MushroomLqy** [comment]
可以在before回调里面先判断网络的状态然后再进行之后的操作吗

**Comment by jeasonlzy** [comment]
无网络的状态判断理论上不应该在网络请求的过程中，而应该在网络请求之前。。
第一种方法：你应该在调用请求之前先判断好网络环境。。
第二种方法：在onAfter 中根据异常类型（无网络的异常应该是 ConnectException ），根据这个可以判断操作。。

**Comment by MushroomLqy** [comment]
明白了
