### ISSUE TITLE
您好，关于缓存，我单个接口接口中设置缓存时间

### ISSUE THREAD

**Issue by sunjie798893816** [jeasonlzy/okhttp-OkGo#66]
情况是这样的，我在application设置缓存模式是没有网络读缓存，有网络走服务器，然后为个别接口设置了缓存时间，设置了1毫秒。我是这样测试的，第一次有网。从服务器获取数据，做缓存。断开网络，这回缓存应该过期了，但是他还是读取出来了数据。

//application中
private void initHttpModule() {
        OkGo.init(this);
        OkGo.getInstance()
                .debug("Ecs")
                .setCacheMode(CacheMode.REQUEST_FAILED_READ_CACHE);
    }

//fragment中
String postData =  CipherUtils.encode(jsonObject);
        HttpUtils.post("http://weixin.1000jd.com/home/parts/listParts", postData, cacheTime, new StringCallback() {
            @Override
            public void onSuccess(String s, Call call, Response response) {
                Log.i("Ecs",s);
            }

```
        @Override
        public void onError(Call call, Response response, Exception e) {
            Log.i("Ecs","Error" + e.getMessage());
        }
    });
```

**Comment by jeasonlzy** [comment]
感谢。。确实存在这个问题。。目前只有 REQUEST_FAILED_READ_CACHE 这个模式下，对缓存时间的控制有点问题，其他模式都正常，代码我在本地已经修复，最近几天将会和其他小修复一并发布一个小版本。。

**Comment by zyfAnd** [comment]
6666

**Comment by jeasonlzy** [comment]
2.1 版本已经修复。。
