### ISSUE TITLE
https 全局证书校验

### ISSUE THREAD

**Issue by LayneCui** [jeasonlzy/okhttp-OkGo#662]
现在遇到一个问题：在 Application 中加了hpps 证书校验，但是在微信绑定时，因为使用了全局的 okgo 客户端导致 https 请求微信服务器失败，请问能在单独接口，取消证书校验吗？

**Comment by zhangxin17610860215** [comment]
您好    您这个问题解决了么？如果解决了怎么解决的可以说一下么？

**Comment by fasei** [comment]
您好，请问你的问题解决了吗，我也遇到了相同的问题
