### ISSUE TITLE
DownloadManager的状态问题

### ISSUE THREAD

**Issue by wjh3936** [jeasonlzy/okhttp-OkGo#67]
DownloadManager的addTask方法中，会判断DownloadInfo的状态为“无状态”、“暂停”或者“错误”的时候才允许开始下载。
当下载完一个请求之后，同样的Key同样的URL【未测试过Key不同的情况下是否有影响】再次请求下载，如果没有经过Remove操作的话，即使是新生成的DownloadInfo返回的状态依然是FINISH，但此时不会经过DownloadListener的onFinish(DownloadInfo downloadInfo)回调。
由于时间关系，所以只能把目前自己测试到的情况提个issues给你。

**Comment by jeasonlzy** [comment]
行。这个逻辑我在梳理一下。。

**Comment by jeasonlzy** [comment]
okgo升级3.0，okserver进行了重构，这个问题也已经解决了。。欢迎体验。。
