### ISSUE TITLE
OKGO怎么禁用系统的log输出阿

### ISSUE THREAD

**Issue by Ambop** [jeasonlzy/okhttp-OkGo#671]
OKGO怎么禁用系统的log输出阿，感觉现在这样上线会容易泄露数据

**Comment by protectedMan** [comment]
同问

**Comment by QiangZhanghaha** [comment]
loggingInterceptor.setPrintLevel(HttpLoggingInterceptor.Level.NONE);

**Comment by yobdms** [comment]
> loggingInterceptor.setPrintLevel(HttpLoggingInterceptor.Level.NONE);

有没有完整代码，为什么设置了不起作用？

HttpLoggingInterceptor log = new HttpLoggingInterceptor("OkGo");
log.setPrintLevel(HttpLoggingInterceptor.Level.NONE);   
com.lzy.okgo.OkGo.getInstance().setOkHttpClient(com.lzy.okgo.OkGo.getInstance().getOkHttpClient().newBuilder().addInterceptor(log).build());
