### ISSUE TITLE
文件下载时，那个totalSize为什么是-1？

### ISSUE THREAD

**Issue by houyanbing** [jeasonlzy/okhttp-OkGo#672]
@Override
                    public void downloadProgress(Progress progress) {
                        super.downloadProgress(progress);

                        double cu = progress.currentSize;
                        double tot = progress.totalSize;
                        LogUtils.iTag("TAG", cu + "  ---  " + tot);
                    }

如上代码， progress.totalSize打印出来值一直是  -1 ，为什么呢？

**Comment by gxs-gc** [comment]
你好 请问你是如何获取进度的

**Comment by liang979zhang** [comment]
一样获取到的是-1

**Comment by Tanyd31** [comment]
totalSize 和 fraction 都为负数
