### ISSUE TITLE
OKgo的底层请求库能不能替换 。

### ISSUE THREAD

**Issue by chenyang1900** [jeasonlzy/okhttp-OkGo#68]
OKgo的底层请求库能不能替换成HttpURLConnection、HttpClient 或者xutils ...
。 修改容易吗

**Comment by jeasonlzy** [comment]
这个问题问的。。。okgo 是封装的okhttp，okhttp才是和HttpURLConnection，HttpClient平级的底层网络通信库，okgo，xutils，volley，async-http-client，retrofit 等都只是个壳，内部分别封装的上述三个框架。而且一般来说是没有必要替换的，httpclient已经过时了，源码中都被移除了，还要用它干嘛，HttpURLConnection是原生的，但是android4.4以上的源码实现也已经换成了okhttp，所以谷歌源码都用okhttp了，还要换成别的干嘛呢。。。至于xutils，那本来就是封装好的壳，怎么能作为底层。。

**Comment by yihuyixi** [comment]
very good

**Comment by BeingAStrongHong** [comment]
回答得好详细，赞
