### ISSUE TITLE
临时救急解决方案（有需要的请进）

### ISSUE THREAD

**Issue by tuzhao** [jeasonlzy/okhttp-OkGo#682]
我自己的一个项目中在用这个库，但是作者不知道什么原因长时间没有更新了。最近项目一直报一个Okhttp的错误，经查证这个问题在最新版的Okhttp上已经解决了，所以我fork了这个库，更新了一下Okhttp的依赖就解决这个问题了。我也将其上传到了jcenter中了，不需要更改项目中得java导包，只需要替换一下gradle依赖即可。
原：compile 'com.lzy.net:okgo:3.0.4'
现：compile 'org.tuzhao.net:okgo:3.0.6'

另外由于时间有限并没有去上传原库中得okrx，okrx2，okserver这三个库。
如果有小伙伴同时引用了这三个库可以采取下面的方式解决。
    compile('com.lzy.net:okrx2:2.0.2') {
        exclude(group: 'com.lzy.net', module: 'okgo')
    }

扩：我还发现okrx2中得rxjava版本也过时了，和项目中包含的引入rxjava2的官方依赖有dex打包冲突，
也可以采用下面的方式解决。
    compile('com.lzy.net:okrx2:2.0.2') {
        exclude(group: 'io.reactivex.rxjava2', module: 'rxjava')
    }

**Comment by EV71** [comment]
那原来报的什么错误？

**Comment by tuzhao** [comment]
在android 8.0的部分机型上okhttp的底层框架会报下面这个错误：
#5478 java.lang.ClassCastException
android.system.UnixSocketAddress cannot be cast to java.net.InetSocketAddress

libcore.io.IoBridge.getLocalInetSocketAddress(IoBridge.java:700)


1 libcore.io.IoBridge.getLocalInetSocketAddress(IoBridge.java:700)
--
2 libcore.io.IoBridge.connectDetail(IoBridge.java:197)
3 libcore.io.IoBridge.connect(IoBridge.java:138)
4 java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:129)
5 java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:356)
6 java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
7 java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
8 java.net.SocksSocketImpl.connect(SocksSocketImpl.java:356)
9 java.net.Socket.connect(Socket.java:616)
10 okhttp3.internal.platform.AndroidPlatform.connectSocket(Unknown Source:63)
11 okhttp3.internal.connection.RealConnection.connectSocket(Unknown Source:223)
12 okhttp3.internal.connection.RealConnection.connect(Unknown Source:149)
13 okhttp3.internal.connection.StreamAllocation.findConnection(Unknown Source:195)
14 okhttp3.internal.connection.StreamAllocation.findHealthyConnection(Unknown Source:121)
15 okhttp3.internal.connection.StreamAllocation.newStream(Unknown Source:100)
16 okhttp3.internal.connection.ConnectInterceptor.intercept(Unknown Source:42)
17 okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source:92)
18 okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source:67)
19 okhttp3.internal.cache.CacheInterceptor.intercept(Unknown Source:93)
20 okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source:92)
21 okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source:67)
22 okhttp3.internal.http.BridgeInterceptor.intercept(Unknown Source:93)
23 okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source:92)
24 okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(Unknown Source:120)
25 okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source:92)
26 okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source:67)
27 okhttp3.RealCall.getResponseWithInterceptorChain(Unknown Source:185)
28 okhttp3.RealCall$AsyncCall.execute(Unknown Source:135)
29 okhttp3.internal.NamedRunnable.run(Unknown Source:32)
30 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
31 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
32 java.lang.Thread.run(Thread.java:764)

**Comment by NicodeLee** [comment]
建议都自己引用源码吧。

**Comment by tuzhao** [comment]
作者是不是已经放弃了这个项目?

**Comment by JessYanCoding** [comment]
...

**Comment by tuzhao** [comment]
更新了okhttp的依赖到3.11.0，大家有需要的可以使用最新的依赖：compile 'org.tuzhao.net:okgo:3.0.7'

**Comment by bebetter1030** [comment]
强制使用最新依赖可以自己配置的。
在module下的build.gradle配置
```
configurations.all {
    resolutionStrategy {
        force 'com.squareup.okhttp3:okhttp:3.12.0'   // 示例:  强行指定依赖库版本     
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
...
...
}

**Comment by zzzsssbo** [comment]
#5502 java.lang.IllegalArgumentException
Unexpected TLS version: NONE

okhttp3.TlsVersion.forJavaName(TlsVersion.java:53)

这种错呢

**Comment by tuzhao** [comment]
> #5502 java.lang.IllegalArgumentException
> Unexpected TLS version: NONE
> 
> okhttp3.TlsVersion.forJavaName(TlsVersion.java:53)
> 
> 这种错呢

放弃这个项目吧。
