### ISSUE TITLE
请问下okGo支持设置Proxy.NO_PROXY吗？

### ISSUE THREAD

**Issue by xiaoli-style** [jeasonlzy/okhttp-OkGo#685]
okhttp可以设置禁止使用代理访问：
new OkHttpClient().newBuilder().proxy(**Proxy.NO_PROXY**).build();

那么okGo该如何设置呢？

**Comment by cuiwang** [comment]
OkGo.getInstance().getOkHttpClientBuilder().proxy(Proxy.NO_PROXY).build();
