### ISSUE TITLE
Okgo框架下载文件无法获取文件大小及OOM

### ISSUE THREAD

**Issue by plmmmmlq** [jeasonlzy/okhttp-OkGo#692]
测试文件地址：http://1256011383.vod2.myqcloud.com/0b68787dvodgzp1256011383/5f28abd17447398155871426551/E5c9atCtY2EA.mp4

**Comment by plmmmmlq** [comment]
去掉日志拦截器正常

**Comment by gxs-gc** [comment]
我这边去掉拦截器也获取不到大小 总大小是-1
