### ISSUE TITLE
DownloadManager能够自定义异常信息吗？

### ISSUE THREAD

**Issue by EvlinLee** [jeasonlzy/okhttp-OkGo#70]
暂时遇到这种情况，当手机存储空间不足时，提示的是读写异常，对用户来说应该提示手机存储空间不足比较好吧。

**Comment by jeasonlzy** [comment]
确实是这样，后期会优化。但是这种属于业务逻辑，库中也只会提供基本逻辑，并无法兼容所有情况，详细的还是需要修改代码或者自己实现。。

**Comment by EvlinLee** [comment]
@jeasonlzy 自己改了。
还有个问题：下载状态的监听DownloadListener的监听放在adapter中会有问题，当数量多的时候拖动会闪屏，这个监听能放到activity或者fragment，然后通知刷新呢？

**Comment by jeasonlzy** [comment]
可以实现。。但是长时间的下载任务建议使用服务实现。。
