### ISSUE TITLE
使用华为P20和小米5更新版本的时候，下载进度一直为0，使用其他三星S6,7一加5，华为p9都没问题

### ISSUE THREAD

**Issue by Mr-Chen** [jeasonlzy/okhttp-OkGo#705]
ProgressDialog dialog = new ProgressDialog(this);
        dialog.setTitle(getString(R.string.home_updating));  
        dialog.setProgressStyle(ProgressDialog.STYLE_HORIZONTAL); 
        dialog.setCanceledOnTouchOutside(false);
        dialog.setCancelable(false);

        final String path = Environment.getExternalStorageDirectory() + "/kswl/";
        PostRequest<File> request = OkGo.<File>post(apkUrl);

        DownloadTask task = OkDownload.request("newVersion", request)
                .save()
                .folder(path)
                .fileName("app.apk")
                .register(new DownloadListener("newVersion") {
                    @Override
                    public void onStart(Progress progress) {
                        dialog.show()；
                    }

                    @Override
                    public void onProgress(Progress progress) {
                        dialog.setMax((int) progress.totalSize / 1024);
                        dialog.setProgress((int) progress.currentSize / 1024);
                    }

                    @Override
                    public void onError(Progress progress) {
                        progress.exception.printStackTrace();
                    }

                    @Override
                    public void onFinish(File file, Progress progress) {
                        dialog.dismiss();  
                        UpdateHelper.installApp(mActivity, file);

                    }

                    @Override
                    public void onRemove(Progress progress) {

                    }
                });
        task.start();

**Comment by zuowutan** [comment]
大兄弟解决了嘛

**Comment by yuqianglianshou** [comment]
小米11也不行，直接   okGo: <-- HTTP FAILED: java.net.SocketTimeoutException: timeout
