### ISSUE TITLE
严重问题 希望及时解决

### ISSUE THREAD

**Issue by chain911** [jeasonlzy/okhttp-OkGo#71]
public void onSuccess(String s, Call call, Response response) 当我请求的时候，一个对象，服务器返回null，可是success方法里面返回的这个s拿到的是0，意思就是把"cont":null搞成"cont":0了，Gson解析时候报错java.lang.IllegalStateException: Expected BEGIN_OBJECT but was NUMBER at line 1 column 47 path $.response.cont

**Comment by moonljt521** [comment]
围观一下~

**Comment by jeasonlzy** [comment]
交流群中已解决，我使用你提供的接口经测试并没有问题，应该是你其他地方的代码有问题。。

**Comment by chain911** [comment]
嗯嗯 是我们服务器问题 测试服务器对的 线上服务器代码有问题导致的 谢谢


发自 网易邮箱大师
在2016年10月18日 16:14，廖子尧 写道:

交流群中已解决，我使用你提供的接口经测试并没有问题，应该是你其他地方的代码有问题。。
