### ISSUE TITLE
关于版本兼容性问题。

### ISSUE THREAD

**Issue by canglen** [jeasonlzy/okhttp-OkGo#718]
从 com.lzy.net:okgo:2.1.4 更新到最新版本后 com.lzy.net:okgo:3.0.4 
发现com.lzy.okgo.request包下的baseRequest没有了，取代的是com.lzy.okgo.request.base.request
还有AbsCallback 等，好像改动挺多的。
demo也没更新，打开也是报错的，找不到包。

**Comment by wanderwuuu** [comment]
你好，我也遇到了这个问题，请问你解决了吗？
