### ISSUE TITLE
关于连接超时等时间设置

### ISSUE THREAD

**Issue by zengcanxiang** [jeasonlzy/okhttp-OkGo#72]
okhttp本身接受的是long类型,但是okgo接受的却是int类型
![qq 20161020103140](https://cloud.githubusercontent.com/assets/16033497/19544290/7a6d1ba0-96b0-11e6-8209-075103696728.png)

**Comment by jeasonlzy** [comment]
这个没什么影响吧，你会把超时时间设置到 超过 int 的最大值？

**Comment by zengcanxiang** [comment]
不是，因为一般项目中设置都是long类型，设置的时候，要么得转换一下，要么修改之前项目中的变量类型。如果你设置long类型，就能更加兼容不同项目中的代码了。切换为okgo的时候，做更少的修改。

**Comment by jeasonlzy** [comment]
ok。。这问题 我下版本修复。。

**Comment by jeasonlzy** [comment]
2.1 版本已经修复。。
