### ISSUE TITLE
取消请求的回调

### ISSUE THREAD

**Issue by zengcanxiang** [jeasonlzy/okhttp-OkGo#73]
平时的一些get,post请求其实一般情况下不会存在取消，但是我是在用下载的时候，发现，没有取消回调.
如果我取消了这个下载，那么，我应该如果获取OkGo返回给我的 取消成功 信息呢？

**Comment by zengcanxiang** [comment]
而且如果在使用缓存的情况下，下载文件不会使用缓存把？我不用去重写onCache等回调把

**Comment by jeasonlzy** [comment]
下载文件不会走缓存。。取消请求时会立即回调 onFailure，但是我在源码中过滤的 取消请求的回调，原因后很多。。总体就是这样更加符合实际项目需求。。
