### ISSUE TITLE
自定义JsonCallBack回调onSuccess不能打印response.body()

### ISSUE THREAD

**Issue by Spikoss** [jeasonlzy/okhttp-OkGo#732]
public static Observable<ResponseBean> loginRegister(String phone,String code){
        return OkGo.<ResponseBean>post(AppUtils.login)
                .params("phone", phone)
                .params("code", code)
                .converter(new JsonCallBack<ResponseBean>() {
                    @Override
                    public void onSuccess(Response<ResponseBean> response) {
//这里进不来
                        LogUtil.i("AbService",response.body()+"=======");
                    }
                })
                .adapt(new ObservableBody<ResponseBean>());
    }

请问是什么原因？

**Comment by WuShuai11** [comment]
我也遇到了类似的问题，是因为Response.body.content中的数据为空.  ps:接口正常访问，并且可以打印出数据
