### ISSUE TITLE
日志

### ISSUE THREAD

**Issue by zengcanxiang** [jeasonlzy/okhttp-OkGo#74]
我用okhttp官方的HttpLoggingInterceptor和OkGo的对比了下，发现OkGo的没有Cookie.有点不便。
并且因为我看到了 maybe [file part] , too large too print , ignored! ，发现OkGo的判断不应该是 判断 
mediaType.subtype() 与 “application/x-www-form-urlencoded" 相等。 因为一般的情况下，后面会加上;charset=UTF-8 之类的，就通不过判断了，然后返回的一个简单的json，发现也是不会打印出来的。

**Comment by jeasonlzy** [comment]
这个是 log 的打印考虑，可能考虑的不全。但是不影响功能的使用。。下版会调整下。。

**Comment by jeasonlzy** [comment]
2.1 版本已解决。。
