### ISSUE TITLE
上传文件服务器的接受方式能借鉴一下么

### ISSUE THREAD

**Issue by zengcanxiang** [jeasonlzy/okhttp-OkGo#75]
如题，要是使用okgo的方式上传服务器，那么服务器接受的方式有什么区别么，因为之前我们服务器能接受我用xutils上传的文件，但是接受不了我用okhttp上传的文件

**Comment by jeasonlzy** [comment]
没有区别。只要是遵守 Restful 请求规范的都行。。okgo 是严格的 Restful 风格的请求框架。

**Comment by zengcanxiang** [comment]
不是，我的意思是你后台的服务器是怎么写的。。。。

**Comment by jeasonlzy** [comment]
简单的使用servlet接收的。Apache的commons-fileupload开源库。demo后台。。没有使用ssh框架。
