### ISSUE TITLE
OkServer下载文件有日志代码没有删除

### ISSUE THREAD

**Issue by zengcanxiang** [jeasonlzy/okhttp-OkGo#76]
一个是我集成的log，一个是demo的log 都存在这个问题
![qq 20161021102006](https://cloud.githubusercontent.com/assets/16033497/19584587/1c7315cc-9778-11e6-87ea-ce66160bcbab.png)
![qq 20161021102013](https://cloud.githubusercontent.com/assets/16033497/19584592/223c6bde-9778-11e6-83d2-e8b137f822bb.png)

**Comment by zengcanxiang** [comment]
DownloadTask类里面看到的
![qq 20161021102345](https://cloud.githubusercontent.com/assets/16033497/19584640/86ea07bc-9778-11e6-9e28-5391e1ca4ca0.png)

**Comment by jeasonlzy** [comment]
...嗯。。确实忘记删除了。我立即删掉。。

**Comment by jeasonlzy** [comment]
2.1 版本已修复。。
