### ISSUE TITLE
关于请求移除

### ISSUE THREAD

**Issue by zengcanxiang** [jeasonlzy/okhttp-OkGo#77]
恩，使用的时候发现普通请求应该加个cancelAll()方法，只有一个cancel(Tag) 感觉有点不够呢.
还有okServer 上传文件的时候，不像DowmLoadManager有remove方法呢。
就是有一种没有同步的感觉，某个操作在请求，上传，下载都会有的，但是这个类有相关方法进行操作，那个没有，或者是不全。很是蛋疼 -_-

**Comment by jeasonlzy** [comment]
可以。没有问题。。下版本修复。。修复完成我会回复你。。

**Comment by jeasonlzy** [comment]
2.1 已经增加。。欢迎体验。。
