### ISSUE TITLE
post请求的表单变成了unicode加密看不懂啊

### ISSUE THREAD

**Issue by Joplin-DDZ** [jeasonlzy/okhttp-OkGo#774]
![Uploading image.png…]()

**Comment by Joplin-DDZ** [comment]
OkGo: 	body:=%7B%22Page%22%3A%221%22%2C%22SessionId%22%3A%220e5f6e0a-93e9-4e56-8fc8-c0f277381e16%22%2C%22PageSize%22%3A%228%22%7D

**Comment by leegh15** [comment]
请问怎么解决的

**Comment by Joplin-DDZ** [comment]
> 请问怎么解决的

没办法，解码怎么整都不行，后面我直接封装了一个请求参数的HashMap，然后Json打印出来的

**Comment by Jasongq** [comment]
有个方法，你把这串加密过的字符串复制到360浏览器网址栏里，回车就能看到了

**Comment by Joplin-DDZ** [comment]
> 有个方法，你把这串加密过的字符串复制到360浏览器网址栏里，回车就能看到了

这样很麻烦，所以我自己封装了一下
