### ISSUE TITLE
JsonCallBack缓存使用的问题

### ISSUE THREAD

**Issue by DotMatrixDev1024** [jeasonlzy/okhttp-OkGo#775]
JsonCallBack下缓存请问是需要怎么使用的呢，是按照demo的jsoncallback一样的

**Comment by DotMatrixDev1024** [comment]
jsoncallback 缓存不下来

**Comment by Edison0716** [comment]
我也是这个问题

**Comment by DotMatrixDev1024** [comment]
> 我也是这个问题

看你javabean有没有实现Serializable接口 我之前是因为没有实现Serializable接口
