### ISSUE TITLE
关于下载

### ISSUE THREAD

**Issue by zengcanxiang** [jeasonlzy/okhttp-OkGo#78]
okServer下载文件的时候，我通过log测试感觉有点问题。

我在成功的时候打印地址，在进度回调中打印进度。发现，当一个任务使用addTask(filename,tag,request,listener)添加之后，下载完成了，如果没有调用removeTask(tag)方法，不管怎么调用addTask方法都不会启动下载任务，但是调用restartTask(tag)方法却能启动下载任务。

但是，我仿照demo中的写法，downloadManager.getDownloadInfo(taskKey)却是==null的。也就是我无法判断他能否通过addTask方法来启动下载任务。亲测可能性百分百(会不会是我得代码有问题，但是我测试了很多次，对比和demo的代码也没什么差别，也能断点下载 ).

虽然感觉在实际情况下没什么问题，但是这样的话，就会导致某些情况下代码无响应。毕竟，再次下载的蠢事我也干过。。。。

**Comment by jeasonlzy** [comment]
addTask 中有判断。。如果任务已经下载，或者处于等待状态，下载是无效的。详细你看 addtask 的方法的代码就知道了。。而removeTask会将该任务删除，删除后才可以 addTask。

**Comment by zengcanxiang** [comment]
一个任务下载完了不会删除，需要手动删除，是这个意思么？

**Comment by jeasonlzy** [comment]
对。会保留在下载数据库中。。不保留的话，下次进来怎么能知道上次完成下载的是哪些呢。

**Comment by zengcanxiang** [comment]
好吧，谢谢解答了
