### ISSUE TITLE
杠精太多，不适合说话。

### ISSUE THREAD

**Issue by gdky005** [jeasonlzy/okhttp-OkGo#788]
### 参考下 OkHttp 官网。
还有个建议：可以弄两份，喜欢看详细的人，可以慢慢深入。不想看的呢，直接拷贝最原始的代码就行，无需太多，起到演示作用即可。

### 备注下：
之所以吐槽，是真想尝试下，写的再好没啥用，要看结果 Ok？

很多东西简单几句话就能说清楚，为何啰嗦一大堆呢？

恢复下主题。

**Comment by tanzhihao1qaz** [comment]
你是不是用了模拟器去请求？我这边用模拟器是请求失败，但是用真机是没问题。另外很少有这么完善的开源文档，不要打击作者写说明文档的热情。。。

**Comment by tanzhihao1qaz** [comment]
我也不知道什么原因，网络权限是开通的了，一开始我也折腾很久，后来才想起自己的模拟器好像连不上网

**Comment by paulkuai** [comment]
我也觉得是，这么完善的开源文档，难得了。。

**Comment by Youngjim77** [comment]
连自带的StringCallBack都能给你弄错，你也是牛人

**Comment by gdky005** [comment]
> 连自带的StringCallBack都能给你弄错，你也是牛人

你应该看看眼病哦，代码和说明有略微差异，不过两种方式都可以定位到类。说别人之前，请先看下代码，才有资格评论，谢谢。


```

OkGo.get("http://www.baidu.com").execute(new StringCallback() {
            @Override
            public void onSuccess(Response<String> response) {

            }
        });

```

请看这样写对不？  如不对，请附上代码。

**Comment by gdky005** [comment]
> > 连自带的StringCallBack都能给你弄错，你也是牛人
> 
> 你应该看看眼病哦，代码和说明有略微差异，不过两种方式都可以定位到类。说别人之前，请先看下代码，才有资格评论，谢谢。
> 
> ```
> 
> OkGo.get("http://www.baidu.com").execute(new StringCallback() {
>             @Override
>             public void onSuccess(Response<String> response) {
> 
>             }
>         });
> ```
> 请看这样写对不？ 如不对，请附上代码。

@Youngjim77

**Comment by gdky005** [comment]
> 参考下 OkHttp 官网。

**Comment by gdky005** [comment]
伙计们，对事不对人哈。没有吐槽说这个多差，但是这样的文档，真没兴趣看下去，哪有时间看一大堆呢？都开了好多天了，都没见 作者出来说下，这维护性不敢恭维。

**Comment by Youngjim77** [comment]
666  既要用别人的东西，又要吐槽别人，别人一年前就停止维护了，说别人维护不敢恭维，是谁有眼病？？？

**Comment by Youngjim77** [comment]
而且这就是你的对事不对人，8000+的star的项目介绍给你说成是一大堆废话，麻烦你把评论改了回来再来说我好吗

**Comment by gdky005** [comment]
@Youngjim77 你个 SB 杠精，脑残的货，不想跟你瞎扯。 8000+ 就好了？ 你脑子进水了么？ 一年前停止维护？？？  你哪里看到停止维护的？ 真不想骂人，你这没脑子的怼。滚粗

**Comment by Youngjim77** [comment]
![default](https://user-images.githubusercontent.com/26914864/47703356-f592b500-dc5a-11e8-9add-ff838e5e64a3.png)牛逼牛逼

**Comment by gdky005** [comment]
顺带说一句，懒得用，最后也没用。 更正评论，只是为了去除 一些激进的话。

**Comment by Youngjim77** [comment]
![qq 20181030154832](https://user-images.githubusercontent.com/26914864/47703449-4a363000-dc5b-11e8-86bb-6a56741138f0.png)
不用谢，我来教你，而且你别关闭了，心虚没用，关不掉的

**Comment by gdky005** [comment]
@Youngjim77 你个 SB 逼逼啥呢？  哪里写停止维护了？ 



> 连自带的StringCallBack都能给你弄错，你也是牛人

打死也不认错，非要认为自己没错。  看你的眼有病么。


我也是有病，跟你这个说啥？ 都说是杠精了，没事找事的家伙。看不见好的，只能看到。。。

关掉的目的 是不想跟你瞎比比，有空多看看书。

**Comment by Youngjim77** [comment]
那你赶紧闭嘴了好吗，会恶心到我的。

**Comment by gdky005** [comment]
SB 太多，自己骂吧。没有付出的家伙，懒得跟你纠缠。

**Comment by gdky005** [comment]
杠精太多，不适合说话。

**Comment by tanzhihao1qaz** [comment]
文档是多了点，但是作者也弄好目录了，想了解哪块就看哪块，一点都不麻烦啊。。。另外遇到问题可以先用排除法，我这边第一次请求也是失败的，我换了个很简单的接口再测试才成功，也发现自己的问题在哪里，心浮气躁没用的。最后我觉得如果连基本的请求都不成功的话，这个开源根本不会有8K的星星，先冷静从自己代码找问题，或者想我这样用些简单的接口看看是否成功。

**Comment by gdky005** [comment]
不置可否。自己体会去吧，也许对你来说很棒呢，对吧。

**Comment by gdky005** [comment]
感兴趣的同学，可以看评论：https://www.v2ex.com/t/502605

**Comment by tanzhihao1qaz** [comment]
都是程序员，搞得自己像个小孩一样发脾气，更不要观点不同就给别人扣杠精帽。如果你找到失败的问题确实是框架导致，大可以指出来让大家知道，大家也服你，但你就说请求不了，但又知道问题所在，反而喷和问题无关的文档，自然会惹来一些人对你的攻击，如果你当初心平气和地问，上面那位正常的话也不会这么强烈地回复你

**Comment by tanzhihao1qaz** [comment]
![image](https://user-images.githubusercontent.com/28348014/47708234-9a67bf00-dc68-11e8-8854-50e6f6406c42.png)
这就是我的请求，我也是用StringCallback，注意第一个红色箭头的泛型，我记得文档说过这个泛型不能不写

**Comment by gdky005** [comment]
@tanzhihao1qaz 终于看到了有价值和有意义的回复了，多谢。

刚删除了相关代码，懒得跟他纠缠。

你的回复值得肯定，但是楼上那位，就知道怼人，杠人，没有任何实质性的帮助。再次感谢。

**Comment by silencer001** [comment]
> @tanzhihao1qaz 终于看到了有价值和有意义的回复了，多谢。
> 
> 刚删除了相关代码，懒得跟他纠缠。
> 
> 你的回复值得肯定，但是楼上那位，就知道怼人，杠人，没有任何实质性的帮助。再次感谢。

“刚删除了相关代码，懒得跟他纠缠。”不应该首先向作者道歉吗？

**Comment by Youngjim77** [comment]
首先，我承认我是故意嘲讽你的，，但不是无脑“杠”你  因为我就是用这个作为网络请求框架，我觉得这个框架是真滴牛逼，看你的评论，气不过，嘲讽了你一句。
其次，我一直没和你说技术上的问题，因为你不是技术上的问题，是态度问题。要是真的写过程序，应该知道jsoncallback和jsoncallBack是没有区别的，因为写代码的时候都是联想的，而你连这个都不知道，就说作者写的什么废话，真的是悲哀。
还有你自己说说你编辑 和修改了多少条自己的评论，不好意思面对？怕你发上去的贴别人看了喷你？我现在我自己看了我的贴，我都觉得自己是好像一直在找你麻烦。
最后，你只要在这个贴，向作者认真得道歉，我也会把我的评论删掉。免得我们都“污染”了github，我们就都当作什么都没发生

**Comment by JessYanCoding** [comment]
OkGo 是一个值得尊敬的项目，是国内少有的文档能写的这么详细的开源项目，比很多大厂的文档都良心，您之所以喷文档是废话，也许是您无法理解一个开源作者想维护好一个优质开源项目需要花费多么大的精力，如果您能日复一日的坚持维护某一个开源项目，你哪怕换位思考都不会说出这样的话了

我作为一个长期持续维护多个开源项目，并且曾经给 OkGo 贡献过代码的旁观者，我能想象到如果这时作者看到您说的这些话，会有多么的伤心，诚然作者现在由于某些个人原因暂时性的放弃了框架的维护，但这并不是他的义务，也不能否定他之前为开源社区做出的巨大的贡献，在我们的职业生涯中会一直受益于这些开源作者的无私付出，但我们未曾给过他们任何形式的回报

哪怕您现在，在这个项目中暂时没有得到您想要得到的收益，甚至觉得给自己制造了麻烦，这时您可能会有情绪，但是请您不要在公众场所公开表达自己的消极情绪，这样会让自己成为大家集中攻击的目标，更会影响到其他开源项目使用者的情绪

并且会有更多坚持持续维护开源项目的开源作者，觉得不值得为这群人免费付出自己的时间来维护开源项目，这样会影响整个开源生态的发展，您是出了气，但是损失的却是大家的利益

**Comment by gdky005** [comment]
@Youngjim77

@silencer001

手机打字不方便，懒得喷你们，道歉 呵呵，不可能的事情！ 

写的文档就是烂，别不承认！

一个好的文档，应该看一眼就懂了，这个文档跳转了好几次，每次都能看到 要求支付的码，让人反感。 邀请打赏我觉得没问题啊，但是你起码把文档维护好呀。参考下  okhttp 的首页，以及其他网络层的 readme.md。


虚心接受，有则改之无则加勉！你只是一个使用者，我不太想跟你计较。本 issue 的目的只是想让文档简单点而已，你们玩道德绑架吗？这个库的的8000+  start 水的不行，已经有人在 v2ex 中分析过了为什么会这么高。 作者也是很有才的，懂的营销炒作。

我说的都是事实和问题，你们就逼着我 道歉，从没想过优化和解决问题。可能我当时的语气确实中了一些，今天意识到问题，已经修改措辞，尽量委婉一些，让这个 issue 看起来更加准确清晰。

**Comment by gdky005** [comment]
@Youngjim77

@silencer001

手机打字不方便，懒得喷你们，道歉 呵呵，不可能的事情！ 

写的文档就是烂，别不承认！

一个好的文档，应该看一眼就懂了，这个文档跳转了好几次，每次都能看到 要求支付的码，让人反感。 邀请打赏我觉得没问题啊，但是你起码把文档维护好呀。参考下  okhttp 的首页，以及其他网络层的 readme.md。


虚心接受，有则改之无则加勉！你只是一个使用者，我不太想跟你计较。本 issue 的目的只是想让文档简单点而已，你们玩道德绑架吗？这个库的的8000+  start 水的不行，已经有人在 v2ex 中分析过了为什么会这么高。 作者也是很有才的，懂的营销炒作。

我说的都是事实和问题，你们就逼着我 道歉，从没想过优化和解决问题。可能我当时的语气确实中了一些，今天意识到问题，已经修改措辞，尽量委婉一些，让这个 issue 看起来更加准确清晰。

**Comment by gdky005** [comment]
@Youngjim77

@silencer001

手机打字不方便，懒得喷你们，道歉 呵呵，不可能的事情！ 

写的文档就是烂，别不承认！

一个好的文档，应该看一眼就懂了，这个文档跳转了好几次，每次都能看到 要求支付的码，让人反感。 邀请打赏我觉得没问题啊，但是你起码把文档维护好呀。参考下  okhttp 的首页，以及其他网络层的 readme.md。


虚心接受，有则改之无则加勉！你只是一个使用者，我不太想跟你计较。本 issue 的目的只是想让文档简单点而已，你们玩道德绑架吗？这个库的的8000+  start 水的不行，已经有人在 v2ex 中分析过了为什么会这么高。 作者也是很有才的，懂的营销炒作。

我说的都是事实和问题，你们就逼着我 道歉，从没想过优化和解决问题。可能我当时的语气确实中了一些，今天意识到问题，已经修改措辞，尽量委婉一些，让这个 issue 看起来更加准确清晰。

**Comment by gdky005** [comment]
@Youngjim77

@silencer001

手机打字不方便，懒得喷你们，道歉 呵呵，不可能的事情！ 

写的文档就是烂，别不承认！

一个好的文档，应该看一眼就懂了，这个文档跳转了好几次，每次都能看到 要求支付的码，让人反感。 邀请打赏我觉得没问题啊，但是你起码把文档维护好呀。参考下  okhttp 的首页，以及其他网络层的 readme.md。


虚心接受，有则改之无则加勉！你只是一个使用者，我不太想跟你计较。本 issue 的目的只是想让文档简单点而已，你们玩道德绑架吗？这个库的的8000+  start 水的不行，已经有人在 v2ex 中分析过了为什么会这么高。 作者也是很有才的，懂的营销炒作。

我说的都是事实和问题，你们就逼着我 道歉，从没想过优化和解决问题。可能我当时的语气确实中了一些，今天意识到问题，已经修改措辞，尽量委婉一些，让这个 issue 看起来更加准确清晰。

**Comment by gdky005** [comment]
@Youngjim77

@silencer001

手机打字不方便，懒得喷你们，道歉 呵呵，不可能的事情！ 

写的文档就是烂，别不承认！

一个好的文档，应该看一眼就懂了，这个文档跳转了好几次，每次都能看到 要求支付的码，让人反感。 邀请打赏我觉得没问题啊，但是你起码把文档维护好呀。参考下  okhttp 的首页，以及其他网络层的 readme.md。


虚心接受，有则改之无则加勉！你只是一个使用者，我不太想跟你计较。本 issue 的目的只是想让文档简单点而已，你们玩道德绑架吗？这个库的的8000+  start 水的不行，已经有人在 v2ex 中分析过了为什么会这么高。 作者也是很有才的，懂的营销炒作。

我说的都是事实和问题，你们就逼着我 道歉，从没想过优化和解决问题。可能我当时的语气确实中了一些，今天意识到问题，已经修改措辞，尽量委婉一些，让这个 issue 看起来更加准确清晰。

**Comment by gdky005** [comment]
@Youngjim77

@silencer001

手机打字不方便，懒得喷你们，道歉 呵呵，不可能的事情！ 

写的文档就是烂，别不承认！

一个好的文档，应该看一眼就懂了，这个文档跳转了好几次，每次都能看到 要求支付的码，让人反感。 邀请打赏我觉得没问题啊，但是你起码把文档维护好呀。参考下  okhttp 的首页，以及其他网络层的 readme.md。


虚心接受，有则改之无则加勉！你只是一个使用者，我不太想跟你计较。本 issue 的目的只是想让文档简单点而已，你们玩道德绑架吗？这个库的的8000+  start 水的不行，已经有人在 v2ex 中分析过了为什么会这么高。 作者也是很有才的，懂的营销炒作。

我说的都是事实和问题，你们就逼着我 道歉，从没想过优化和解决问题。可能我当时的语气确实中了一些，今天意识到问题，已经修改措辞，尽量委婉一些，让这个 issue 看起来更加准确清晰。

**Comment by gdky005** [comment]
@JessYanCoding

你说的我都能理解，本来没想把这个事情搞大，我很喜欢开源组织，并且会参与一些开源组织。我开这个 issue,  只是想让文档简单明了一些，就这么简单。我也可以提交 PR,但是也得有人 review 和合并呀，我自己都用的不爽，还让我道歉，让我贡献，还不能说一点这个库的不好。这不是一个良性发展，慢慢演变成了: 你们都得向我俯首称臣，不容置疑，这是一种病态的表现。我也很感谢大家对开源的贡献，也从中受益。

**Comment by JessYanCoding** [comment]
@gdky005 建议您控制下自己的情绪，戾气不要这么重，您虽然没从这个开源项目中获得自己想要的收益，但是开源作者并不欠您的，作者在这件事情上从始至终也没表态过任何一句话，更没有恶意攻击过您，所以不管您怎么和别人互怼，有多么生气，请您别一直攻击作者和这个项目，更别拿 star 数，和支付码来恶意揣测作者的行为，什么俯首称臣这些词语也是您自己意淫出来的，这些对别人来说都是一种非常严重的伤害，作者并没有做错什么，作者在自己的能力范围之内力所能及的帮助一些自己能够帮助到的人，不求回报，虽然没能帮助到您，但是也并没有恶意伤害您

即然这件事弄的大家都很不愉快，大家都不再理睬就是了，这个世界上从来都不缺选择，更不缺后悔的选择，既然觉得自己之前的选择是错误的，就抛开所有负面情绪，继续前行去追求其他更好的风景即可，继续沉沦在之前的负面情绪当中，讨论一个不可能有结果的事，对自己来说也并不是一件好事，也不是一个聪明人会干的事

**Comment by silencer001** [comment]
> @Youngjim77
> 
> @silencer001
> 
> 手机打字不方便，懒得喷你们，道歉 呵呵，不可能的事情！
> 
> 写的文档就是烂，别不承认！
> 
> 一个好的文档，应该看一眼就懂了，这个文档跳转了好几次，每次都能看到 要求支付的码，让人反感。 邀请打赏我觉得没问题啊，但是你起码把文档维护好呀。参考下 okhttp 的首页，以及其他网络层的 readme.md。
> 
> 虚心接受，有则改之无则加勉！你只是一个使用者，我不太想跟你计较。本 issue 的目的只是想让文档简单点而已，你们玩道德绑架吗？这个库的的8000+ start 水的不行，已经有人在 v2ex 中分析过了为什么会这么高。 作者也是很有才的，懂的营销炒作。
> 
> 我说的都是事实和问题，你们就逼着我 道歉，从没想过优化和解决问题。可能我当时的语气确实中了一些，今天意识到问题，已经修改措辞，尽量委婉一些，让这个 issue 看起来更加准确清晰。

你为什么“懒得喷我”，我觉得你应该道歉，这就是你要喷我的理由吗？你的戾气真的很重喔

**Comment by stl714** [comment]
> ![image](https://user-images.githubusercontent.com/28348014/47708234-9a67bf00-dc68-11e8-8854-50e6f6406c42.png)
> 这就是我的请求，我也是用StringCallback，注意第一个红色箭头的泛型，我记得文档说过这个泛型不能不写

我发现onsuccess 回调中的 response.body() 在 200 下是空的，但是log中返回了body的值，不明白原因

**Comment by wylIwwg** [comment]
这开源库用了一年多才发现这里居然还有个傻逼，无能者，哎，你要是去找英文资料，是不是还要要求别人把中文文档给你准备好呀

**Comment by zhaoxiuyu** [comment]
文档还是不错的，也一直在用，就是文档里面某些图片加载不出来 丢失了。。。
