### ISSUE TITLE
每次请求网络都会触发两次网络访问。请问如何解决？

### ISSUE THREAD

**Issue by icodero** [jeasonlzy/okhttp-OkGo#79]
每次请求网络都会触发两次网络访问。请问如何解决？

**Comment by jeasonlzy** [comment]
可能是网址被重定向，抓包会请求两次，但是回调也只会执行一次。。。如果正常情况下也是两次。建议先检查代码，测试demo ，看是否是两次。。如果还有问题。。请把详细log发给我。。感谢。

**Comment by icodero** [comment]
谢谢！

**Comment by xyStephenZhou** [comment]
解决了吗
