### ISSUE TITLE
下载管理报权限错误

### ISSUE THREAD

**Issue by zlkk2013** [jeasonlzy/okhttp-OkGo#80]
华为p9，6.0系统，下载报java.io.FileNotFoundException：

10-24 11:29:41.513 17371-18199/com.lzy.demo W/System.err: java.io.FileNotFoundException: /storage/emulated/0/download/meilijia.apk: open failed: EACCES (Permission denied)
10-24 11:29:41.513 17371-18199/com.lzy.demo W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:459)
10-24 11:29:41.514 17371-18199/com.lzy.demo W/System.err:     at java.io.RandomAccessFile.<init>(RandomAccessFile.java:117)
10-24 11:29:41.514 17371-18199/com.lzy.demo W/System.err:     at com.lzy.okserver.download.DownloadTask$ProgressRandomAccessFile.<init>(DownloadTask.java:241)
10-24 11:29:41.514 17371-18199/com.lzy.demo W/System.err:     at com.lzy.okserver.download.DownloadTask.doInBackground(DownloadTask.java:153)
10-24 11:29:41.514 17371-18199/com.lzy.demo W/System.err:     at com.lzy.okserver.download.DownloadTask.doInBackground(DownloadTask.java:30)
10-24 11:29:41.514 17371-18199/com.lzy.demo W/System.err:     at com.lzy.okserver.task.PriorityAsyncTask$1.call(PriorityAsyncTask.java:69)
10-24 11:29:41.514 17371-18199/com.lzy.demo W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
10-24 11:29:41.514 17371-18199/com.lzy.demo W/System.err:     at com.lzy.okserver.task.PriorityRunnable.run(PriorityRunnable.java:20)
10-24 11:29:41.515 17371-18199/com.lzy.demo W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
10-24 11:29:41.515 17371-18199/com.lzy.demo W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
10-24 11:29:41.515 17371-18199/com.lzy.demo W/System.err:     at java.lang.Thread.run(Thread.java:833)
10-24 11:29:41.515 17371-18199/com.lzy.demo W/System.err: Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
10-24 11:29:41.516 17371-18199/com.lzy.demo W/System.err:     at libcore.io.Posix.open(Native Method)
10-24 11:29:41.516 17371-18199/com.lzy.demo W/System.err:     at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
10-24 11:29:41.516 17371-18199/com.lzy.demo W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:445)

**Comment by jeasonlzy** [comment]
框架内部不做 6.0 的动态权限检查，也无法做检查，所以如果要下载，涉及到sd卡权限的，建议先自己主动申请权限。
