### ISSUE TITLE
我在使用的时候遇到了一个很棘手的异常

### ISSUE THREAD

**Issue by Jeff-1203** [jeasonlzy/okhttp-OkGo#817]
OKGO: <-- HTTP FAILED: java.io.IOException: Canceled

我在onResume里面请求OKGO  第一次进来页面是没问题的  去别的页面更改了某些东西  然后回到当前页面走了onResume 但是直接出异常了

**Comment by wzxlucky** [comment]
同样遇到这个问题 @yinking1203
