### ISSUE TITLE
Eclipse使用jar包下载出现问题

### ISSUE THREAD

**Issue by AmiGWF** [jeasonlzy/okhttp-OkGo#82]
你好，我使用/jar下面提供的okgo-2.0.0和okserver-1.1.0两个jar包，进行下载是报错了。
我的工程jar包都导入了，也在application中进行了初始化，下载路径也没有问题，只是下载一个apk，下面是报错信息，是不是单单导入这两个jar包有问题呢？
`10-25 15:44:39.158: E/AndroidRuntime(4537): FATAL EXCEPTION: main
10-25 15:44:39.158: E/AndroidRuntime(4537): java.lang.ExceptionInInitializerError
10-25 15:44:39.158: E/AndroidRuntime(4537):     at com.lzy.okgo.request.BaseRequest.<init>(BaseRequest.java:58)
10-25 15:44:39.158: E/AndroidRuntime(4537):     at com.lzy.okgo.request.GetRequest.<init>(GetRequest.java:20)
10-25 15:44:39.158: E/AndroidRuntime(4537):     at com.lzy.okgo.OkGo.get(OkGo.java:103)
10-25 15:44:39.158: E/AndroidRuntime(4537):     at com.giant.downthread.MainActivity.onClick(MainActivity.java:67)
10-25 15:44:39.158: E/AndroidRuntime(4537):     at android.view.View.performClick(View.java:4261)
10-25 15:44:39.158: E/AndroidRuntime(4537):     at android.view.View$PerformClick.run(View.java:17344)
10-25 15:44:39.158: E/AndroidRuntime(4537):     at android.os.Handler.handleCallback(Handler.java:615)
10-25 15:44:39.158: E/AndroidRuntime(4537):     at android.os.Handler.dispatchMessage(Handler.java:92)
10-25 15:44:39.158: E/AndroidRuntime(4537):     at android.os.Looper.loop(Looper.java:137)
10-25 15:44:39.158: E/AndroidRuntime(4537):     at android.app.ActivityThread.main(ActivityThread.java:4944)
10-25 15:44:39.158: E/AndroidRuntime(4537):     at java.lang.reflect.Method.invokeNative(Native Method)
10-25 15:44:39.158: E/AndroidRuntime(4537):     at java.lang.reflect.Method.invoke(Method.java:511)
10-25 15:44:39.158: E/AndroidRuntime(4537):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1043)
10-25 15:44:39.158: E/AndroidRuntime(4537):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810)
10-25 15:44:39.158: E/AndroidRuntime(4537):     at dalvik.system.NativeStart.main(Native Method)
10-25 15:44:39.158: E/AndroidRuntime(4537): Caused by: java.lang.NoClassDefFoundError: okhttp3.MediaType
10-25 15:44:39.158: E/AndroidRuntime(4537):     at com.lzy.okgo.model.HttpParams.<clinit>(HttpParams.java:28)
10-25 15:44:39.158: E/AndroidRuntime(4537):     ... 15 more`

**Comment by jeasonlzy** [comment]
原因一：没有导入提供的  okhttp.jar  和 okie.jar
原因二：项目方法数超过 64k，具体64k方法超限问题请自行百度，解决方法也很简单。
