### ISSUE TITLE
post请求如何修改Content-Type

### ISSUE THREAD

**Issue by aojiaoqiang** [jeasonlzy/okhttp-OkGo#829]
如题，post请求想要修改一下Content-Type

**Comment by iMucc** [comment]
我也想问, 后台要求传递contentType: “application/json”, 死活都搞不定咋回事.......

**Comment by rockerkekex** [comment]
> 我也想问, 后台要求传递contentType: “application/json”, 死活都搞不定咋回事.......

请问这个问题解决了吗
