### ISSUE TITLE
关于cookie的使用

### ISSUE THREAD

**Issue by PingerOne** [jeasonlzy/okhttp-OkGo#83]
说明里没说Cookie怎么使用，能大致说一下嘛？最近在做一个自动登录的模块，以前没接触过，不是很清除。求大神解惑~

**Comment by jeasonlzy** [comment]
最近我会补上 cookie 的详细的说明。。简单来讲，就是框架只要初始化的时候设置了 持久化的cookie处理，那么框架的行为就喝 标准的http协议中的 cookie 行为是一致的，客户端请求会自动携带服务器使用 set-cookie 返回的数据。必须是使用 set-cookie 返回的框架才会自动处理，否则是无法自动管理的。。

**Comment by jeasonlzy** [comment]
最的文档中已经具有了详细的文档说明。。欢迎查看。。
