### ISSUE TITLE
post提交中文字符串乱码

### ISSUE THREAD

**Issue by wcglws** [jeasonlzy/okhttp-OkGo#84]
请问大神  
1，post提交中文字符串乱码，在服务器中就显示乱码了。。
2，在application中初始化的时候设置超时重连的方法提示找不到      请大神解惑？
![image](https://cloud.githubusercontent.com/assets/16982083/19711055/9488f6b2-9b65-11e6-9daa-e8582292693f.png)

**Comment by wcglws** [comment]
![image](https://cloud.githubusercontent.com/assets/16982083/19710307/0aa0a9f4-9b60-11e6-88ab-f3282e5910b8.png)

**Comment by jeasonlzy** [comment]
1. post 提交字符串，默认是按照 utf8 提交的，这个编码目前是无法修改的，所以服务端需要按照 utf8 解码，至于服务端返回的数据，无论 utf8 还是 gbk编码都可以，框架会自动适配编码。。
2. 这个重试次数是新功能，我还为发布，只是把代码提交到了 github 的仓库中，但是并没有发布到 jcenter 和 maven 仓库，所以直接使用 compile 依赖远程仓库是找不到这个方法的，我会在一到两周内更新完毕后，发布 jcenter 和 maven，到时候就有了。。

**Comment by wcglws** [comment]
服务器的伙计说他们就是用的u8解的，难道是在逗我么。。。
还有我换了xutils3来提交竟然奇迹般的好了，，不乱码

**Comment by jeasonlzy** [comment]
详细的情况建议抓包看数据。。看你发送的数据和格式是否是服务端需要的。。

**Comment by tanweijiu** [comment]
post默认的是application/x-www-form-urlencoded，所以针对使用tomcat的服务器必须指定contenttype里的charset为utf8.。。或者直接.isMultipart(true)使用表单的方式。不然就是中文乱码
