### ISSUE TITLE
如果我使用了预埋证书，那么我在访问微信接口的时候也要导入他们的证书吗？

### ISSUE THREAD

**Issue by Freedomhxb** [jeasonlzy/okhttp-OkGo#840]
如果我使用了预埋证书，那么我在访问微信接口的时候也要导入他们的证书吗？（如果没有导入微信的证书，就会报出CertPathValidatorException），有没有一种方式就是如果是我们自己的网站就用预埋证书，其他的网站则不用验证证书？

**Comment by Freedomhxb** [comment]
自定义规则，已解决

**Comment by kayroc** [comment]
@Freedomhxb 请问怎么解决的这个问题？
