### ISSUE TITLE
单独设置某个链接请求的超时时间 怎么设置？

### ISSUE THREAD

**Issue by anjiao** [jeasonlzy/okhttp-OkGo#86]
RT

**Comment by jeasonlzy** [comment]
在请求的时候 ，除基本params参数外，可以额外指定 三个 超时时间，与初始化的方法一样。。

**Comment by anjiao** [comment]
那会不会  其他请求的超时时间 会有影响呢？ 我已经全局设置了一个

**Comment by jeasonlzy** [comment]
不会。单独设置只会拿一个请求生效。。其余的任然是全局的

**Comment by BIGMONK** [comment]
原来okhttputils的超时可以直接设定的，这个okgo是要重新setOkHttpClient？

**Comment by jeasonlzy** [comment]
对的。以前内部也是重建了一个okhttpclient来实现的。现在只是让用户自己来做了。。

**Comment by hss01248** [comment]
也就是说还是得自己做,没有直接的对每个请求直接.setTimeOut()方法

**Comment by xiakejian** [comment]
OkGo这个类是个单例，okhttpclient是所有请求公用的，那么setokhttpclient后所有请求的okhttpclient不就都改变了吗？还怎么设置单个请求的timeout时间？

**Comment by YaDongHouse** [comment]
可以给每个request设置一个OkHttpClient单独设置超时
