### ISSUE TITLE
downloadProgress回调一次问题，拦截器做了token失效处理不能屏蔽

### ISSUE THREAD

**Issue by DotMatrixDev1024** [jeasonlzy/okhttp-OkGo#866]
如题，有没有其他什么办法?

**Comment by DotMatrixDev1024** [comment]
拦截器部分代码
 

-  @Override
    public Response intercept(Chain chain) throws IOException {
        Request request = chain.request();
        Response response = chain.proceed(request);
        ResponseBody responseBody = response.body();
        BufferedSource source = responseBody.source();
        source.request(Long.MAX_VALUE); // Buffer the entire body.
        Buffer buffer = source.buffer();
        Charset charset = UTF8;
        MediaType contentType = responseBody.contentType();
        if (contentType != null) {
            charset = contentType.charset(UTF8);
        }
        String bodyString = buffer.clone().readString(charset);
        //LogUtil.i(TAG,"网络拦截器:" + bodyString + " host:" + request.url().toString());
        boolean isText = isText(contentType);
        if (!isText) {
            return response;
        }
        //判断响应是否过期（无效）
        if (isResponseExpired(response, bodyString)) {
            return responseExpired(chain, bodyString);
        }
        return response;
    }

**Comment by DotMatrixDev1024** [comment]
添加了拦截器，就不能使用下载功能了？

**Comment by DotMatrixDev1024** [comment]
@jeasonlzy 还望大佬回复下

**Comment by APLK** [comment]
可以在拦截器中对下载地址单独处理,如果当前请求方式是get并且url是你的下载地址,则不进行拦截处理,直接返回response即可

**Comment by DotMatrixDev1024** [comment]
谢谢
