### ISSUE TITLE
okserver多图上传的时候，会有几率报下面错误

### ISSUE THREAD

**Issue by yuzhiqiang1993** [jeasonlzy/okhttp-OkGo#87]
I/shipApp: parseNetworkResponse  Exception
11-01 14:20:46.712 24305-25218/com.ship.yzq.ship I/shipApp: {"shipId":"425","categoryNo":8,"imei":"869465020815960","RESULT":0,"REASON":"上传文件成功！"}
11-01 14:20:46.713 24305-25218/com.ship.yzq.ship W/System.err: java.lang.IllegalStateException: closed
11-01 14:20:46.714 24305-25218/com.ship.yzq.ship W/System.err:     at okhttp3.internal.http.Http1xStream$ChunkedSource.read(Http1xStream.java:414)
11-01 14:20:46.715 24305-25218/com.ship.yzq.ship W/System.err:     at okio.Buffer.writeAll(Buffer.java:993)
11-01 14:20:46.715 24305-25218/com.ship.yzq.ship W/System.err:     at okio.RealBufferedSource.readByteArray(RealBufferedSource.java:106)
11-01 14:20:46.715 24305-25218/com.ship.yzq.ship W/System.err:     at okhttp3.ResponseBody.bytes(ResponseBody.java:128)
11-01 14:20:46.715 24305-25218/com.ship.yzq.ship W/System.err:     at okhttp3.ResponseBody.string(ResponseBody.java:154)
11-01 14:20:46.715 24305-25218/com.ship.yzq.ship W/System.err:     at com.ship.yzq.ship.adapter.TransferAdapter$MyListener.parseNetworkResponse(TransferAdapter.java:109)
11-01 14:20:46.715 24305-25218/com.ship.yzq.ship W/System.err:     at com.lzy.okserver.upload.UploadTask.doInBackground(UploadTask.java:71)
11-01 14:20:46.715 24305-25218/com.ship.yzq.ship W/System.err:     at com.lzy.okserver.upload.UploadTask.doInBackground(UploadTask.java:23)
11-01 14:20:46.716 24305-25218/com.ship.yzq.ship W/System.err:     at com.lzy.okserver.task.PriorityAsyncTask$1.call(PriorityAsyncTask.java:69)
11-01 14:20:46.716 24305-25218/com.ship.yzq.ship W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
11-01 14:20:46.716 24305-25218/com.ship.yzq.ship W/System.err:     at com.lzy.okserver.task.PriorityRunnable.run(PriorityRunnable.java:20)
11-01 14:20:46.716 24305-25218/com.ship.yzq.ship W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
11-01 14:20:46.716 24305-25218/com.ship.yzq.ship W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
11-01 14:20:46.717 24305-25218/com.ship.yzq.ship W/System.err:     at java.lang.Thread.run(Thread.java:818)
11-01 14:20:46.718 24305-24305/com.ship.yzq.ship I/shipApp: listener为：com.ship.yzq.ship.adapter.TransferAdapter$MyListener@5c225f0

**Comment by yuzhiqiang1993** [comment]
虽然报错了，但是图片已经成功上传到服务器了，uploadinfo状态就是error了

**Comment by magic0908** [comment]
请问一下，图片转换成文件流的形式上传是直接调用 .setCertificates(stream)这个方法吗？公司的后台是以流的形式接受的，但是我这么传后台却显示图片没通过验证

**Comment by yuzhiqiang1993** [comment]
我这边没有转换，直接将文件传进去就行了，
![image](https://cloud.githubusercontent.com/assets/18605757/20205314/b923c84e-a812-11e6-8b5f-3715e6fa4bfc.png)

**Comment by magic0908** [comment]
好的，多谢解答

**Comment by jeasonlzy** [comment]
.setCertificates(stream) 这个方法是设置 https 的证书的。。并不是上传文件的。。
