### ISSUE TITLE
post请求content-type不支持application/x-www-form-urlencoded

### ISSUE THREAD

**Issue by huazhiyuan2008** [jeasonlzy/okhttp-OkGo#88]
如题， post请求content-type不支持application/x-www-form-urlencoded

**Comment by jeasonlzy** [comment]
不知道你说的不支持是什么意思。默认没有文件使用post ，content-type 就自动是 application/x-www-form-urlencoded

**Comment by huazhiyuan2008** [comment]
![image](https://cloud.githubusercontent.com/assets/2877748/20047839/f863c388-a4f2-11e6-8f26-5003e14e8691.png)
Post 中方法upString upJson upBytes都不是application/x-www-form-urlencoded

**Comment by jeasonlzy** [comment]
肯定啊。。因为他们的数据格式就不是 application/x-www-form-urlencoded，只有普通的键值对才是你要的这个，其余的 upJson 就肯定要是 application/json;charset=utf-8，这是基本的http协议约定。

**Comment by huazhiyuan2008** [comment]
加个方法就行了 upString(String string, MediaType mediaType)， 有时候服务端就是需要不停的MediaType, 我提过PR, 可以看下

**Comment by jeasonlzy** [comment]
ok，已合并。。后期更新会随 2.1 版本发布。。

**Comment by jeasonlzy** [comment]
2.1 版本已经发布。。
