### ISSUE TITLE
这个框架没人维护了，有别的好用的框架推荐吗

### ISSUE THREAD

**Issue by clj12081103** [jeasonlzy/okhttp-OkGo#883]

**Comment by just-to-Cyberspace** [comment]
为什么这么说

**Comment by CodeK1988** [comment]
这也不能怪大佬不维护 你看看提的一些都是什么问题 。。。 文档不看 google不查

**Comment by clj12081103** [comment]
挺好的一个框架，可惜不维护了。

**Comment by yaochangliang159** [comment]
我用的时候完全能满足我的需求啊，也没发现这个框架的什么BUG

**Comment by Mazhanzhu** [comment]
我这用了很多年了，从我知道这个框架以来，就一直在用，就目前来说，可以满足我的一切需求，要是有的需求，这里满足不了的话，可能我自己搞得也费尽，总结一句话，能用就用这个，满足不了的话，就直接上Retrofit！
