### ISSUE TITLE
网络请求无法取消

### ISSUE THREAD

**Issue by zhaichuankai** [jeasonlzy/okhttp-OkGo#890]
接手别人写的项目，使用如下方式无法取消网络请求
Request
pq.tag(ApiConfig.questionapi_studentPaper);
        return pq.converter(new ZJJsonConvert<>(type))
            .adapt(new ObservableBody<T>())
            .subscribeOn(Schedulers.io())
            .observeOn(AndroidSchedulers.mainThread());

Dialog
dialog.setOnCancelListener(dialog1 -> {
                        OkGo.getInstance().cancelTag(ApiConfig.questionapi_studentPaper);
                    });

**Comment by helloworld10010** [comment]
？
