### ISSUE TITLE
OKGO post方式请求时怎样修改为表单的形式？

### ISSUE THREAD

**Issue by huan920924** [jeasonlzy/okhttp-OkGo#90]
我知道现在只要在params中添加一个文件就会自动变成表单,但是当我没有文件上传的时候我也需要他是以表单的形式。求助

**Comment by jeasonlzy** [comment]
这样子确实目前是不支持的。。临时的解决方案是传一个空的file。后期我加一个参数可以强制使用表单格式提交。。其实这主要是服务端不标准导致的，理论上没有文件不应该使用表单提交的。

**Comment by huan920924** [comment]
万分感谢，随时在关注你的更新

**Comment by jeasonlzy** [comment]
2.1 已经增强该功能，即使没有文件 也可以提交表单。
