### ISSUE TITLE
请求重试次数的方法不能调用了么？还是更换名字了

### ISSUE THREAD

**Issue by 379548560** [jeasonlzy/okhttp-OkGo#91]

**Comment by pengbs** [comment]
同问，没有那方法啦

**Comment by MoneyNotFoundException** [comment]
同问，还望作者解答下 @jeasonlzy

**Comment by jeasonlzy** [comment]
那个是暂时没有发布的版本。。一些小的修改我就直接 push 到github 上了。。大版本的更新才会发布到 jcenter，你们如果使用 compile 'com.lzy.net:okgo:2.0.0'   这样是没有的。如果直接依赖项目源码，就会有了。。后续我会尽快同步到 jcenter 上。

**Comment by jeasonlzy** [comment]
2.1 已经发布。
