### ISSUE TITLE
多请求统一回调?

### ISSUE THREAD

**Issue by weinierfei** [jeasonlzy/okhttp-OkGo#93]
我记得前段时间看这个的时候,说明文档里头有多请求统一回调的说明?难道是我记错了!!!

**Comment by jeasonlzy** [comment]
多请求统一回调是什么意思。。用同一个 callback 吗？ 目前 okgo 是不打算支持这样的写法的。。

**Comment by weinierfei** [comment]
对,就是一个页面有好几个请求,可能有的页面需要这几个请求都返回后才继续执行;这个时候,就有这样的需求了

**Comment by jeasonlzy** [comment]
不同的请求是需要不同的 Callback的，因为他们的业务逻辑都不一样。没必要放在一个 callbcak中。因为我自己时不建议这么写的。所以 okgo 也不会支持这样的写法。

**Comment by weinierfei** [comment]
好的,感谢回复
