### ISSUE TITLE
eclicpse downloadManager addTask() nullPointException

### ISSUE THREAD

**Issue by littleKun** [jeasonlzy/okhttp-OkGo#96]
按照所提供的demo进行练习，
 switch (downloadInfo.getState()) {
                    case DownloadManager.PAUSE:
                    case DownloadManager.NONE:
                    case DownloadManager.ERROR:

//11-09 12:46:35.138: E/AndroidRuntime(23800): java.lang.NullPointerException
//11-09 12:46:35.138: E/AndroidRuntime(23800): 	at //com.lzy.okserver.download.DownloadManager.addTask(DownloadManager.java:99)
//11-09 12:46:35.138: E/AndroidRuntime(23800): 	at //com.lzy.okserver.download.DownloadManager.addTask(DownloadManager.java:80)
//11-09 12:46:35.138: E/AndroidRuntime(23800): 	at //com.kun.aiyousystem1.fragment.NetResourceFragment$viewHolder.onClick(NetResourceFragment.java://273)
//在此处出现空指针 实在找不到理由
                        downloadManager.addTask(downloadInfo.getUrl(), downloadInfo.getRequest(), downloadInfo.getListener());
/
                        break;
                    case DownloadManager.DOWNLOADING:
                        downloadManager.pauseTask(downloadInfo.getUrl());
                        break;
                    case DownloadManager.FINISH:
                        if (ApkUtils.isAvailable(DownloadManagerActivity.this, new File(downloadInfo.getTargetPath()))) {
                            ApkUtils.uninstall(DownloadManagerActivity.this, ApkUtils.getPackageName(DownloadManagerActivity.this, downloadInfo.getTargetPath()));
                        } else {
                            ApkUtils.install(DownloadManagerActivity.this, new File(downloadInfo.getTargetPath()));
                        }
                        break;
                }
                refresh();

**Comment by jeasonlzy** [comment]
详细原因到群里问吧。。这样子不好解决。。
