### ISSUE TITLE
关于Base64图片上传的问题

### ISSUE THREAD

**Issue by XiaoMa2016** [jeasonlzy/okhttp-OkGo#98]
后台提供的接口是"key,value"形式的给我的，就是说一个"key",后面的参数是一个很长的base64字符串。
我把图片转成了base64，有的图片很大，所以我加了一个HUD的loading，但是在上传的时候loading会卡住，这个是为什么呢。按道理说请求是另外在线程的。我试了用handler来更新loading照样不行。
我知道后台接口不该这么写，但是要他改又不改，作者您有什么好的解决办法么，或者说造成loading卡住的原因是什么

**Comment by jeasonlzy** [comment]
这个首先图片转成string后，是大数据量，而okgo有些参数的预处理是在主线程的，后台线程当然也负责一部分。。所以可能导致卡顿，可以先尝试取消初始化的时候 debug 方法的调用，禁止打印log，因为这里也会处理大量的数据，看能不能缓解你的问题。。

**Comment by m2kl1m** [comment]
您好，我是最近用的OkGo，想问下您是如何把base64字符串作为参数请求的呢？

**Comment by jeasonlzy** [comment]
具体使用方法参考[OkGo文档](https://github.com/jeasonlzy/okhttp-OkGo/wiki)
