### ISSUE TITLE
关于文件File下载请求

### ISSUE THREAD

**Issue by gallonyin** [jeasonlzy/okhttp-OkGo#99]
OkGo.get(Urls.URL_DOWNLOAD)//
            .tag(this)//
            .execute(new FileCallback() {  //文件下载时，可以指定下载的文件目录和文件名
        @Override
        public void onSuccess(File file, Call call, Response response) {
            // file 即为文件数据，文件保存在指定目录
        }
        @Override
        public void downloadProgress(long currentSize, long totalSize, float progress, long networkSpeed) {
            //这里回调下载进度(该回调在主线程,可以直接更新ui)
        }
    });

支持大文件传输吗 
File如果比较大有几十兆或更高

**Comment by jeasonlzy** [comment]
没有问题。无论文件多大都可以。。别说几十M，就是几个G也没有问题，只要你的手机空间足够。。
